import type { NormalizedCostEvidence, FinOpsQualification, FinOpsCurrentness } from "./index.js";

export type CommercialEconomicEvidence = Readonly<{ revisionRef:string; scopeRef:string; periodRef:string; amountMinor:number; currency:string; provenanceRef:string; currentness:FinOpsCurrentness; population:FinOpsQualification }>;
export type UnitEconomicsEvidence = Readonly<{ kind:"UNIT_ECONOMICS_EVIDENCE"; revisionRef:string; scopeRef:string; periodRef:string; numerator:Readonly<{ identity:"COMMERCIAL_AMOUNT"; amountMinor:number; currency:string; revisionRef:string; provenanceRef:string }>; denominator:Readonly<{ identity:"TECHNOLOGY_COST"; amountMinor:number; currency:string; revisionRef:string; provenanceRef:string }>; ratio:number; provenanceRef:string; currentness:"CURRENT"; population:"COMPLETE"; commercialAuthority:false }>;
export type UnitEconomicsResult = Readonly<{state:"QUALIFIED";evidence:UnitEconomicsEvidence}>|Readonly<{state:"UNKNOWN";reason:string}>;
export type ComplexityDimension = Readonly<{ name:string; factRef:string; revisionRef:string; provenanceRef:string; value:number|null; currentness:FinOpsCurrentness; population:FinOpsQualification }>;
export type OperationalComplexityProfile = Readonly<{ kind:"OPERATIONAL_COMPLEXITY_PROFILE"; revisionRef:string; scopeRef:string; periodRef:string; dimensions:ReadonlyArray<ComplexityDimension>; provenanceRef:string; aggregateScore:false }>;
const tok=/^\S+$/; function token(v:string,p:string){if(!tok.test(v))throw new TypeError(`Invalid FinOps evidence at ${p}`);return v;}
export function deriveUnitEconomics(input:Readonly<{cost:NormalizedCostEvidence;commercial:CommercialEconomicEvidence;periodRef:string;revisionRef:string;provenanceRef:string}>):UnitEconomicsResult{const {cost,commercial}=input;if(cost.currentness!=="CURRENT"||cost.population!=="COMPLETE"||commercial.currentness!=="CURRENT"||commercial.population!=="COMPLETE")return{state:"UNKNOWN",reason:"economic-evidence-not-qualified"};if(cost.scopeRef!==commercial.scopeRef)return{state:"UNKNOWN",reason:"economic-scope-mismatch"};if(cost.currency!==commercial.currency)return{state:"UNKNOWN",reason:"economic-currency-mismatch"};if(commercial.periodRef!==input.periodRef)return{state:"UNKNOWN",reason:"economic-period-mismatch"};if(cost.amountMinor===0)return{state:"UNKNOWN",reason:"zero-cost-denominator"};return{state:"QUALIFIED",evidence:{kind:"UNIT_ECONOMICS_EVIDENCE",revisionRef:token(input.revisionRef,"$revisionRef"),scopeRef:cost.scopeRef,periodRef:input.periodRef,numerator:{identity:"COMMERCIAL_AMOUNT",amountMinor:commercial.amountMinor,currency:commercial.currency,revisionRef:commercial.revisionRef,provenanceRef:commercial.provenanceRef},denominator:{identity:"TECHNOLOGY_COST",amountMinor:cost.amountMinor,currency:cost.currency,revisionRef:cost.revisionRef,provenanceRef:cost.provenanceRef},ratio:commercial.amountMinor/cost.amountMinor,provenanceRef:token(input.provenanceRef,"$provenanceRef"),currentness:"CURRENT",population:"COMPLETE",commercialAuthority:false}};}
export function buildOperationalComplexityProfile(input:Readonly<{revisionRef:string;scopeRef:string;periodRef:string;provenanceRef:string;dimensions:ReadonlyArray<ComplexityDimension>}>):OperationalComplexityProfile{return{kind:"OPERATIONAL_COMPLEXITY_PROFILE",revisionRef:token(input.revisionRef,"$revisionRef"),scopeRef:token(input.scopeRef,"$scopeRef"),periodRef:token(input.periodRef,"$periodRef"),dimensions:input.dimensions.map((d,i)=>({...d,name:token(d.name,`$dimensions[${i}].name`),factRef:token(d.factRef,`$dimensions[${i}].factRef`),revisionRef:token(d.revisionRef,`$dimensions[${i}].revisionRef`),provenanceRef:token(d.provenanceRef,`$dimensions[${i}].provenanceRef`),value:d.currentness==="CURRENT"&&d.population==="COMPLETE"?d.value:null})),provenanceRef:token(input.provenanceRef,"$provenanceRef"),aggregateScore:false};}
