import { normalizeCurrentnessQualification, normalizeDefinitionRevisionRef, type CurrentnessQualification, type DefinitionRevisionRef } from "../semantic-substrate/index.js";

export const LOCALITY_RECONCILIATION_CONTRACT_VERSION = "1.0.0" as const;
export type LocalityKind = "LOCAL" | "STATION" | "FLEET";
export type LocalityAuthority = "LOCAL_AUTHORITY" | "CANONICAL_SOURCE" | "OBSERVED";
export type LocalityConflict = "NONE" | "KNOWN" | "UNKNOWN";
export type ReconciliationState = "RECONCILED" | "PENDING" | "PARTITIONED" | "UNKNOWN";
export type LocalityObservation = Readonly<{ kind: LocalityKind; localityRef: string; subject: DefinitionRevisionRef; currentness: CurrentnessQualification; authority: LocalityAuthority }>;
export type ResidualLocalityLineage = Readonly<{ localityRef: string; subject: DefinitionRevisionRef; state: "VISIBLE" | "DRAINED" | "UNKNOWN" }>;
export type LocalityReconciliation = Readonly<{ contractVersion: typeof LOCALITY_RECONCILIATION_CONTRACT_VERSION; canonicalSource: DefinitionRevisionRef; observations: readonly LocalityObservation[]; conflict: LocalityConflict; reconciliation: ReconciliationState; residuals: readonly ResidualLocalityLineage[] }>;

type R=Record<string,unknown>;
const rec=(v:unknown,l:string):R=>{if(typeof v!=="object"||v===null||Array.isArray(v))throw new Error(`${l} must be an object`);return v as R};
const exact=(r:R,f:readonly string[],l:string)=>{for(const k of Object.keys(r))if(!f.includes(k))throw new Error(`${l} has unexpected field ${k}`);for(const k of f)if(!(k in r))throw new Error(`${l} is missing field ${k}`)};
const text=(v:unknown,l:string)=>{if(typeof v!=="string"||!v.trim())throw new Error(`${l} must be non-empty`);return v.trim()};
const key=(v:DefinitionRevisionRef)=>[v.semanticOwner,v.semanticKind,v.canonicalRef,v.definitionRef,v.revisionOwner,v.revisionDimension,v.revisionRef].join("\u0000");
export function normalizeLocalityObservation(input:unknown):LocalityObservation{const r=rec(input,"locality observation");exact(r,["kind","localityRef","subject","currentness","authority"],"locality observation");if(r.kind!=="LOCAL"&&r.kind!=="STATION"&&r.kind!=="FLEET")throw new Error("invalid locality kind");if(r.authority!=="LOCAL_AUTHORITY"&&r.authority!=="CANONICAL_SOURCE"&&r.authority!=="OBSERVED")throw new Error("invalid locality authority");const subject=normalizeDefinitionRevisionRef(r.subject);const currentness=normalizeCurrentnessQualification(r.currentness);const localityRef=text(r.localityRef,"localityRef");if(key(currentness.subject)!==key(subject)||currentness.localityScope!==localityRef)throw new Error("currentness must qualify the exact subject and locality");return Object.freeze({kind:r.kind,localityRef,subject,currentness,authority:r.authority});}
export function normalizeLocalityReconciliation(input:unknown):LocalityReconciliation{const r=rec(input,"locality reconciliation");exact(r,["contractVersion","canonicalSource","observations","conflict","reconciliation","residuals"],"locality reconciliation");if(r.contractVersion!==LOCALITY_RECONCILIATION_CONTRACT_VERSION)throw new Error("unsupported locality reconciliation contract version");const canonicalSource=normalizeDefinitionRevisionRef(r.canonicalSource);if(!Array.isArray(r.observations)||r.observations.length===0)throw new Error("at least one locality observation is required");const observations=Object.freeze(r.observations.map(normalizeLocalityObservation));if(r.conflict!=="NONE"&&r.conflict!=="KNOWN"&&r.conflict!=="UNKNOWN")throw new Error("invalid conflict state");if(r.reconciliation!=="RECONCILED"&&r.reconciliation!=="PENDING"&&r.reconciliation!=="PARTITIONED"&&r.reconciliation!=="UNKNOWN")throw new Error("invalid reconciliation state");if(!Array.isArray(r.residuals))throw new Error("residuals must be an array");const residuals=Object.freeze(r.residuals.map(v=>{const x=rec(v,"residual locality lineage");exact(x,["localityRef","subject","state"],"residual locality lineage");if(x.state!=="VISIBLE"&&x.state!=="DRAINED"&&x.state!=="UNKNOWN")throw new Error("invalid residual state");return Object.freeze({localityRef:text(x.localityRef,"residual localityRef"),subject:normalizeDefinitionRevisionRef(x.subject),state:x.state});}));if(r.reconciliation==="RECONCILED"){if(r.conflict!=="NONE")throw new Error("conflict cannot be silently resolved");if(observations.some(o=>o.currentness.state!=="CURRENT"))throw new Error("stale or UNKNOWN locality cannot be promoted to current global truth");if(residuals.some(x=>x.state!=="DRAINED"))throw new Error("residual lineage must remain visible until drained");if(!observations.some(o=>o.authority==="CANONICAL_SOURCE"&&key(o.subject)===key(canonicalSource)))throw new Error("local authority cannot substitute canonical source ownership");}if(r.conflict==="UNKNOWN"&&r.reconciliation==="RECONCILED")throw new Error("UNKNOWN conflict requires reconcile-before-retry");return Object.freeze({contractVersion:LOCALITY_RECONCILIATION_CONTRACT_VERSION,canonicalSource,observations,conflict:r.conflict,reconciliation:r.reconciliation,residuals});}
