import assert from "node:assert/strict";
import test from "node:test";
import {
  aiMediatedCandidateEstablishesCanonicalTruth,
  aiMediatedInferenceEstablishesAuthority,
  aiMediatedOrdinaryGenerationRemainsAvailable,
  aiMediatedProviderBindingEstablishesSupport,
  aiMediatedProviderBindingOwnsQualification,
  aiMediatedProvenanceReplayMatches,
  assertAiMediatedProviderBinding,
  assertAiMediatedWorkspaceSnapshot,
  computeAiMediatedProvenanceHash,
  evaluateAiMediatedProviderBinding,
  evaluateAiMediatedWorkspace,
  type AiMediatedProviderBinding,
  type AiMediatedProvenanceRef,
  type AiMediatedWorkspaceSnapshot,
} from "../../packages/contracts/ai-mediated-assistance/index.js";
import { aiMediatedDispositionEstablishesActionEligibility, aiMediatedDispositionEstablishesAuthority, aiMediatedManualPathRemainsAvailable, evaluateAiMediatedCandidateDisposition, type AiMediatedCandidateDisposition } from "../../packages/contracts/ai-mediated-assistance/disposition.js";
import type { ProviderBindingQualification, ProviderQualificationStatus } from "../../packages/contracts/provider/qualification.js";
import type { CurrentnessState, DefinitionRevisionRef } from "../../packages/contracts/semantic-substrate/index.js";

function provenance(overrides: Partial<AiMediatedProvenanceRef> = {}): AiMediatedProvenanceRef[] { return [{ kind: "PROMPT", ref: "prompt:work-order-summary", revisionRef: "prompt-revision:4", digest: "sha256:prompt-4", currentness: "CURRENT", completeness: "KNOWN" }, { kind: "CONTEXT", ref: "workflow:work-order-42", revisionRef: "workflow-revision:10", digest: "sha256:workflow-10", currentness: "CURRENT", completeness: "KNOWN", ...overrides }, { kind: "EVIDENCE", ref: "evidence:work-order-42", revisionRef: "evidence-revision:10", digest: "sha256:evidence-10", currentness: "CURRENT", completeness: "KNOWN" }]; }
function workspace(refs: readonly AiMediatedProvenanceRef[] = provenance()): AiMediatedWorkspaceSnapshot { return { identity: { workspaceRef: "ai-workspace:work-order-assistance", workspaceRevisionRef: "ai-workspace-revision:2", gatewayRef: "ai-gateway:bounded-assistance", gatewayRevisionRef: "ai-gateway-revision:3", locality: { scope: "STATION", scopeRef: "station:porto-alegre" } }, provenance: refs, candidateLineage: { candidateRef: "candidate:work-order-summary", candidateRevisionRef: "candidate-revision:1", sourceKind: "CONTEXT", sourceRef: "workflow:work-order-42", sourceRevisionRef: "workflow-revision:10", provenanceHash: computeAiMediatedProvenanceHash(refs) } }; }
function revision(canonicalRef: string, revisionRef: string): DefinitionRevisionRef { return { contractVersion: "1.0.0", semanticOwner: "provider", semanticKind: "provider-binding", canonicalRef, definitionRef: `${canonicalRef}:definition`, revisionOwner: "provider", revisionDimension: "qualification", revisionRef }; }
function providerQualification(disposition: ProviderQualificationStatus = "SUPPORTED", currentness: CurrentnessState = "CURRENT", evidenceAuthority: ProviderBindingQualification["evidenceAuthority"] = "AUTHORITATIVE"): ProviderBindingQualification { const binding = revision("provider-binding:replaceable", "provider-binding-revision:7"); const evidence = revision("provider-evidence:qualification", "provider-evidence-revision:12"); return { contractVersion: "1.0.0", binding, providerRealizationRef: "provider-realization:opaque", evidence, currentness: { contractVersion: "1.0.0", subject: evidence, revisionVector: [{ revisionOwner: "provider", revisionDimension: "qualification", revisionRef: evidence.revisionRef }], temporal: { occurredAt: null, observedAt: "2026-09-14T20:00:00Z", evaluatedAt: "2026-09-14T20:00:00Z", effectiveFrom: "2026-09-14T20:00:00Z", effectiveUntil: null, reconciledAt: "2026-09-14T20:00:00Z" }, populationScope: "provider-binding:replaceable", localityScope: "FLEET", currentnessHorizon: { assessedAt: "2026-09-14T20:00:00Z", validUntil: "2026-09-15T20:00:00Z" }, state: currentness, reason: "explicit qualification evidence" }, evidenceAuthority, dimensions: [{ dimension: "candidate-generation", status: disposition, reason: "explicit qualification dimension" }], disposition }; }
function providerBinding(overrides: Partial<AiMediatedProviderBinding> = {}): AiMediatedProviderBinding { return { bindingRef: "provider-binding:replaceable", bindingRevisionRef: "provider-binding-revision:7", modelRef: "model-family:replaceable", modelRevisionRef: "model-revision:2026-09", currentness: "CURRENT", qualification: providerQualification(), ...overrides }; }
function governedDisposition(snapshot: AiMediatedWorkspaceSnapshot, binding: AiMediatedProviderBinding, overrides: Partial<AiMediatedCandidateDisposition> = {}): AiMediatedCandidateDisposition { return { candidate: snapshot.candidateLineage, providerBindingRef: binding.bindingRef, providerBindingRevisionRef: binding.bindingRevisionRef, governingOwnerRef: "human-owner:1", governingOwnerRevisionRef: "owner-revision:4", decision: "ACCEPT", currentness: "CURRENT", completeness: "KNOWN", rationaleRef: "rationale:1", ...overrides }; }

// TASK-551/552 regression proofs remain intentionally compact here.
test("AI workspace remains deterministic and non-authoritative", () => { const snapshot = workspace(); assert.doesNotThrow(() => assertAiMediatedWorkspaceSnapshot(snapshot)); assert.equal(evaluateAiMediatedWorkspace(snapshot), "AVAILABLE"); assert.equal(aiMediatedInferenceEstablishesAuthority(snapshot), false); assert.equal(aiMediatedCandidateEstablishesCanonicalTruth(snapshot.candidateLineage), false); });
test("provider binding remains replaceable and qualification-owned elsewhere", () => { const primary = providerBinding(); assert.doesNotThrow(() => assertAiMediatedProviderBinding(primary)); assert.equal(evaluateAiMediatedProviderBinding(primary), "ELIGIBLE"); assert.equal(aiMediatedProviderBindingEstablishesSupport(primary), false); assert.equal(aiMediatedProviderBindingOwnsQualification(primary), false); });
test("stale and unresolved evidence never strengthens", () => { assert.equal(evaluateAiMediatedWorkspace(workspace(provenance({ currentness: "STALE" }))), "DEGRADED"); assert.equal(evaluateAiMediatedWorkspace(workspace(provenance({ completeness: "CONFLICTED" }))), "RECONCILE_BEFORE_RETRY"); assert.equal(aiMediatedOrdinaryGenerationRemainsAvailable("RECONCILE_BEFORE_RETRY"), true); });
test("provenance replay remains revision sensitive", () => { const refs = provenance(); assert.equal(aiMediatedProvenanceReplayMatches(workspace(refs), refs), true); assert.equal(aiMediatedProvenanceReplayMatches(workspace(refs), provenance({ revisionRef: "workflow-revision:11" })), false); });

test("TASK-553 candidate disposition is owner-attributed without authority or action eligibility", () => { const snapshot = workspace(); const binding = providerBinding(); const disposition = governedDisposition(snapshot, binding); assert.equal(evaluateAiMediatedCandidateDisposition(snapshot, binding, disposition), "GOVERNED"); assert.equal(aiMediatedDispositionEstablishesAuthority(disposition), false); assert.equal(aiMediatedDispositionEstablishesActionEligibility(disposition), false); assert.notEqual(disposition.candidate.candidateRef, disposition.governingOwnerRef); });
test("TASK-553 UNKNOWN/conflict reconcile and manual path coexists", () => { const snapshot = workspace(); const binding = providerBinding(); const base = governedDisposition(snapshot, binding, { decision: "REVISE" }); for (const patch of [{ currentness: "UNKNOWN" as const }, { completeness: "CONFLICTED" as const }, { completeness: "INCONCLUSIVE" as const }]) { const evaluation = evaluateAiMediatedCandidateDisposition(snapshot, binding, { ...base, ...patch }); assert.equal(evaluation, "RECONCILE_BEFORE_RETRY"); assert.equal(aiMediatedManualPathRemainsAvailable(evaluation), true); } });
test("TASK-553 lineage mismatches are rejected", () => { const snapshot = workspace(); const binding = providerBinding(); const base = governedDisposition(snapshot, binding, { decision: "REJECT" }); assert.throws(() => evaluateAiMediatedCandidateDisposition(snapshot, binding, { ...base, candidate: { ...snapshot.candidateLineage, candidateRevisionRef: "candidate-revision:999" } }), /candidate-lineage-mismatch/); assert.throws(() => evaluateAiMediatedCandidateDisposition(snapshot, binding, { ...base, providerBindingRevisionRef: "provider-binding-revision:999" }), /provider-binding-mismatch/); });

// TASK-554 integrated Construction B proof composes existing contracts only.
test("TASK-554 integrated happy path preserves revision-aware provenance, replaceable binding and governed non-authoritative disposition", () => { const refs = provenance(); const snapshot = workspace(refs); const binding = providerBinding(); const disposition = governedDisposition(snapshot, binding); assert.equal(aiMediatedProvenanceReplayMatches(snapshot, refs), true); assert.equal(evaluateAiMediatedWorkspace(snapshot), "AVAILABLE"); assert.equal(evaluateAiMediatedProviderBinding(binding), "ELIGIBLE"); assert.equal(evaluateAiMediatedCandidateDisposition(snapshot, binding, disposition), "GOVERNED"); assert.equal(aiMediatedInferenceEstablishesAuthority(snapshot), false); assert.equal(aiMediatedCandidateEstablishesCanonicalTruth(snapshot.candidateLineage), false); assert.equal(aiMediatedProviderBindingOwnsQualification(binding), false); assert.equal(aiMediatedProviderBindingEstablishesSupport(binding), false); assert.equal(aiMediatedDispositionEstablishesAuthority(disposition), false); assert.equal(aiMediatedDispositionEstablishesActionEligibility(disposition), false); assert.equal(aiMediatedManualPathRemainsAvailable("GOVERNED"), true); });
test("TASK-554 stale, PARTIAL, UNKNOWN, INCONCLUSIVE and CONFLICTED inputs never strengthen the integrated path", () => { const stale = workspace(provenance({ currentness: "STALE" })); assert.notEqual(evaluateAiMediatedWorkspace(stale), "AVAILABLE"); const partial = workspace(provenance({ completeness: "PARTIAL" })); assert.notEqual(evaluateAiMediatedWorkspace(partial), "AVAILABLE"); const conflicted = workspace(provenance({ completeness: "CONFLICTED" })); assert.equal(evaluateAiMediatedWorkspace(conflicted), "RECONCILE_BEFORE_RETRY"); for (const qualification of [providerBinding({ currentness: "UNKNOWN" }), providerBinding({ qualification: providerQualification("INCONCLUSIVE") }), providerBinding({ qualification: providerQualification("UNKNOWN") })]) { assert.notEqual(evaluateAiMediatedProviderBinding(qualification), "ELIGIBLE"); } const snapshot = workspace(); const binding = providerBinding(); for (const patch of [{ currentness: "UNKNOWN" as const }, { completeness: "INCONCLUSIVE" as const }, { completeness: "CONFLICTED" as const }]) { const evaluation = evaluateAiMediatedCandidateDisposition(snapshot, binding, governedDisposition(snapshot, binding, patch)); assert.equal(evaluation, "RECONCILE_BEFORE_RETRY"); assert.equal(aiMediatedManualPathRemainsAvailable(evaluation), true); } });
test("TASK-554 adversarial revision drift cannot be replayed or disposed as the current candidate", () => { const refs = provenance(); const snapshot = workspace(refs); const binding = providerBinding(); assert.equal(aiMediatedProvenanceReplayMatches(snapshot, provenance({ revisionRef: "workflow-revision:11" })), false); assert.throws(() => evaluateAiMediatedCandidateDisposition(snapshot, binding, governedDisposition(snapshot, binding, { candidate: { ...snapshot.candidateLineage, provenanceHash: "sha256:stale" } })), /candidate-lineage-mismatch/); assert.throws(() => evaluateAiMediatedCandidateDisposition(snapshot, binding, governedDisposition(snapshot, binding, { providerBindingRevisionRef: "provider-binding-revision:stale" })), /provider-binding-mismatch/); });
