import assert from "node:assert/strict";
import test from "node:test";
import { BROWNFIELD_RECOVERY_CONTRACT_VERSION, normalizeBrownfieldRecovery } from "../../packages/contracts/brownfield/recovery.js";
import { EXTERNAL_IDENTITY_COEXISTENCE_CONTRACT_VERSION } from "../../packages/contracts/brownfield/external-identity-coexistence.js";
import { LOCALITY_RECONCILIATION_CONTRACT_VERSION } from "../../packages/contracts/locality/reconciliation.js";
import { SEMANTIC_SUBSTRATE_CONTRACT_VERSION } from "../../packages/contracts/semantic-substrate/index.js";

const subject={contractVersion:SEMANTIC_SUBSTRATE_CONTRACT_VERSION,semanticOwner:"brownfield",semanticKind:"external-binding",canonicalRef:"asset-b",definitionRef:"binding:device-7",revisionOwner:"brownfield",revisionDimension:"binding-revision",revisionRef:"r2"} as const;
const currentness=(localityScope:string,state:"CURRENT"|"STALE"|"UNKNOWN"|"INSUFFICIENT"="CURRENT",populationScope="tenant-a/assets")=>({contractVersion:SEMANTIC_SUBSTRATE_CONTRACT_VERSION,subject,revisionVector:[{revisionOwner:subject.revisionOwner,revisionDimension:subject.revisionDimension,revisionRef:subject.revisionRef}],temporal:{occurredAt:null,observedAt:"2026-09-11T01:00:00Z",evaluatedAt:"2026-09-11T01:01:00Z",effectiveFrom:null,effectiveUntil:null,reconciledAt:state==="CURRENT"?"2026-09-11T01:01:00Z":null},populationScope,localityScope,currentnessHorizon:{assessedAt:"2026-09-11T01:01:00Z",validUntil:"2026-09-11T02:01:00Z"},state,reason:`${state}`});
const locality=(overrides:Record<string,unknown>={})=>({contractVersion:LOCALITY_RECONCILIATION_CONTRACT_VERSION,canonicalSource:subject,observations:[{kind:"FLEET",localityRef:"fleet:primary",subject,currentness:currentness("fleet:primary"),authority:"CANONICAL_SOURCE"}],conflict:"NONE",reconciliation:"RECONCILED",residuals:[{localityRef:"station:legacy",subject,state:"DRAINED"}],...overrides});
const coexistence=(drained=true)=>({contractVersion:EXTERNAL_IDENTITY_COEXISTENCE_CONTRACT_VERSION,sourceAuthorities:[{sourceRef:"source-old",scopeRef:"tenant-a/assets",epoch:1,fencingToken:"fence-1",canonical:false},{sourceRef:"source-new",scopeRef:"tenant-a/assets",epoch:2,fencingToken:"fence-2",canonical:true}],bindings:[{bindingRef:"binding-old",providerRef:"provider-a",scopeRef:"tenant-a/assets",externalId:"device-7",canonicalEntityRef:"asset-a",bindingRevision:"r1",epoch:1,sourceRef:"source-old",fencingToken:"fence-1",evidenceRef:"old",evidenceAuthority:"AUTHORITATIVE",state:drained?"DRAINED":"RESIDUAL"},{bindingRef:"binding-new",providerRef:"provider-a",scopeRef:"tenant-a/assets",externalId:"device-7",canonicalEntityRef:"asset-b",bindingRevision:"r2",epoch:2,sourceRef:"source-new",fencingToken:"fence-2",evidenceRef:"new",evidenceAuthority:"AUTHORITATIVE",state:"ACTIVE"}],rebindings:[{rebindRef:"rebind-1",priorBindingRef:"binding-old",nextBindingRef:"binding-new",qualification:"CONFIRMED",evidenceRef:"proof",evidenceAuthority:"AUTHORITATIVE"}],residualCohorts:[{cohortRef:"residual-device-7",providerRef:"provider-a",scopeRef:"tenant-a/assets",externalId:"device-7",bindingRefs:["binding-old"],completeness:"KNOWN",drained}]});
const recovery=(overrides:Record<string,unknown>={})=>({contractVersion:BROWNFIELD_RECOVERY_CONTRACT_VERSION,coexistence:coexistence(true),locality:locality(),drainageEvidence:[{cohortRef:"residual-device-7",evidenceRef:"drain-proof",evidenceAuthority:"AUTHORITATIVE",completeness:"KNOWN"}],disposition:"RECOVERY_ELIGIBLE",...overrides});

test("accepts recovery only after authoritative drainage and locality reconciliation",()=>{assert.equal(normalizeBrownfieldRecovery(recovery()).disposition,"RECOVERY_ELIGIBLE");});
test("rejects hidden drainage evidence",()=>{assert.throws(()=>normalizeBrownfieldRecovery({...recovery(),drainageEvidence:[]}),/explicit AUTHORITATIVE KNOWN drainage evidence/);});
test("rejects UNKNOWN drainage strengthening",()=>{assert.throws(()=>normalizeBrownfieldRecovery({...recovery(),drainageEvidence:[{cohortRef:"residual-device-7",evidenceRef:"weak",evidenceAuthority:"AUTHORITATIVE",completeness:"UNKNOWN"}]}),/AUTHORITATIVE KNOWN drainage evidence/);});
test("keeps undrained residual cohorts reconcile-required",()=>{assert.equal(normalizeBrownfieldRecovery(recovery({coexistence:coexistence(false),drainageEvidence:[],disposition:"RECONCILE_REQUIRED"})).disposition,"RECONCILE_REQUIRED");});
test("rejects recovery eligibility while residual lineage remains visible",()=>{assert.throws(()=>normalizeBrownfieldRecovery(recovery({coexistence:coexistence(false),drainageEvidence:[]})),/reconcile-before-retry/);});
test("rejects Station Fleet reconnect with UNKNOWN conflict as recovery eligible",()=>{assert.throws(()=>normalizeBrownfieldRecovery(recovery({locality:locality({observations:[{kind:"STATION",localityRef:"station:offline",subject,currentness:currentness("station:offline","UNKNOWN"),authority:"OBSERVED"}],conflict:"UNKNOWN",reconciliation:"PARTITIONED",residuals:[{localityRef:"station:offline",subject,state:"VISIBLE"}]})})),/reconcile-before-retry/);});
test("rejects locality truth for a different canonical entity",()=>{const wrongSubject={...subject,canonicalRef:"asset-other"}; assert.throws(()=>normalizeBrownfieldRecovery(recovery({locality:locality({canonicalSource:wrongSubject,observations:[{kind:"FLEET",localityRef:"fleet:primary",subject:wrongSubject,currentness:{...currentness("fleet:primary"),subject:wrongSubject},authority:"CANONICAL_SOURCE"}],residuals:[{localityRef:"station:legacy",subject:wrongSubject,state:"DRAINED"}]})})),/canonical identity\/revision\/scope/);});
test("rejects locality truth for a stale binding revision",()=>{const staleSubject={...subject,revisionRef:"r1"}; assert.throws(()=>normalizeBrownfieldRecovery(recovery({locality:locality({canonicalSource:staleSubject,observations:[{kind:"FLEET",localityRef:"fleet:primary",subject:staleSubject,currentness:{...currentness("fleet:primary"),subject:staleSubject,revisionVector:[{revisionOwner:staleSubject.revisionOwner,revisionDimension:staleSubject.revisionDimension,revisionRef:staleSubject.revisionRef}]},authority:"CANONICAL_SOURCE"}],residuals:[{localityRef:"station:legacy",subject:staleSubject,state:"DRAINED"}]})})),/canonical identity\/revision\/scope/);});
test("rejects locality truth qualified for another population scope",()=>{assert.throws(()=>normalizeBrownfieldRecovery(recovery({locality:locality({observations:[{kind:"FLEET",localityRef:"fleet:primary",subject,currentness:currentness("fleet:primary","CURRENT","tenant-b/assets"),authority:"CANONICAL_SOURCE"}]})})),/canonical identity\/revision\/scope/);});
test("inherits stale-authority fencing during rebinding recovery",()=>{const input=coexistence(true); const stale={...input,bindings:[{...input.bindings[0],state:"ACTIVE"},input.bindings[1]]}; assert.throws(()=>normalizeBrownfieldRecovery(recovery({coexistence:stale})),/stale binding cannot resurrect authority/);});
test("inherits single canonical truth during recovery",()=>{const input=coexistence(true); const dual={...input,sourceAuthorities:input.sourceAuthorities.map(x=>({...x,canonical:true}))}; assert.throws(()=>normalizeBrownfieldRecovery(recovery({coexistence:dual})),/exactly one canonical source authority/);});
test("rejects external ID reuse after fencing without confirmed authoritative rebinding",()=>{const input=coexistence(true); const reused={...input,bindings:[input.bindings[0],{...input.bindings[1],canonicalEntityRef:"asset-c"}],rebindings:[]}; assert.throws(()=>normalizeBrownfieldRecovery(recovery({coexistence:reused})),/external ID reuse cannot imply same or rebound entity without confirmed authoritative rebinding/);});
test("rejects rebound-to-old epoch during recovery",()=>{const input=coexistence(true); const oldEpoch={...input,bindings:[input.bindings[0],{...input.bindings[1],epoch:1,sourceRef:"source-old",fencingToken:"fence-1"}]}; assert.throws(()=>normalizeBrownfieldRecovery(recovery({coexistence:oldEpoch})),/(rebinding must advance epoch|stale binding cannot resurrect authority)/);});
