import assert from "node:assert/strict";
import test from "node:test";
import { bindCustomerContract, commercialRevisionState, selectCommercialRevision, type CommercialPrice } from "../../packages/contracts/commercial/index.js";

const now="2026-09-19T12:00:00Z";
const base={id:"price:standard",scopeRef:"scope:tenant-a",provenanceRef:"catalog:approved",currentness:"CURRENT",population:"COMPLETE",planRef:"plan:standard",currency:"BRL"} as const;
const rev1:CommercialPrice={...base,kind:"PRICE",revisionRef:"rev:1",effectiveAt:"2026-01-01T00:00:00Z",amountMinor:10000};
const rev2:CommercialPrice={...base,kind:"PRICE",revisionRef:"rev:2",effectiveAt:"2026-09-01T00:00:00Z",supersedesRevisionRef:"rev:1",amountMinor:12000};

test("TASK-567 selects the unique effective commercial revision",()=>{ const selected=selectCommercialRevision([rev1,rev2],base.id,base.scopeRef,now); assert.equal(selected.state,"CURRENT"); assert.equal(selected.revision?.revisionRef,"rev:2"); assert.equal(selected.revision?.amountMinor,12000); assert.equal(selected.revision?.provenanceRef,"catalog:approved"); });
test("missing commercial facts remain unknown rather than becoming truth",()=>{ assert.deepEqual(selectCommercialRevision([],base.id,base.scopeRef,now),{state:"UNKNOWN"}); assert.deepEqual(selectCommercialRevision([rev2],"price:missing",base.scopeRef,now),{state:"UNKNOWN"}); });
test("conflicting current revisions do not become commercial truth",()=>{ const competing:CommercialPrice={...base,kind:"PRICE",revisionRef:"rev:parallel",effectiveAt:"2026-09-10T00:00:00Z",amountMinor:9000}; assert.equal(selectCommercialRevision([rev1,rev2,competing],base.id,base.scopeRef,now).state,"CONFLICTED"); });
test("partial unknown stale and not-yet-effective facts cannot strengthen selection",()=>{ const partial:CommercialPrice={...rev2,revisionRef:"rev:partial",population:"PARTIAL"}; const unknown:CommercialPrice={...rev2,revisionRef:"rev:unknown",currentness:"UNKNOWN"}; const stale:CommercialPrice={...rev2,revisionRef:"rev:stale",currentness:"STALE"}; const future:CommercialPrice={...rev2,revisionRef:"rev:future",effectiveAt:"2027-01-01T00:00:00Z"}; assert.equal(commercialRevisionState(partial,now),"UNKNOWN"); assert.equal(commercialRevisionState(unknown,now),"UNKNOWN"); assert.equal(commercialRevisionState(stale,now),"STALE"); assert.equal(commercialRevisionState(future,now),"NOT_YET_EFFECTIVE"); });
test("malformed effective timestamps fail closed instead of becoming current commercial truth",()=>{ const invalidStart:CommercialPrice={...rev2,revisionRef:"rev:invalid-start",effectiveAt:"2026-99-99T00:00:00Z"}; const invalidEnd:CommercialPrice={...rev2,revisionRef:"rev:invalid-end",effectiveUntil:"2026-99-99T00:00:00Z"}; assert.throws(()=>commercialRevisionState(invalidStart,now),/Invalid commercial contract/); assert.throws(()=>commercialRevisionState(invalidEnd,now),/Invalid commercial contract/); assert.throws(()=>selectCommercialRevision([invalidStart],base.id,base.scopeRef,now),/Invalid commercial contract/); });
test("customer contract pins the qualified price revision and provenance instead of following later catalog changes",()=>{ const contract=bindCustomerContract({contract:{id:"contract:1",revisionRef:"rev:1",scopeRef:base.scopeRef,provenanceRef:"agreement:signed",effectiveAt:now,currentness:"CURRENT",population:"COMPLETE",customerRef:"customer:1",offerRef:"offer:standard",planRef:base.planRef},price:rev2,at:now}); assert.equal(contract.priceRef,"price:standard"); assert.equal(contract.priceRevisionRef,"rev:2"); assert.equal(contract.priceProvenanceRef,"catalog:approved"); const rev3:CommercialPrice={...rev2,revisionRef:"rev:3",supersedesRevisionRef:"rev:2",provenanceRef:"catalog:later",amountMinor:15000}; assert.equal(contract.priceRevisionRef,"rev:2"); assert.equal(contract.priceProvenanceRef,"catalog:approved"); assert.equal(rev3.revisionRef,"rev:3"); });
test("unrelated or non-current price cannot be bound to a customer contract",()=>{ const contract={id:"contract:2",revisionRef:"rev:1",scopeRef:base.scopeRef,provenanceRef:"agreement:signed",effectiveAt:now,currentness:"CURRENT",population:"COMPLETE",customerRef:"customer:2",offerRef:"offer:standard",planRef:base.planRef} as const; assert.throws(()=>bindCustomerContract({contract,price:{...rev2,planRef:"plan:other"},at:now})); assert.throws(()=>bindCustomerContract({contract,price:{...rev2,population:"UNKNOWN"},at:now})); });
