import assert from "node:assert/strict";
import test from "node:test";
import { DATA_SCHEMA_COEXISTENCE_CONTRACT_VERSION, historicalRecordUsesExactProducingRevision, normalizeReaderWriterCoexistence } from "../../packages/contracts/data-schema/coexistence.js";

const rev=(revisionRef:string,kind="canonical-schema")=>({contractVersion:"1.0.0" as const,semanticOwner:"data-schema",semanticKind:kind,canonicalRef:"customer-record",definitionRef:"customer-record-definition",revisionOwner:"data-schema",revisionDimension:"schema",revisionRef});
const currentness=(subject:ReturnType<typeof rev>,populationScope:string,localityScope:string,state:"CURRENT"|"STALE"|"UNKNOWN"|"INSUFFICIENT"="CURRENT",validUntil="2026-09-10T13:20:00Z")=>({contractVersion:"1.0.0" as const,subject,revisionVector:[{revisionOwner:"data-schema",revisionDimension:"schema",revisionRef:subject.revisionRef}],temporal:{occurredAt:null,observedAt:"2026-09-10T12:20:00Z",evaluatedAt:null,effectiveFrom:null,effectiveUntil:null,reconciledAt:null},populationScope,localityScope,currentnessHorizon:{assessedAt:"2026-09-10T12:20:00Z",validUntil},state,reason:"cohort evidence"});
const cohort=(role:"READER"|"WRITER",schemaRevision:ReturnType<typeof rev>,overrides:Record<string,unknown>={})=>({role,cohortRef:`${role.toLowerCase()}-${schemaRevision.revisionRef}`,schemaRevision,populationScope:"fleet-a",localityScope:"station-a",populationCount:10,completeness:"KNOWN",compatibility:"COMPATIBLE",currentness:currentness(schemaRevision,"fleet-a","station-a"),...overrides});
const base=()=>({contractVersion:DATA_SCHEMA_COEXISTENCE_CONTRACT_VERSION,coexistenceRevision:{...rev("coexist-r1","schema-coexistence"),canonicalRef:"customer-record-coexistence",definitionRef:"customer-record-coexistence-definition"},evaluatedAt:"2026-09-10T12:30:00Z",historicalRecords:[{recordRef:"record-001",producingSchemaRevision:rev("r1"),sourceRevision:rev("source-r1","source-schema")}],readerCohorts:[cohort("READER",rev("r1")),cohort("READER",rev("r2"))],writerCohorts:[cohort("WRITER",rev("r2"))]});

test("TASK-507 preserves historical producing revision while old/new cohorts coexist",()=>{const normalized=normalizeReaderWriterCoexistence(base());assert.equal(normalized.readerCohorts.length,2);assert.equal(historicalRecordUsesExactProducingRevision(normalized.historicalRecords[0]!,rev("r1")),true);assert.equal(historicalRecordUsesExactProducingRevision(normalized.historicalRecords[0]!,rev("r2")),false);});

test("TASK-507 rejects population/locality currentness strengthening",()=>{assert.throws(()=>normalizeReaderWriterCoexistence({...base(),readerCohorts:[cohort("READER",rev("r1"),{currentness:currentness(rev("r1"),"other-fleet","station-a")})]}),/population scope/);assert.throws(()=>normalizeReaderWriterCoexistence({...base(),readerCohorts:[cohort("READER",rev("r1"),{currentness:currentness(rev("r1"),"fleet-a","other-station")})]}),/locality scope/);});

test("TASK-507 preserves UNKNOWN/PARTIAL residual population instead of treating it as zero",()=>{const normalized=normalizeReaderWriterCoexistence({...base(),readerCohorts:[cohort("READER",rev("r1"),{populationCount:"UNKNOWN",completeness:"PARTIAL",compatibility:"PARTIAL"})]});assert.equal(normalized.readerCohorts[0]?.populationCount,"UNKNOWN");assert.equal(normalized.readerCohorts[0]?.completeness,"PARTIAL");assert.throws(()=>normalizeReaderWriterCoexistence({...base(),readerCohorts:[cohort("READER",rev("r1"),{populationCount:0,completeness:"UNKNOWN",compatibility:"UNKNOWN"})]}),/preserve populationCount as UNKNOWN/);});

test("TASK-507 rejects latest-revision substitution and stale compatibility promotion",()=>{assert.throws(()=>normalizeReaderWriterCoexistence({...base(),readerCohorts:[cohort("READER",rev("r1"),{currentness:currentness(rev("r2"),"fleet-a","station-a")})]}),/subject must exactly match/);assert.throws(()=>normalizeReaderWriterCoexistence({...base(),readerCohorts:[cohort("READER",rev("r1"),{currentness:currentness(rev("r1"),"fleet-a","station-a","STALE")})]}),/cannot be promoted/);});

test("TASK-507 rejects compatibility evidence reuse outside its currentness horizon",()=>{assert.throws(()=>normalizeReaderWriterCoexistence({...base(),readerCohorts:[cohort("READER",rev("r1"),{currentness:currentness(rev("r1"),"fleet-a","station-a","CURRENT","2026-09-10T12:25:00Z")})]}),/outside its currentness horizon/);assert.throws(()=>normalizeReaderWriterCoexistence({...base(),evaluatedAt:"2026-09-10T12:10:00Z"}),/outside its currentness horizon/);});

test("TASK-507 rejects hidden reader or writer residual classes",()=>{assert.throws(()=>normalizeReaderWriterCoexistence({...base(),readerCohorts:[]}),/explicit reader and writer cohorts/);assert.throws(()=>normalizeReaderWriterCoexistence({...base(),writerCohorts:[]}),/explicit reader and writer cohorts/);});
