import assert from "node:assert/strict";
import test from "node:test";
import { SOURCE_OF_TRUTH_CUTOVER_CONTRACT_VERSION, normalizeSourceOfTruthCutover } from "../../packages/contracts/data-schema/source-of-truth-cutover.js";

const rev=(revisionRef:string,kind="canonical-schema")=>({contractVersion:"1.0.0" as const,semanticOwner:"data-schema",semanticKind:kind,canonicalRef:"customer-record",definitionRef:"customer-record-definition",revisionOwner:"data-schema",revisionDimension:"schema",revisionRef});
const cutoverRev=()=>({...rev("cutover-r1","source-cutover"),canonicalRef:"customer-cutover",definitionRef:"customer-cutover-definition"});
const currentness=(subject:ReturnType<typeof cutoverRev>,populationScope="tenant-a/customer",localityScope="region-a",state:"CURRENT"|"STALE"|"UNKNOWN"|"INSUFFICIENT"="CURRENT",validUntil="2026-09-10T14:00:00Z")=>({contractVersion:"1.0.0" as const,subject,revisionVector:[{revisionOwner:"data-schema",revisionDimension:"schema",revisionRef:subject.revisionRef}],temporal:{occurredAt:null,observedAt:"2026-09-10T13:00:00Z",evaluatedAt:null,effectiveFrom:null,effectiveUntil:null,reconciledAt:null},populationScope,localityScope,currentnessHorizon:{assessedAt:"2026-09-10T13:00:00Z",validUntil},state,reason:"residual cohort observation"});
const authority=(sourceRef:string,epoch:number,canonical:boolean,fencingToken=`fence-${epoch}-${sourceRef}`)=>({sourceRef,scopeRef:"tenant-a/customer",epoch,fencingToken,canonical});
const lineage=(overrides:Record<string,unknown>={})=>({lineageRef:"lineage-1",mode:"CDC",sourceRef:"source-old",targetRef:"source-new",sourceSchemaRevision:rev("r1"),producingSchemaRevision:rev("r1"),targetSchemaRevision:rev("r2"),executedAt:"2026-09-10T13:00:00Z",acknowledgedAt:"2026-09-10T13:01:00Z",executionSucceeded:true,adoption:"PARTIAL",convergence:"PARTIAL",...overrides});
const residual=(kind:"SOURCE"|"READER"|"WRITER"|"REPLICATION",overrides:Record<string,unknown>={})=>({cohortRef:`${kind.toLowerCase()}-residual`,cohortKind:kind,populationScope:"tenant-a/customer",localityScope:"region-a",populationCount:"UNKNOWN",completeness:"UNKNOWN",drained:false,currentness:currentness(cutoverRev()),...overrides});
const allResiduals=()=>[residual("SOURCE"),residual("READER"),residual("WRITER"),residual("REPLICATION")];
const base=()=>({contractVersion:SOURCE_OF_TRUTH_CUTOVER_CONTRACT_VERSION,cutoverRevision:cutoverRev(),scopeRef:"tenant-a/customer",evaluatedAt:"2026-09-10T13:02:00Z",authorities:[authority("source-old",1,false),authority("source-new",2,true)],lineage:[lineage()],residualCohorts:allResiduals()});

test("TASK-508 preserves exactly one canonical source while dual-write/coexistence remains bounded",()=>{const normalized=normalizeSourceOfTruthCutover({...base(),lineage:[lineage({mode:"DUAL_WRITE"})]});assert.equal(normalized.authorities.filter((entry)=>entry.canonical).length,1);assert.equal(normalized.lineage[0]?.mode,"DUAL_WRITE");assert.equal(normalized.lineage[0]?.producingSchemaRevision.revisionRef,"r1");});

test("TASK-508 rejects dual canonical truth and fencing epoch reuse",()=>{assert.throws(()=>normalizeSourceOfTruthCutover({...base(),authorities:[authority("source-old",2,true),authority("source-new",2,true)]}),/exactly one canonical/);assert.throws(()=>normalizeSourceOfTruthCutover({...base(),authorities:[authority("source-old",2,false,"old-token"),authority("source-new",2,true,"new-token")]}),/fencing epoch cannot be reused/);});

test("TASK-508 rejects stale writer resurrection",()=>{assert.throws(()=>normalizeSourceOfTruthCutover({...base(),authorities:[authority("source-old",1,true),authority("source-new",2,false)]}),/stale fenced source/);});

test("TASK-508 preserves lineage and keeps acknowledgement execution adoption and convergence distinct",()=>{const normalized=normalizeSourceOfTruthCutover(base());assert.equal(normalized.lineage[0]?.executionSucceeded,true);assert.equal(normalized.lineage[0]?.acknowledgedAt,"2026-09-10T13:01:00Z");assert.equal(normalized.lineage[0]?.adoption,"PARTIAL");assert.equal(normalized.lineage[0]?.convergence,"PARTIAL");assert.equal(normalized.lineage[0]?.sourceSchemaRevision.revisionRef,"r1");assert.equal(normalized.lineage[0]?.targetSchemaRevision.revisionRef,"r2");});

test("TASK-508 rejects ACK to convergence strengthening and failed-execution promotion",()=>{const drained=allResiduals().map((entry)=>({...entry,populationCount:0,completeness:"KNOWN",drained:true}));assert.throws(()=>normalizeSourceOfTruthCutover({...base(),lineage:[lineage({adoption:"PENDING",convergence:"CONVERGED"})],residualCohorts:drained}),/acknowledgement cannot imply convergence/);assert.throws(()=>normalizeSourceOfTruthCutover({...base(),lineage:[lineage({executionSucceeded:false,adoption:"ADOPTED"})]}),/failed execution/);});

test("TASK-508 rejects hidden residual cohort classes",()=>{for(const kind of ["SOURCE","READER","WRITER","REPLICATION"] as const){assert.throws(()=>normalizeSourceOfTruthCutover({...base(),residualCohorts:allResiduals().filter((entry)=>entry.cohortKind!==kind)}),new RegExp(`residual cohort class ${kind} must remain explicit`));}});

test("TASK-508 keeps UNKNOWN residuals visible and blocks false convergence",()=>{const normalized=normalizeSourceOfTruthCutover(base());assert.equal(normalized.residualCohorts.length,4);assert.equal(normalized.residualCohorts[0]?.populationCount,"UNKNOWN");assert.throws(()=>normalizeSourceOfTruthCutover({...base(),lineage:[lineage({acknowledgedAt:null,adoption:"ADOPTED",convergence:"CONVERGED"})]}),/drainage/);assert.throws(()=>normalizeSourceOfTruthCutover({...base(),residualCohorts:[residual("SOURCE",{populationCount:0,completeness:"UNKNOWN"}),residual("READER"),residual("WRITER"),residual("REPLICATION")]}),/preserve populationCount as UNKNOWN/);});

test("TASK-508 rejects stale or mismatched currentness as drained/converged evidence",()=>{const drained=(state:"CURRENT"|"STALE"="CURRENT",validUntil="2026-09-10T14:00:00Z")=>allResiduals().map((entry)=>({...entry,populationCount:0,completeness:"KNOWN",drained:true,currentness:currentness(cutoverRev(),"tenant-a/customer","region-a",state,validUntil)}));assert.throws(()=>normalizeSourceOfTruthCutover({...base(),residualCohorts:drained("STALE")}),/CURRENT evidence/);assert.throws(()=>normalizeSourceOfTruthCutover({...base(),residualCohorts:drained("CURRENT","2026-09-10T13:01:00Z")}),/currentness horizon/);assert.throws(()=>normalizeSourceOfTruthCutover({...base(),residualCohorts:[residual("SOURCE",{currentness:currentness(cutoverRev(),"other-scope")}),residual("READER"),residual("WRITER"),residual("REPLICATION")]}),/population scope/);assert.throws(()=>normalizeSourceOfTruthCutover({...base(),residualCohorts:[residual("SOURCE",{currentness:currentness(cutoverRev(),"tenant-a/customer","other-region")}),residual("READER"),residual("WRITER"),residual("REPLICATION")]}),/locality scope/);});

test("TASK-508 allows convergence only with explicit current known-zero drainage",()=>{const drained=["SOURCE","READER","WRITER","REPLICATION"].map((kind)=>residual(kind as "SOURCE"|"READER"|"WRITER"|"REPLICATION",{populationCount:0,completeness:"KNOWN",drained:true}));const normalized=normalizeSourceOfTruthCutover({...base(),lineage:[lineage({acknowledgedAt:null,adoption:"ADOPTED",convergence:"CONVERGED"})],residualCohorts:drained});assert.equal(normalized.lineage[0]?.convergence,"CONVERGED");});
