import assert from "node:assert/strict";
import test from "node:test";
import { EKB_QUESTION_SEMANTIC_KIND, ELICITATION_KNOWLEDGE_BASE_CONTRACT_VERSION, SEMANTIC_SUBSTRATE_CONTRACT_VERSION, normalizeQuestionDefinitionRevision, normalizeQuestionOccurrence } from "../../packages/contracts/elicitation-knowledge-base/index.js";
import { normalizeEKBCapabilityLensRoute } from "../../packages/contracts/elicitation-knowledge-base/capability-lens-routing.js";

const owner = "capability:elicitation";
const definition = normalizeQuestionDefinitionRevision({ contractVersion: ELICITATION_KNOWLEDGE_BASE_CONTRACT_VERSION, ref: { contractVersion: SEMANTIC_SUBSTRATE_CONTRACT_VERSION, semanticOwner: owner, semanticKind: EKB_QUESTION_SEMANTIC_KIND, canonicalRef: "question:maintenance-window", definitionRef: "question:maintenance-window@definition", revisionOwner: owner, revisionDimension: "wording", revisionRef: "r1" }, text: "Which maintenance windows are unavailable?" });
const occurrence = normalizeQuestionOccurrence({ contractVersion: ELICITATION_KNOWLEDGE_BASE_CONTRACT_VERSION, ref: { occurrence: { contractVersion: SEMANTIC_SUBSTRATE_CONTRACT_VERSION, semanticOwner: owner, semanticKind: EKB_QUESTION_SEMANTIC_KIND, canonicalRef: "question:maintenance-window", occurrenceRef: "occurrence:station-a:maintenance-window:1" }, producingDefinitionRevision: definition.ref }, definitionRevision: definition.ref, context: { contextRef: "workshop:station-a", populationScope: "population:station-a", localityScope: "locality:station-a" } });
const producingLensRevision = { lensRef: "lens:maintenance", revisionRef: "lens:maintenance:r1" } as const;
const base = () => ({ contractVersion: ELICITATION_KNOWLEDGE_BASE_CONTRACT_VERSION, identity: { routeRef: "lens-route:maintenance:1", producingLensRevision }, routeRef: "lens-route:maintenance:1", sourceFollowUpRef: "follow-up:maintenance-window:1", producingLensRevision, sourceOccurrence: occurrence.ref, sourceContext: occurrence.context, targetOwners: [{ ownerRef: "capability:maintenance", authorityRef: "semantic-owner:maintenance" }], outcome: "ROUTED", rationale: "Explicit capability routing evidence identifies one external owner." } as const);

test("TASK-480 preserves predecessor follow-up, producing lens revision, occurrence lineage, locality and external owner identity", () => { const route = normalizeEKBCapabilityLensRoute(base()); assert.equal(route.sourceFollowUpRef, "follow-up:maintenance-window:1"); assert.equal(route.identity.routeRef, route.routeRef); assert.equal(route.identity.producingLensRevision.revisionRef, "lens:maintenance:r1"); assert.equal(route.producingLensRevision.revisionRef, "lens:maintenance:r1"); assert.equal(route.sourceOccurrence.occurrence.occurrenceRef, occurrence.ref.occurrence.occurrenceRef); assert.equal(route.sourceOccurrence.producingDefinitionRevision.revisionRef, "r1"); assert.equal(route.sourceContext.populationScope, "population:station-a"); assert.equal(route.sourceContext.localityScope, "locality:station-a"); assert.equal(route.targetOwners[0]?.ownerRef, "capability:maintenance"); });
test("TASK-480 preserves ambiguous multi-owner routing without choosing a winner", () => { const route = normalizeEKBCapabilityLensRoute({ ...base(), outcome: "MULTI_CANDIDATE", targetOwners: [{ ownerRef: "capability:maintenance", authorityRef: "semantic-owner:maintenance" }, { ownerRef: "capability:scheduling", authorityRef: "semantic-owner:scheduling" }] }); assert.equal(route.outcome, "MULTI_CANDIDATE"); assert.equal(route.targetOwners.length, 2); assert.throws(() => normalizeEKBCapabilityLensRoute({ ...base(), outcome: "MULTI_CANDIDATE" }), /multiple explicit/); });
test("TASK-480 pins historical routing to its producing lens revision instead of rewriting it to the current lens", () => { const historicalRoute = normalizeEKBCapabilityLensRoute(base()); const currentLens = { lensRef: "lens:maintenance", revisionRef: "lens:maintenance:r2" } as const; assert.equal(historicalRoute.identity.producingLensRevision.revisionRef, "lens:maintenance:r1"); assert.notEqual(historicalRoute.identity.producingLensRevision.revisionRef, currentLens.revisionRef); assert.throws(() => normalizeEKBCapabilityLensRoute({ ...base(), producingLensRevision: currentLens }), /revision pinned by the historical route identity/); assert.throws(() => normalizeEKBCapabilityLensRoute({ ...base(), identity: { routeRef: base().routeRef, producingLensRevision: currentLens } }), /revision pinned by the historical route identity/); assert.throws(() => normalizeEKBCapabilityLensRoute({ ...base(), routeRef: "lens-route:maintenance:rewritten" }), /historical route identity/); });
test("TASK-480 rejects owner cloning and heuristic winner fields", () => { assert.throws(() => normalizeEKBCapabilityLensRoute({ ...base(), semanticPredicate: "maintenance.window" }), /unexpected field semanticPredicate/); assert.throws(() => normalizeEKBCapabilityLensRoute({ ...base(), confidence: 0.99 }), /unexpected field confidence/); assert.throws(() => normalizeEKBCapabilityLensRoute({ ...base(), firstMatchWins: true }), /unexpected field firstMatchWins/); assert.throws(() => normalizeEKBCapabilityLensRoute({ ...base(), featureNameEquivalent: true }), /unexpected field featureNameEquivalent/); });
test("TASK-480 fails closed and cannot strengthen Fleet/global routing into Station/local truth", () => { const inconclusive = normalizeEKBCapabilityLensRoute({ ...base(), outcome: "INCONCLUSIVE", targetOwners: [], rationale: "No explicit semantic-owner candidate is authoritative for this local occurrence." }); assert.equal(inconclusive.targetOwners.length, 0); assert.throws(() => normalizeEKBCapabilityLensRoute({ ...base(), sourceContext: { ...occurrence.context, localityScope: "locality:fleet" }, stationTruth: "locality:station-a" }), /unexpected field stationTruth/); assert.throws(() => normalizeEKBCapabilityLensRoute({ ...base(), outcome: "INCONCLUSIVE" }), /must not choose or fabricate/); });
