import assert from "node:assert/strict";
import test from "node:test";
import { GOVERNANCE_CONTRACT_VERSION, assessGovernance, normalizeGovernanceDecision, normalizeGovernanceEnforcement, normalizeGovernanceEvidence, normalizeGovernancePolicy, normalizeGovernanceWaiver, policyAuthorityState, selectCurrentPolicy, waiverAuthorityState } from "../../packages/contracts/governance/index.js";
import { assessPrivacyDisposition, normalizePrivacyPopulation } from "../../packages/contracts/governance/privacy.js";

const now="2026-09-18T12:00:00Z";
const policy=normalizeGovernancePolicy({contractVersion:GOVERNANCE_CONTRACT_VERSION,policyId:"policy:retention",revisionRef:"rev:1",effectiveAt:now,scopeRef:"scope:tenant-a"});
const decision=normalizeGovernanceDecision({decisionId:"decision:1",policyRef:policy.policyId,policyRevisionRef:policy.revisionRef,basisRefs:["evidence:1"],inferenceRef:"ai:recommendation:1"});
const enforcement=normalizeGovernanceEnforcement({enforcementId:"enforcement:1",decisionRef:decision.decisionId,observedAt:now,result:"APPLIED"});
const complete=normalizeGovernanceEvidence({evidenceId:"evidence:1",provenanceRef:"provenance:1",currentness:"CURRENT",population:"COMPLETE",observedAt:now});

test("TASK-563 keeps policy decision enforcement evidence and assessment distinct",()=>{ assert.notEqual(policy.policyId,decision.decisionId); assert.notEqual(decision.decisionId,enforcement.enforcementId); assert.equal(decision.inferenceRef,"ai:recommendation:1"); assert.equal(decision.authorityRef,undefined); assert.equal(assessGovernance({assessmentId:"assessment:1",policyRef:policy.policyId,evidence:[complete],assertionSatisfied:true,assessedAt:now}).outcome,"SATISFIED"); });
test("missing stale partial or unknown evidence cannot strengthen compliance truth",()=>{ assert.equal(assessGovernance({assessmentId:"a:missing",policyRef:policy.policyId,evidence:[],assertionSatisfied:true,assessedAt:now}).outcome,"INDETERMINATE"); for(const [currentness,population] of [["STALE","COMPLETE"],["UNKNOWN","COMPLETE"],["CURRENT","PARTIAL"],["CURRENT","UNKNOWN"]] as const){ const evidence=normalizeGovernanceEvidence({evidenceId:`evidence:${currentness}:${population}`,provenanceRef:"provenance:bounded",currentness,population,observedAt:now}); assert.equal(assessGovernance({assessmentId:`a:${currentness}:${population}`,policyRef:policy.policyId,evidence:[evidence],assertionSatisfied:true,assessedAt:now}).outcome,"INDETERMINATE"); } });
test("complete current evidence can support negative assessment without becoming authority",()=>{ assert.equal(assessGovernance({assessmentId:"assessment:negative",policyRef:policy.policyId,evidence:[complete],assertionSatisfied:false,assessedAt:now}).outcome,"NOT_SATISFIED"); assert.equal(Object.hasOwn(complete,"authorityRef"),false); });
test("TASK-564 resolves effective-dated policy supersession deterministically",()=>{ const rev1=normalizeGovernancePolicy({contractVersion:GOVERNANCE_CONTRACT_VERSION,policyId:"policy:access",revisionRef:"rev:1",effectiveAt:"2026-01-01T00:00:00Z",scopeRef:"scope:a"}); const rev2=normalizeGovernancePolicy({contractVersion:GOVERNANCE_CONTRACT_VERSION,policyId:"policy:access",revisionRef:"rev:2",effectiveAt:"2026-06-01T00:00:00Z",supersedesRevisionRef:"rev:1",scopeRef:"scope:a"}); const selected=selectCurrentPolicy([rev1,rev2],"policy:access","scope:a",now); assert.equal(selected.state,"CURRENT"); assert.equal(selected.policy?.revisionRef,"rev:2"); const competing=normalizeGovernancePolicy({contractVersion:GOVERNANCE_CONTRACT_VERSION,policyId:"policy:access",revisionRef:"rev:parallel",effectiveAt:"2026-07-01T00:00:00Z",scopeRef:"scope:a"}); assert.equal(selectCurrentPolicy([rev1,rev2,competing],"policy:access","scope:a",now).state,"CONFLICTED"); });
test("waiver authority is issuer scope revision time expiry and revocation bounded",()=>{ const governed=normalizeGovernancePolicy({contractVersion:GOVERNANCE_CONTRACT_VERSION,policyId:"policy:retention",revisionRef:"rev:2",effectiveAt:"2026-01-01T00:00:00Z",scopeRef:"scope:tenant-a"}); const waiver=normalizeGovernanceWaiver({waiverId:"waiver:1",policyRef:governed.policyId,policyRevisionRef:governed.revisionRef,issuerAuthorityRef:"authority:privacy-officer",scopeRef:governed.scopeRef,rationaleRef:"case:123",effectiveAt:"2026-09-01T00:00:00Z",expiresAt:"2026-10-01T00:00:00Z"}); assert.equal(waiverAuthorityState(waiver,governed,now),"CURRENT"); assert.equal(waiverAuthorityState(waiver,governed,"2026-10-01T00:00:00Z"),"EXPIRED"); const stalePolicy=normalizeGovernancePolicy({contractVersion:GOVERNANCE_CONTRACT_VERSION,policyId:governed.policyId,revisionRef:"rev:3",effectiveAt:"2026-09-10T00:00:00Z",scopeRef:governed.scopeRef}); assert.equal(waiverAuthorityState(waiver,stalePolicy,now),"STALE"); const revoked=normalizeGovernanceWaiver({...waiver,revokedAt:"2026-09-15T00:00:00Z"}); assert.equal(waiverAuthorityState(revoked,governed,now),"REVOKED"); });
test("acknowledgement evidence or AI inference cannot create waiver authority",()=>{ assert.equal(Object.hasOwn(complete,"issuerAuthorityRef"),false); assert.equal(decision.inferenceRef,"ai:recommendation:1"); assert.equal(decision.authorityRef,undefined); assert.equal(policyAuthorityState(policy,now),"CURRENT"); });

const populationBase={populationId:"population:orders",policyRef:"policy:privacy",policyRevisionRef:"rev:7",classification:"RESTRICTED",sourceProviderRef:"provider:legacy",currentProviderRef:"provider:new",sourceRef:"source:orders",residencyRefs:["region:br"],retainedUntil:"2026-09-01T00:00:00Z",legalHoldRefs:[],inventoryCoverage:"COMPLETE",migrationCoverage:"COMPLETE",residualPopulationRefs:[]} as const;
test("TASK-565 qualifies disposition by policy revision population retention and residency",()=>{ const population=normalizePrivacyPopulation(populationBase); const result=assessPrivacyDisposition(population,now,"region:br"); assert.equal(result.state,"ELIGIBLE"); assert.equal(result.policyRevisionRef,"rev:7"); });
test("legal hold has precedence over otherwise eligible disposition",()=>{ const population=normalizePrivacyPopulation({...populationBase,legalHoldRefs:["hold:case-9"]}); const result=assessPrivacyDisposition(population,now,"region:br"); assert.equal(result.state,"BLOCKED"); assert.deepEqual(result.reasons,["LEGAL_HOLD"]); });
test("active retention blocks disposition",()=>{ const population=normalizePrivacyPopulation({...populationBase,retainedUntil:"2027-09-01T00:00:00Z"}); assert.equal(assessPrivacyDisposition(population,now,"region:br").state,"BLOCKED"); });
test("provider migration preserves source lineage and residual populations remain indeterminate",()=>{ const population=normalizePrivacyPopulation({...populationBase,migrationCoverage:"PARTIAL",residualPopulationRefs:["population:orders:legacy"]}); assert.equal(population.sourceProviderRef,"provider:legacy"); assert.equal(population.currentProviderRef,"provider:new"); const result=assessPrivacyDisposition(population,now,"region:br"); assert.equal(result.state,"INDETERMINATE"); assert.deepEqual(result.residualPopulationRefs,["population:orders:legacy"]); });
test("unknown or partial inventory cannot strengthen into disposition eligibility",()=>{ for(const inventoryCoverage of ["PARTIAL","UNKNOWN"] as const){ const population=normalizePrivacyPopulation({...populationBase,inventoryCoverage}); assert.equal(assessPrivacyDisposition(population,now,"region:br").state,"INDETERMINATE"); } });
test("unknown or violated residency cannot strengthen disposition",()=>{ const population=normalizePrivacyPopulation(populationBase); assert.equal(assessPrivacyDisposition(population,now).state,"INDETERMINATE"); assert.equal(assessPrivacyDisposition(population,now,"region:us").state,"INDETERMINATE"); });
