import assert from "node:assert/strict";
import test from "node:test";
import { IDENTITY_AUTHORIZATION_CONTRACT_VERSION, normalizeAuthorizationDecision, normalizeAuthorizationRequest } from "../../packages/contracts/identity-authorization/index.js";
import { DERIVED_AUTHORITY_CONTRACT_VERSION, normalizeDerivedAuthorityDescriptor } from "../../packages/contracts/identity-authorization/delegation.js";
import { REVOCATION_CONVERGENCE_CONTRACT_VERSION, normalizeRevocationConvergence } from "../../packages/contracts/identity-authorization/revocation.js";
import { SEMANTIC_SUBSTRATE_CONTRACT_VERSION } from "../../packages/contracts/semantic-substrate/index.js";
const rev=(c:string,r:string,k="identity-evidence")=>({contractVersion:SEMANTIC_SUBSTRATE_CONTRACT_VERSION,semanticOwner:"identity-domain",semanticKind:k,canonicalRef:c,definitionRef:`${c}-definition`,revisionOwner:"identity-domain",revisionDimension:"definition",revisionRef:r});
const locality={scopeKind:"STATION" as const,localityRef:"station-a"};
const curr=(subject:ReturnType<typeof rev>,state:"CURRENT"|"STALE"|"UNKNOWN"="CURRENT")=>({contractVersion:SEMANTIC_SUBSTRATE_CONTRACT_VERSION,subject,revisionVector:[{revisionOwner:"identity-domain",revisionDimension:"definition",revisionRef:subject.revisionRef}],temporal:{occurredAt:null,observedAt:"2026-09-09T20:15:00Z",evaluatedAt:null,effectiveFrom:null,effectiveUntil:null,reconciledAt:"2026-09-09T20:16:00Z"},populationScope:"operator",localityScope:"station-a",currentnessHorizon:{assessedAt:"2026-09-09T20:15:00Z",validUntil:"2026-09-09T21:15:00Z"},state,reason:"integrated authority proof"});
const identity=rev("operator-42","identity-r3","identity"),delegate=rev("operator-77","identity-r2","identity"),authEvidence=rev("auth-evidence","auth-r7"),policy=rev("maintenance-policy","policy-r4","authority-policy"),authzEvidence=rev("maintenance-evidence","evidence-r9","authorization-evidence"),derivedEvidence=rev("delegation-ticket","ticket-r2","delegation-evidence"),revokeEvidence=rev("revocation-ticket","ticket-r9","revocation-evidence"),reconcileEvidence=rev("revocation-reconciliation","reconcile-r5","convergence-evidence"),sessionEvidence=rev("session-scan","scan-r2","residual-evidence"),tokenEvidence=rev("token-scan","scan-r3","residual-evidence"),cacheEvidence=rev("cache-scan","scan-r4","residual-evidence"),offlineEvidence=rev("offline-scan","scan-r5","residual-evidence");
const actor={contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,identity:{contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,identity},authentication:{contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,subjectIdentity:identity,evidence:authEvidence,currentness:curr(authEvidence),locality,state:"AUTHENTICATED" as const}};
const request=normalizeAuthorizationRequest({contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,actor,authorityPolicy:policy,policyCurrentness:curr(policy),authorizationEvidence:{contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,evidence:authzEvidence,currentness:curr(authzEvidence),locality,state:"SUFFICIENT"},requested:{action:"work-order.update",resource:"work-order:42",scope:"maintenance",locality}});
const allow=normalizeAuthorizationDecision({contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,request,disposition:"ALLOW"},request);
const descriptor={contractVersion:DERIVED_AUTHORITY_CONTRACT_VERSION,mode:"DELEGATION" as const,sourceDecision:allow,delegator:actor,delegate:{contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,identity:delegate},sourceWindow:{notBefore:"2026-09-09T19:00:00Z",expiresAt:"2026-09-09T21:00:00Z"},effectiveWindow:{notBefore:"2026-09-09T19:30:00Z",expiresAt:"2026-09-09T20:30:00Z"},effectiveScope:request.requested,reason:"bounded maintenance handoff",evidence:derivedEvidence};
const intent={contractVersion:REVOCATION_CONVERGENCE_CONTRACT_VERSION,identity:{contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,identity},authorityRevision:policy,desiredState:"REVOKED" as const,evidence:revokeEvidence,currentness:curr(revokeEvidence),locality};
const residuals=[
 {kind:"SESSION" as const,populationCount:1,evidence:sessionEvidence,currentness:curr(sessionEvidence),locality},
 {kind:"TOKEN" as const,populationCount:2,evidence:tokenEvidence,currentness:curr(tokenEvidence),locality},
 {kind:"CACHE" as const,populationCount:"UNKNOWN" as const,evidence:cacheEvidence,currentness:curr(cacheEvidence),locality},
 {kind:"OFFLINE" as const,populationCount:1,evidence:offlineEvidence,currentness:curr(offlineEvidence),locality},
];
const convergence={contractVersion:REVOCATION_CONVERGENCE_CONTRACT_VERSION,intent,observedAuthorityRevision:policy,observedState:"REVOKED" as const,acknowledged:true,status:"PARTIAL" as const,convergenceEvidence:reconcileEvidence,convergenceCurrentness:curr(reconcileEvidence),residualCohorts:residuals};
test("TASK-499 proves exact integrated identity authorization delegation and revocation lineage",()=>{const derived=normalizeDerivedAuthorityDescriptor(descriptor,allow);const converged=normalizeRevocationConvergence(convergence,policy);assert.equal(derived.sourceDecision.request.actor.identity.identity.revisionRef,"identity-r3");assert.equal(derived.sourceDecision.request.authorityPolicy.revisionRef,"policy-r4");assert.equal(derived.effectiveScope.locality.localityRef,"station-a");assert.equal(converged.status,"PARTIAL");assert.deepEqual(converged.residualCohorts.map((cohort)=>cohort.kind),["SESSION","TOKEN","CACHE","OFFLINE"]);assert.equal(converged.residualCohorts[2]?.populationCount,"UNKNOWN");});
test("TASK-499 rejects authenticated-to-allowed promotion plus identity and policy revision substitution",()=>{const weak=normalizeAuthorizationRequest({...request,authorizationEvidence:{...request.authorizationEvidence,state:"UNKNOWN"}});assert.throws(()=>normalizeAuthorizationDecision({contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,request:weak,disposition:"ALLOW"},weak),/cannot produce ALLOW/);const substitutedPolicy=rev("maintenance-policy","policy-r5","authority-policy");assert.throws(()=>normalizeDerivedAuthorityDescriptor({...descriptor,sourceDecision:{...allow,request:{...request,authorityPolicy:substitutedPolicy,policyCurrentness:curr(substitutedPolicy)}}},allow),/exact expected actor\/policy\/scope envelope/);const substitutedIdentity=rev("operator-42","identity-r4","identity");assert.throws(()=>normalizeAuthorizationRequest({...request,actor:{...actor,identity:{contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,identity:substitutedIdentity}}}),/identity/);});
test("TASK-499 rejects delegation expansion and break-glass evidence or expiry removal",()=>{assert.throws(()=>normalizeDerivedAuthorityDescriptor({...descriptor,effectiveScope:{...request.requested,scope:"fleet"}},allow),/scope\/locality/);const noReason={...descriptor,mode:"BREAK_GLASS" as const,reason:""};assert.throws(()=>normalizeDerivedAuthorityDescriptor(noReason,allow),/reason/);const noEvidence={...descriptor,mode:"BREAK_GLASS" as const} as Record<string,unknown>;delete noEvidence.evidence;assert.throws(()=>normalizeDerivedAuthorityDescriptor(noEvidence,allow),/missing field evidence/);const noExpiry={...descriptor,effectiveWindow:{notBefore:descriptor.effectiveWindow.notBefore}};assert.throws(()=>normalizeDerivedAuthorityDescriptor(noExpiry,allow),/missing field expiresAt/);});
test("TASK-499 rejects false convergence hidden residuals ack promotion and stale authority resurrection",()=>{assert.throws(()=>normalizeRevocationConvergence({...convergence,status:"CONVERGED"},policy),/drained/);const hidden={...convergence} as Record<string,unknown>;delete hidden.residualCohorts;assert.throws(()=>normalizeRevocationConvergence(hidden,policy),/missing field residualCohorts/);assert.throws(()=>normalizeRevocationConvergence({...convergence,intent:{...intent,currentness:curr(revokeEvidence,"UNKNOWN")},status:"CONVERGED",residualCohorts:[]},policy),/cannot become fully converged/);const ackOnly={...convergence,residualCohorts:[],status:"PARTIAL" as const};assert.equal(normalizeRevocationConvergence(ackOnly,policy).status,"PARTIAL");const stale=rev("maintenance-policy","policy-r3","authority-policy");assert.throws(()=>normalizeRevocationConvergence({...convergence,observedAuthorityRevision:stale},policy),/cannot substitute or resurrect/);});
