import assert from "node:assert/strict";
import test from "node:test";
import { SEMANTIC_SUBSTRATE_CONTRACT_VERSION } from "../../packages/contracts/semantic-substrate/index.js";
import { PROVIDER_QUALIFICATION_CONTRACT_VERSION } from "../../packages/contracts/provider/qualification.js";
import { PHYSICAL_PERIPHERAL_GOVERNANCE_CONTRACT_VERSION, normalizePhysicalPeripheralInteraction, normalizePhysicalPeripheralQualification } from "../../packages/contracts/physical/governance.js";

const rev=(canonicalRef:string,revisionRef:string,semanticKind:string)=>({contractVersion:SEMANTIC_SUBSTRATE_CONTRACT_VERSION,semanticOwner:"physical-owner",semanticKind,canonicalRef,definitionRef:`${canonicalRef}-definition`,revisionOwner:"physical-owner",revisionDimension:"definition",revisionRef});
const peripheral=rev("peripheral/gate-a","peripheral-r2","physical-peripheral");
const providerBinding=rev("provider/gate-a","binding-r4","provider-binding");
const providerEvidence=rev("provider/gate-a/evidence","evidence-r9","provider-qualification-evidence");
const currentness=(subject:ReturnType<typeof rev>,localityScope:string,state:"CURRENT"|"STALE"|"UNKNOWN"="CURRENT")=>({contractVersion:SEMANTIC_SUBSTRATE_CONTRACT_VERSION,subject,revisionVector:[{revisionOwner:subject.revisionOwner,revisionDimension:subject.revisionDimension,revisionRef:subject.revisionRef}],temporal:{occurredAt:null,observedAt:"2026-09-11T00:00:00Z",evaluatedAt:null,effectiveFrom:null,effectiveUntil:null,reconciledAt:"2026-09-11T00:01:00Z"},populationScope:"physical/peripheral",localityScope,currentnessHorizon:{assessedAt:"2026-09-11T00:00:00Z",validUntil:"2026-09-11T01:00:00Z"},state,reason:"TASK-514 product proof"});
const provider=(disposition:"SUPPORTED"|"PARTIAL"|"UNSUPPORTED"|"UNKNOWN"|"INCONCLUSIVE"="SUPPORTED",localityScope="station-alpha")=>({contractVersion:PROVIDER_QUALIFICATION_CONTRACT_VERSION,binding:providerBinding,providerRealizationRef:"vendor/gate-a/42",evidence:providerEvidence,currentness:currentness(providerEvidence,localityScope),evidenceAuthority:"AUTHORITATIVE" as const,dimensions:[{dimension:"transport",status:disposition,reason:"qualified transport"}],disposition});
const qualification=(overrides:Record<string,unknown>={})=>({contractVersion:PHYSICAL_PERIPHERAL_GOVERNANCE_CONTRACT_VERSION,peripheral,providerQualification:provider(),localityRef:"station-alpha",currentness:currentness(peripheral,"station-alpha"),capability:"SUPPORTED" as const,...overrides});
const actuation=(overrides:Record<string,unknown>={})=>({contractVersion:PHYSICAL_PERIPHERAL_GOVERNANCE_CONTRACT_VERSION,qualification:qualification(),intentKind:"ACTUATE" as const,requestedIntentRef:"intent/open-gate",owningDomainAuthorityRef:"access-control/authorization/77",authorization:"AUTHORIZED" as const,observedTelemetry:"PRESENT" as const,effect:"CONFIRMED" as const,...overrides});

test("TASK-514 keeps qualification provider revision currentness and locality aware",()=>{const normalized=normalizePhysicalPeripheralQualification(qualification());assert.equal(normalized.capability,"SUPPORTED");assert.equal(normalized.localityRef,"station-alpha");assert.equal(normalized.providerQualification.binding.revisionRef,"binding-r4");});
test("TASK-514 rejects provider or physical uncertainty strengthening",()=>{assert.throws(()=>normalizePhysicalPeripheralQualification(qualification({providerQualification:provider("UNKNOWN")})),/cannot strengthen/);assert.throws(()=>normalizePhysicalPeripheralQualification(qualification({currentness:currentness(peripheral,"station-alpha","UNKNOWN")})),/cannot strengthen/);});
test("TASK-514 rejects provider qualification from another locality",()=>{assert.throws(()=>normalizePhysicalPeripheralQualification(qualification({providerQualification:provider("SUPPORTED","station-beta")})),/locality must match/);});
test("TASK-514 rejects connected capability as generic actuation authority",()=>{assert.throws(()=>normalizePhysicalPeripheralInteraction(actuation({owningDomainAuthorityRef:null})),/requires external owning-domain authority/);assert.throws(()=>normalizePhysicalPeripheralInteraction(actuation({authorization:"UNKNOWN"})),/does not grant actuation authority/);});
test("TASK-514 keeps observation distinct from requested actuation and effect",()=>{const observed=normalizePhysicalPeripheralInteraction({...actuation(),intentKind:"OBSERVE",owningDomainAuthorityRef:null,authorization:"NOT_REQUIRED",effect:"NOT_APPLICABLE"});assert.equal(observed.intentKind,"OBSERVE");assert.equal(observed.effect,"NOT_APPLICABLE");});
test("TASK-514 rejects command accepted style claims without confirmed effect evidence",()=>{const pending=normalizePhysicalPeripheralInteraction(actuation({observedTelemetry:"PRESENT",effect:"NOT_CONFIRMED"}));assert.equal(pending.effect,"NOT_CONFIRMED");assert.throws(()=>normalizePhysicalPeripheralInteraction(actuation({observedTelemetry:"MISSING",effect:"CONFIRMED"})),/cannot imply confirmed physical effect/);});
test("TASK-514 does not treat missing telemetry as safe or absent",()=>{const observed=normalizePhysicalPeripheralInteraction({...actuation(),intentKind:"OBSERVE",owningDomainAuthorityRef:null,authorization:"NOT_REQUIRED",observedTelemetry:"MISSING",effect:"NOT_APPLICABLE"});assert.equal(observed.observedTelemetry,"MISSING");});
