import assert from "node:assert/strict";
import test from "node:test";
import { normalizeDegradedAuthorityCeiling, normalizeFencingObservation, normalizeRecoveryEffect, normalizeRecoveryRequalification, normalizeResidualRecoveryCohort } from "../../packages/contracts/identity-authorization/recovery.js";

const rev=(revisionRef:string,canonicalRef="authority/policy-a",semanticKind="recovery")=>({contractVersion:"1.0.0",semanticOwner:"g2-wp04",semanticKind,canonicalRef,definitionRef:canonicalRef,revisionOwner:"g2-wp04",revisionDimension:"revision",revisionRef});
const locality={scopeKind:"STATION",localityRef:"station-a"} as const;
const currentness=(subject:ReturnType<typeof rev>,state:"CURRENT"|"STALE"|"UNKNOWN"="CURRENT")=>({contractVersion:"1.0.0",subject,revisionVector:[],temporal:{occurredAt:null,observedAt:"2026-09-10T04:10:00Z",evaluatedAt:null,effectiveFrom:null,effectiveUntil:null,reconciledAt:null},populationScope:"station-a",localityScope:"station-a",currentnessHorizon:{assessedAt:"2026-09-10T04:10:00Z",validUntil:"2026-09-10T05:10:00Z"},state,reason:"TASK-503 product proof"});
const authority=rev("auth-r2");const cutSource=rev("cut-r1","recovery/source-cut");const cutEvidence=rev("cut-e1","evidence/recovery-cut");const actor=rev("actor-r2","identity/actor-a","identity");const epoch=rev("epoch-2","fencing/domain-a","fencing");const oldEpoch=rev("epoch-1","fencing/domain-a","fencing");const fenceEvidence=rev("fence-e1","evidence/fencing");const verifyEvidence=rev("verify-e1","evidence/recovery-verification");
const trust=rev("trust-g2","trust/domain-a","trust");const config=rev("config-g2","config/domain-a","config");
const ceiling={contractVersion:"1.0.0",authorityPolicy:authority,policyCurrentness:currentness(authority),allowedScopes:["read:local"],prohibitedScopes:["write:fleet"],locality,validUntil:"2026-09-10T05:00:00Z",reviewCondition:"connectivity-restored"};
const cut={contractVersion:"1.0.0",sourceRevision:cutSource,cutEvidence,currentness:currentness(cutEvidence),locality};
const fencing={contractVersion:"1.0.0",actor,epoch,supersedesEpoch:oldEpoch,oldActorQuiescence:"UNKNOWN",evidence:fenceEvidence,currentness:currentness(fenceEvidence),locality};
const effectEvidence=rev("effect-e1","evidence/effect");const effect={contractVersion:"1.0.0",effectRef:"dispatch-42",knowledge:"KNOWN",duplicateSafety:"PROVEN",retryDisposition:"SAFE_RETRY",evidence:effectEvidence,currentness:currentness(effectEvidence),locality};
const cohortEvidence=rev("cohort-e1","evidence/cohort");const cohort={contractVersion:"1.0.0",cohortRef:"old-recovery-path",generation:oldEpoch,disposition:"DRAINED",evidence:cohortEvidence,currentness:currentness(cohortEvidence),locality};
const verified={contractVersion:"1.0.0",ceiling,cut,fencing,restoredAuthority:authority,currentAuthority:authority,restoredTrust:trust,currentTrust:trust,restoredConfig:config,currentConfig:config,postCutRevocations:[],postCutRotations:[],postCutConfigRevisions:[],effects:[effect],residualCohorts:[cohort],evidence:verifyEvidence,currentness:currentness(verifyEvidence),locality,state:"VERIFIED"};

test("TASK-503 keeps degraded authority bounded and recovery verification explicit",()=>{const normalized=normalizeRecoveryRequalification(verified);assert.equal(normalized.state,"VERIFIED");assert.deepEqual(normalizeDegradedAuthorityCeiling(ceiling).allowedScopes,["read:local"]);assert.equal(normalizeFencingObservation(fencing,epoch).oldActorQuiescence,"UNKNOWN");});

test("TASK-503 rejects failover authority/locality expansion and superseded epoch reuse",()=>{assert.throws(()=>normalizeDegradedAuthorityCeiling({...ceiling,allowedScopes:["write:fleet"],prohibitedScopes:["write:fleet"]}));assert.throws(()=>normalizeRecoveryRequalification({...verified,locality:{scopeKind:"FLEET",localityRef:"station-a"}}));assert.throws(()=>normalizeFencingObservation({...fencing,epoch:oldEpoch,supersedesEpoch:null},epoch));});

test("TASK-503 rejects stale restored authority trust and config resurrection",()=>{assert.throws(()=>normalizeRecoveryRequalification({...verified,restoredAuthority:rev("auth-r1")}));assert.throws(()=>normalizeRecoveryRequalification({...verified,restoredTrust:rev("trust-g1","trust/domain-a","trust")}));assert.throws(()=>normalizeRecoveryRequalification({...verified,restoredConfig:rev("config-g1","config/domain-a","config")}));});

test("TASK-503 keeps restore acknowledgement distinct from verified recovery",()=>{assert.throws(()=>normalizeRecoveryRequalification({...verified,currentness:currentness(verifyEvidence,"UNKNOWN")}));assert.throws(()=>normalizeRecoveryRequalification({...verified,postCutRevocations:[rev("revocation-r3","authority/revocations")]}));assert.equal(normalizeRecoveryRequalification({...verified,state:"PARTIAL",postCutRotations:[rev("trust-g3","trust/domain-a","trust")]}).state,"PARTIAL");});

test("TASK-503 routes UNKNOWN external effects to reconcile-before-retry unless duplicate-safe",()=>{const unknown={...effect,knowledge:"UNKNOWN",duplicateSafety:"UNKNOWN",retryDisposition:"RECONCILE_BEFORE_RETRY"};assert.equal(normalizeRecoveryEffect(unknown).retryDisposition,"RECONCILE_BEFORE_RETRY");assert.throws(()=>normalizeRecoveryEffect({...unknown,retryDisposition:"SAFE_RETRY"}));assert.equal(normalizeRecoveryEffect({...unknown,duplicateSafety:"PROVEN",retryDisposition:"SAFE_RETRY"}).retryDisposition,"SAFE_RETRY");});

test("TASK-503 keeps residual old paths visible until current drained evidence",()=>{assert.equal(normalizeResidualRecoveryCohort(cohort).disposition,"DRAINED");assert.throws(()=>normalizeRecoveryRequalification({...verified,residualCohorts:[{...cohort,disposition:"ACTIVE"}]}));assert.throws(()=>normalizeResidualRecoveryCohort({...cohort,currentness:currentness(cohortEvidence,"STALE")}));});
