import assert from "node:assert/strict";
import test from "node:test";
import { IDENTITY_AUTHORIZATION_CONTRACT_VERSION, normalizeAuthorizationDecision, normalizeAuthorizationRequest } from "../../packages/contracts/identity-authorization/index.js";
import { normalizeDegradedAuthorityCeiling, normalizeExternalEffectAssessment, normalizeFencingObservation, normalizeRecoveryCut, normalizeRecoveryVerification, normalizeResidualRecoveryCohort, RECOVERY_CONTRACT_VERSION, type ResidualRecoveryKind } from "../../packages/contracts/identity-authorization/recovery.js";
import { SEMANTIC_SUBSTRATE_CONTRACT_VERSION } from "../../packages/contracts/semantic-substrate/index.js";

const revision=(canonicalRef:string,revisionRef:string,kind="recovery-evidence")=>({contractVersion:SEMANTIC_SUBSTRATE_CONTRACT_VERSION,semanticOwner:"g2-wp04",semanticKind:kind,canonicalRef,definitionRef:`${canonicalRef}-definition`,revisionOwner:"g2-wp04",revisionDimension:"definition",revisionRef});
const locality={scopeKind:"STATION" as const,localityRef:"station-a"};
const currentness=(subject:ReturnType<typeof revision>,state:"CURRENT"|"STALE"|"UNKNOWN"="CURRENT")=>({contractVersion:SEMANTIC_SUBSTRATE_CONTRACT_VERSION,subject,revisionVector:[],temporal:{occurredAt:null,observedAt:"2026-09-10T03:30:00Z",evaluatedAt:null,effectiveFrom:null,effectiveUntil:null,reconciledAt:null},populationScope:"station-a",localityScope:"station-a",currentnessHorizon:{assessedAt:"2026-09-10T03:30:00Z",validUntil:"2026-09-10T04:30:00Z"},state,reason:"TASK-503 product proof"});
const identity=revision("operator-42","identity-r3","identity");const authEvidence=revision("auth-evidence","auth-r7");const policy=revision("maintenance-policy","policy-r4","authority-policy");const decisionEvidence=revision("authorization-evidence","evidence-r9");
const actor={contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,identity:{contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,identity},authentication:{contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,subjectIdentity:identity,evidence:authEvidence,currentness:currentness(authEvidence),locality,state:"AUTHENTICATED" as const}};
const request=normalizeAuthorizationRequest({contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,actor,authorityPolicy:policy,policyCurrentness:currentness(policy),authorizationEvidence:{contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,evidence:decisionEvidence,currentness:currentness(decisionEvidence),locality,state:"SUFFICIENT"},requested:{action:"work-order.update",resource:"work-order:42",scope:"maintenance",locality}});
const allow=normalizeAuthorizationDecision({contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,request,disposition:"ALLOW"},request);
const horizonEvidence=revision("degraded-horizon","horizon-r1");const ceiling={contractVersion:RECOVERY_CONTRACT_VERSION,sourceDecision:allow,allowedScope:"maintenance",prohibitedScopes:["fleet-admin"],locality,horizonEvidence,currentness:currentness(horizonEvidence),expiresAt:"2026-09-10T04:00:00Z",reviewCondition:"revalidate authority and trust before extension"};
const authorityCurrent=revision("maintenance-policy","policy-r4","authority-policy");const trustCurrent=revision("trust-domain","trust-r8","trust-generation");const configCurrent=revision("secret-config","config-r9","config-generation");const cutRef=revision("recovery-cut","cut-r2");
const cut={contractVersion:RECOVERY_CONTRACT_VERSION,sourceCut:cutRef,restoredAuthority:authorityCurrent,currentAuthority:authorityCurrent,restoredTrust:trustCurrent,currentTrust:trustCurrent,restoredConfig:configCurrent,currentConfig:configCurrent,postCutRevocations:[revision("revocation-log","rev-r10")],postCutRotations:[revision("rotation-log","rotation-r11")],postCutConfigRevisions:[revision("config-log","config-r12")],restoreState:"RESTORED" as const,locality};
const actorEpoch=revision("fencing-epoch","epoch-r4","fencing");const oldEpoch=revision("fencing-epoch","epoch-r3","fencing");const fenceEvidence=revision("fencing-evidence","fence-r5");const fencing={contractVersion:RECOVERY_CONTRACT_VERSION,actor:identity,epoch:actorEpoch,supersededEpoch:oldEpoch,oldActorState:"QUIESCED" as const,evidence:fenceEvidence,currentness:currentness(fenceEvidence),locality};
const effect={contractVersion:RECOVERY_CONTRACT_VERSION,effectRef:"external-effect-42",outcome:"UNKNOWN" as const,retryDisposition:"RECONCILE_BEFORE_RETRY" as const,duplicateSafetyEvidence:null,currentness:null,locality};
const residualEvidence=revision("residual-recovery","residual-r1");const residual=(kind:ResidualRecoveryKind)=>({contractVersion:RECOVERY_CONTRACT_VERSION,cohortRef:`${kind.toLowerCase()}-old`,kind,generation:oldEpoch,populationKnowledge:"KNOWN" as const,population:0,disposition:"DRAINED" as const,evidence:residualEvidence,currentness:currentness(residualEvidence),locality});
const residualCohorts=[residual("OLD_ACTOR"),residual("TRUST"),residual("CONFIG"),residual("CACHE"),residual("OFFLINE"),residual("RECOVERY_PATH")];const reprotectionEvidence=revision("reprotection-evidence","protect-r6");const verification={contractVersion:RECOVERY_CONTRACT_VERSION,ceiling,cut,fencing,effect,residualCohorts,reprotectionEvidence,currentness:currentness(reprotectionEvidence),locality,state:"VERIFIED" as const};

test("TASK-503 keeps degraded authority bounded and recovery verification explicit",()=>{assert.equal(normalizeDegradedAuthorityCeiling(ceiling).allowedScope,"maintenance");assert.equal(normalizeRecoveryCut(cut).restoreState,"RESTORED");assert.equal(normalizeFencingObservation(fencing).oldActorState,"QUIESCED");assert.equal(normalizeRecoveryVerification(verification).state,"VERIFIED");});
test("TASK-503 rejects failover scope or locality authority substitution",()=>{assert.throws(()=>normalizeDegradedAuthorityCeiling({...ceiling,allowedScope:"fleet"}),/cannot expand or substitute/);assert.throws(()=>normalizeDegradedAuthorityCeiling({...ceiling,locality:{scopeKind:"FLEET",localityRef:"fleet-a"}}),/locality/);const unknown=normalizeAuthorizationDecision({contractVersion:IDENTITY_AUTHORIZATION_CONTRACT_VERSION,request,disposition:"UNKNOWN"},request);assert.throws(()=>normalizeDegradedAuthorityCeiling({...ceiling,sourceDecision:unknown}),/cannot mint authority/);});
test("TASK-503 rejects stale or over-horizon degraded authority",()=>{assert.throws(()=>normalizeDegradedAuthorityCeiling({...ceiling,currentness:currentness(horizonEvidence,"STALE")}),/requires CURRENT horizon evidence/);assert.throws(()=>normalizeDegradedAuthorityCeiling({...ceiling,currentness:currentness(horizonEvidence,"UNKNOWN")}),/requires CURRENT horizon evidence/);assert.throws(()=>normalizeDegradedAuthorityCeiling({...ceiling,expiresAt:"2026-09-10T05:00:00Z"}),/within the proven currentness horizon/);assert.throws(()=>normalizeDegradedAuthorityCeiling({...ceiling,expiresAt:"not-a-timestamp"}),/valid timestamp/);});
test("TASK-503 rejects stale restored authority trust or config resurrection",()=>{const staleAuthority=revision("maintenance-policy","policy-r3","authority-policy");const staleTrust=revision("trust-domain","trust-r7","trust-generation");const staleConfig=revision("secret-config","config-r8","config-generation");for(const patch of [{restoredAuthority:staleAuthority},{restoredTrust:staleTrust},{restoredConfig:staleConfig}]) assert.throws(()=>normalizeRecoveryVerification({...verification,cut:{...cut,...patch}}),/cannot promote stale/);});
test("TASK-503 rejects recovery ACK promotion and superseded fencing reuse",()=>{assert.throws(()=>normalizeRecoveryVerification({...verification,fencing:{...fencing,oldActorState:"UNKNOWN"}}),/old-actor quiescence/);assert.throws(()=>normalizeFencingObservation({...fencing,epoch:oldEpoch,supersededEpoch:oldEpoch}),/cannot be reused/);assert.throws(()=>normalizeRecoveryVerification({...verification,currentness:currentness(reprotectionEvidence,"UNKNOWN")}),/current evidence/);});
test("TASK-503 keeps ambiguous external effects reconcile-before-retry",()=>{assert.equal(normalizeExternalEffectAssessment(effect).retryDisposition,"RECONCILE_BEFORE_RETRY");assert.throws(()=>normalizeExternalEffectAssessment({...effect,retryDisposition:"SAFE_TO_RETRY"}),/reconcile-before-retry/);const duplicateEvidence=revision("duplicate-safety","dup-r1");assert.equal(normalizeExternalEffectAssessment({...effect,retryDisposition:"SAFE_TO_RETRY",duplicateSafetyEvidence:duplicateEvidence,currentness:currentness(duplicateEvidence)}).retryDisposition,"SAFE_TO_RETRY");});
test("TASK-503 rejects hidden, zero-defaulted or non-drained residual recovery cohorts",()=>{assert.throws(()=>normalizeRecoveryVerification({...verification,residualCohorts:residualCohorts.slice(0,-1)}),/hidden residuals/);assert.throws(()=>normalizeResidualRecoveryCohort({...residual("CACHE"),populationKnowledge:"UNKNOWN",population:0,disposition:"UNKNOWN"}),/never zero-defaulted/);assert.throws(()=>normalizeRecoveryVerification({...verification,residualCohorts:residualCohorts.map(c=>c.kind==="OFFLINE"?{...c,population:1,disposition:"ACTIVE" as const}:c)}),/explicitly drained/);assert.throws(()=>normalizeResidualRecoveryCohort({...residual("RECOVERY_PATH"),currentness:currentness(residualEvidence,"STALE")}),/CURRENT known zero/);});
