import assert from "node:assert/strict";
import test from "node:test";
import { normalizeAdoptionObservation, normalizeResidualCohort, normalizeRotationAcknowledgement, normalizeRotationConvergence, normalizeRotationIntent } from "../../packages/contracts/identity-authorization/rotation-drainage.js";

const rev=(revisionRef:string, canonicalRef="trust/domain-a")=>({contractVersion:"1.0.0",semanticOwner:"g2-wp04",semanticKind:"rotation",canonicalRef,definitionRef:"domain-a",revisionOwner:"g2-wp04",revisionDimension:"generation",revisionRef});
const locality={scopeKind:"STATION",localityRef:"station-a"} as const;
const currentness=(subject:ReturnType<typeof rev>,state:"CURRENT"|"STALE"|"UNKNOWN"="CURRENT")=>({contractVersion:"1.0.0",subject,revisionVector:[],temporal:{occurredAt:null,observedAt:"2026-09-10T02:40:00Z",evaluatedAt:null,effectiveFrom:null,effectiveUntil:null,reconciledAt:null},populationScope:"fleet-a",localityScope:"station-a",currentnessHorizon:{assessedAt:"2026-09-10T02:40:00Z",validUntil:"2026-09-10T03:40:00Z"},state,reason:"TASK-502 product proof"});
const oldGeneration=rev("g1");const newGeneration=rev("g2");const ackEvidence=rev("ack-e1","evidence/ack");const adoptionEvidence=rev("adopt-e1","evidence/adoption");const residualEvidence=rev("residual-e1","evidence/residual");const convergenceEvidence=rev("convergence-e1","evidence/convergence");
const intent={contractVersion:"1.0.0",domain:"TRUST",oldGeneration,newGeneration,providerVersionRef:"provider-v2",populationRef:"verifier-set-a",populationKnowledge:"KNOWN",eligiblePopulation:10,locality};
const ack={contractVersion:"1.0.0",intent,providerVersionRef:"provider-v2",evidence:ackEvidence,currentness:currentness(ackEvidence),locality};
const adoption={contractVersion:"1.0.0",intent,populationRef:"verifier-set-a",generation:newGeneration,populationKnowledge:"KNOWN",observedPopulation:10,adoptedPopulation:10,disposition:"ADOPTED",evidence:adoptionEvidence,currentness:currentness(adoptionEvidence),locality};
const residual=(kind:"VERIFIER"|"CONSUMER"|"CACHE"|"OFFLINE"|"RECOVERY")=>({contractVersion:"1.0.0",intent,cohortId:`${kind.toLowerCase()}-old`,kind,generation:oldGeneration,populationKnowledge:"KNOWN",population:0,disposition:"DRAINED",evidence:residualEvidence,currentness:currentness(residualEvidence),locality});

test("TASK-502 keeps request, provider ACK, adoption and convergence distinct",()=>{assert.equal(normalizeRotationIntent(intent).newGeneration.revisionRef,"g2");assert.equal(normalizeRotationAcknowledgement(ack).providerVersionRef,"provider-v2");assert.equal(normalizeAdoptionObservation(adoption).disposition,"ADOPTED");const result=normalizeRotationConvergence({contractVersion:"1.0.0",intent,acknowledgement:ack,adoption,residualCohorts:[residual("VERIFIER"),residual("CONSUMER"),residual("CACHE"),residual("OFFLINE"),residual("RECOVERY")],evidence:convergenceEvidence,currentness:currentness(convergenceEvidence),locality,state:"CONVERGED"});assert.equal(result.state,"CONVERGED");});

test("TASK-502 permits explicit old/new coexistence but rejects wrong-generation adoption",()=>{const partial={...adoption,observedPopulation:10,adoptedPopulation:6,disposition:"PARTIAL"};assert.equal(normalizeAdoptionObservation(partial).disposition,"PARTIAL");assert.throws(()=>normalizeAdoptionObservation({...partial,generation:oldGeneration}));});

test("TASK-502 rejects ACK=>convergence, hidden residuals and unknown population=>zero",()=>{assert.throws(()=>normalizeRotationConvergence({contractVersion:"1.0.0",intent,acknowledgement:ack,adoption,residualCohorts:[],evidence:convergenceEvidence,currentness:currentness(convergenceEvidence),locality,state:"CONVERGED"}));const unknownIntent={...intent,populationKnowledge:"UNKNOWN",eligiblePopulation:null};assert.equal(normalizeRotationIntent(unknownIntent).eligiblePopulation,null);assert.throws(()=>normalizeRotationIntent({...unknownIntent,eligiblePopulation:0}));assert.throws(()=>normalizeRotationConvergence({contractVersion:"1.0.0",intent:unknownIntent,acknowledgement:{...ack,intent:unknownIntent},adoption:{...adoption,intent:unknownIntent,populationKnowledge:"UNKNOWN",observedPopulation:null,adoptedPopulation:null,disposition:"UNKNOWN"},residualCohorts:[{...residual("VERIFIER"),intent:unknownIntent,populationKnowledge:"UNKNOWN",population:null,disposition:"UNKNOWN"}],evidence:convergenceEvidence,currentness:currentness(convergenceEvidence),locality,state:"CONVERGED"}));});

test("TASK-502 rejects locality strengthening, provider substitution and stale evidence",()=>{assert.throws(()=>normalizeRotationAcknowledgement({...ack,providerVersionRef:"provider-v3"}));assert.throws(()=>normalizeRotationAcknowledgement({...ack,locality:{scopeKind:"FLEET",localityRef:"station-a"}}));assert.throws(()=>normalizeAdoptionObservation({...adoption,currentness:currentness(adoptionEvidence,"STALE")}));assert.throws(()=>normalizeResidualCohort({...residual("CACHE"),disposition:"DRAINED",currentness:currentness(residualEvidence,"UNKNOWN")}));});

test("TASK-502 rejects stale-generation resurrection and non-drained authoritative residuals",()=>{assert.throws(()=>normalizeResidualCohort({...residual("RECOVERY"),generation:newGeneration}));assert.throws(()=>normalizeRotationConvergence({contractVersion:"1.0.0",intent,acknowledgement:ack,adoption,residualCohorts:[{...residual("OFFLINE"),population:1,disposition:"AUTHORITATIVE"}],evidence:convergenceEvidence,currentness:currentness(convergenceEvidence),locality,state:"CONVERGED"}));});
