import assert from "node:assert/strict";
import test from "node:test";

import { BUTTON_GROUP_DESCRIPTOR, BUTTON_GROUP_SLOT_IDS, COMPONENT_FAMILIES, ComponentRegistry, admitCompositionContract, defineCompositionGraph, normalizeComponentDescriptor, resolveInspectorFields, validateCompositionGraph, validateCompositionPlacement } from "../../packages/station-composition/index.js";

const atomic = { id: "component:button", family: "atomic", layout: "none", childPolicy: "none", constraints: { minColumns: 1, maxColumns: 4, recommendedColumns: 2, minRows: 1, maxRows: 2, recommendedRows: 1 }, slots: [] } as const;
const layout = { id: "component:grid", family: "layout-container", layout: "grid", layoutOwnership: "self", childPolicy: "multiple", constraints: { minColumns: 1, maxColumns: 12, recommendedColumns: 12, minRows: 1, maxRows: 12, recommendedRows: 4 }, slots: [{ id: "content", childPolicy: "multiple", acceptsFamilies: [...COMPONENT_FAMILIES] }] } as const;

test("component registry is stable-id based and deterministically ordered", () => { const registry = new ComponentRegistry([layout, atomic]); assert.deepEqual(registry.list().map((item) => item.id), ["component:button", "component:grid"]); assert.equal(registry.get("component:grid")?.family, "layout-container"); });
test("component registry rejects duplicate stable ids deterministically", () => { const registry = new ComponentRegistry([atomic]); assert.throws(() => registry.register(atomic), /duplicate component descriptor id/); });
test("composition contracts represent all four component families", () => { const registry = new ComponentRegistry(COMPONENT_FAMILIES.map((family, index) => ({ ...atomic, id: `component:${family}:${index}`, family }))); assert.deepEqual(new Set(registry.list().map((item) => item.family)), new Set(COMPONENT_FAMILIES)); });
test("descriptor validation requires canonical composition fields and discrete spans", () => { assert.throws(() => normalizeComponentDescriptor({ ...atomic, id: "" }), /component descriptor id must be a non-empty string/); assert.throws(() => normalizeComponentDescriptor({ ...atomic, constraints: { ...atomic.constraints, recommendedColumns: 5 } }), /column span constraints/); assert.throws(() => normalizeComponentDescriptor({ ...atomic, family: "app" }), /component family is unsupported/); });
test("named slots reject duplicate identity and preserve family compatibility metadata", () => { const descriptor = normalizeComponentDescriptor(layout); assert.equal(descriptor.slots[0]?.id, "content"); assert.deepEqual(descriptor.slots[0]?.acceptsFamilies, COMPONENT_FAMILIES); assert.throws(() => normalizeComponentDescriptor({ ...layout, slots: [layout.slots[0], layout.slots[0]] }), /duplicate slot id/); });
test("placement accepts only discrete spans inside child constraints", () => { const parent = normalizeComponentDescriptor(layout); const child = normalizeComponentDescriptor(atomic); assert.doesNotThrow(() => validateCompositionPlacement({ parent, child, slotId: "content", columnSpan: 2, rowSpan: 1 })); assert.throws(() => validateCompositionPlacement({ parent, child, slotId: "content", columnSpan: 5, rowSpan: 1 }), /columnSpan is outside/); assert.throws(() => validateCompositionPlacement({ parent, child, slotId: "content", columnSpan: 2.5, rowSpan: 1 }), /columnSpan is outside/); });
test("named slots enforce family, layout and allowed-parent compatibility", () => { const parent = normalizeComponentDescriptor({ ...layout, slots: [{ ...layout.slots[0], acceptsFamilies: ["atomic"], acceptsLayouts: ["none"] }] }); const child = normalizeComponentDescriptor({ ...atomic, allowedParentFamilies: ["layout-container"] }); assert.doesNotThrow(() => validateCompositionPlacement({ parent, child, slotId: "content", columnSpan: 2, rowSpan: 1 })); const collection = normalizeComponentDescriptor({ ...atomic, id: "component:list", family: "collection" }); assert.throws(() => validateCompositionPlacement({ parent, child: collection, slotId: "content", columnSpan: 2, rowSpan: 1 }), /rejects child family/); });
test("nested layout ownership is explicit and independent of window geometry", () => { const parent = normalizeComponentDescriptor(layout); const nested = normalizeComponentDescriptor({ ...layout, id: "component:nested-grid", allowedParentFamilies: ["layout-container"] }); assert.doesNotThrow(() => validateCompositionPlacement({ parent, child: nested, slotId: "content", columnSpan: 6, rowSpan: 4 })); const unowned = normalizeComponentDescriptor({ ...nested, id: "component:unowned-grid", layoutOwnership: undefined }); assert.throws(() => validateCompositionPlacement({ parent, child: unowned, slotId: "content", columnSpan: 6, rowSpan: 4 }), /nested layout must explicitly own/); assert.equal("width" in nested.constraints, false); assert.equal("height" in nested.constraints, false); });
test("ButtonGroup owns five deterministic atomic button slots without pixel geometry", () => { const group = normalizeComponentDescriptor(BUTTON_GROUP_DESCRIPTOR); assert.equal(group.family, "semantic-composite"); assert.equal(group.layoutOwnership, "self"); assert.deepEqual(group.slots.map((slot) => slot.id), BUTTON_GROUP_SLOT_IDS); assert.equal("width" in group.constraints, false); assert.equal("height" in group.constraints, false); const button = normalizeComponentDescriptor(atomic); for (const slotId of BUTTON_GROUP_SLOT_IDS) assert.doesNotThrow(() => validateCompositionPlacement({ parent: group, child: button, slotId, columnSpan: 2, rowSpan: 1 })); });
test("ButtonGroup rejects non-atomic children", () => { const group = normalizeComponentDescriptor(BUTTON_GROUP_DESCRIPTOR); const invalid = normalizeComponentDescriptor({ ...atomic, id: "component:button-collection", family: "collection" }); assert.throws(() => validateCompositionPlacement({ parent: group, child: invalid, slotId: "button-1", columnSpan: 2, rowSpan: 1 }), /rejects child family/); });
test("composition graph keeps semantic refs, named slots and discrete spans without normalizing malformed structure", () => { const graph = defineCompositionGraph({ rootRef: "node:root", nodes: [{ ref: "node:root", componentRef: "component:grid" }, { ref: "node:button", componentRef: "component:button", placement: { parentRef: "node:root", slotRef: "content", columnSpan: 2, rowSpan: 1 } }, { ref: "node:button", componentRef: "component:missing", placement: { parentRef: "node:missing", slotRef: "unknown-slot", columnSpan: 99, rowSpan: 1 } }] }); assert.equal(graph.rootRef, "node:root"); assert.equal(graph.nodes[1]?.placement?.slotRef, "content"); assert.equal(graph.nodes[1]?.placement?.columnSpan, 2); assert.equal(graph.nodes[2]?.ref, "node:button"); assert.equal(graph.nodes[2]?.placement?.parentRef, "node:missing"); assert.equal("width" in (graph.nodes[1]?.placement ?? {}), false); });
test("composition graph validator accepts a valid graph without mutation", () => { const registry = new ComponentRegistry([layout, atomic]); const graph = defineCompositionGraph({ rootRef: "node:root", nodes: [{ ref: "node:root", componentRef: "component:grid" }, { ref: "node:button", componentRef: "component:button", placement: { parentRef: "node:root", slotRef: "content", columnSpan: 2, rowSpan: 1 } }] }); assert.deepEqual(validateCompositionGraph(graph, registry), []); assert.equal(graph.nodes[1]?.placement?.columnSpan, 2); });
test("composition graph validator reports deterministic structural and placement findings", () => { const registry = new ComponentRegistry([layout, atomic]); const graph = defineCompositionGraph({ rootRef: "node:root", nodes: [{ ref: "node:root", componentRef: "component:grid" }, { ref: "node:dup", componentRef: "component:button", placement: { parentRef: "node:root", slotRef: "missing", columnSpan: 99, rowSpan: 1 } }, { ref: "node:dup", componentRef: "component:missing", placement: { parentRef: "node:gone", slotRef: "content", columnSpan: 1, rowSpan: 1 } }, { ref: "node:orphan", componentRef: "component:button" }] }); const findings = validateCompositionGraph(graph, registry); assert.deepEqual(findings.map((item) => item.code), ["duplicate-node-ref", "invalid-placement", "unknown-component-ref", "dangling-parent-ref"]); assert.match(findings[1]?.message ?? "", /unknown parent slot|columnSpan/); });

const admissionSchema = { componentRef: "component:button", variants: ["default", "quiet"], inspectorFields: [{ id: "variant", label: "Variant" }, { id: "columnSpan", label: "Columns" }] } as const;
const validAdmission = { parentRef: "component:grid", componentRef: "component:button", slotId: "content", columnSpan: 2, rowSpan: 1, variant: "default", inspectorFieldIds: ["variant", "columnSpan"] } as const;

test("C01 admits a declared component slot variant and schema tuple deterministically", () => { const registry = new ComponentRegistry([layout, atomic]); const first = admitCompositionContract(registry, admissionSchema, validAdmission); const second = admitCompositionContract(registry, admissionSchema, validAdmission); assert.deepEqual(first, second); assert.equal(first.component.id, "component:button"); assert.equal(first.variant, "default"); assert.deepEqual(first.inspectorFields.map((field) => field.id), ["variant", "columnSpan"]); });
test("C01 rejects unknown component slot variant and schema field before any caller mutation", () => { const registry = new ComponentRegistry([layout, atomic]); const draft = { revision: 7, selectedRef: "node:button" }; const before = structuredClone(draft); assert.throws(() => admitCompositionContract(registry, admissionSchema, { ...validAdmission, componentRef: "component:missing" }), /does not describe component|unknown admission component/); assert.throws(() => admitCompositionContract(registry, admissionSchema, { ...validAdmission, slotId: "missing" }), /unknown parent slot/); assert.throws(() => admitCompositionContract(registry, admissionSchema, { ...validAdmission, variant: "approve-document" }), /unsupported admission variant/); assert.throws(() => admitCompositionContract(registry, admissionSchema, { ...validAdmission, inspectorFieldIds: ["businessStatus"] }), /unknown inspector schema field/); assert.deepEqual(draft, before); });
test("C01 preserves existing family layout and discrete span compatibility at the admission boundary", () => { const registry = new ComponentRegistry([layout, atomic]); assert.throws(() => admitCompositionContract(registry, admissionSchema, { ...validAdmission, columnSpan: 9 }), /columnSpan is outside/); const rejectingParent = { ...layout, id: "component:rejecting-grid", slots: [{ ...layout.slots[0], acceptsFamilies: ["collection"] }] } as const; const rejectingRegistry = new ComponentRegistry([rejectingParent, atomic]); assert.throws(() => admitCompositionContract(rejectingRegistry, admissionSchema, { ...validAdmission, parentRef: "component:rejecting-grid" }), /rejects child family/); });
test("C01 Inspector field availability is schema-driven and action semantics are absent from presentation variants", () => { assert.deepEqual(resolveInspectorFields(admissionSchema, ["variant"]).map((field) => field.id), ["variant"]); assert.deepEqual(resolveInspectorFields(admissionSchema, ["columnSpan"]).map((field) => field.id), ["columnSpan"]); assert.equal(admissionSchema.variants.some((variant) => /approve|deploy|cancel/i.test(variant)), false); });
test("C01 stable component identity is independent from placement span and presentation variant", () => { const registry = new ComponentRegistry([layout, atomic]); const a = admitCompositionContract(registry, admissionSchema, validAdmission); const b = admitCompositionContract(registry, admissionSchema, { ...validAdmission, columnSpan: 3, variant: "quiet" }); assert.equal(a.component.id, b.component.id); assert.notEqual(a.columnSpan, b.columnSpan); assert.notEqual(a.variant, b.variant); });