export function renderRuntimeFileExecutionSupport(): string {
  return [
    "function runtimeResolveFileBinding(environment, bindingRef) { const binding = Array.isArray(environment && environment.bindings) ? environment.bindings.find((candidate) => candidate && candidate.name === bindingRef) : undefined; if (!binding || binding.kind !== \"config\" || binding.requirementKind !== \"storage\" || typeof binding.reference !== \"string\" || !binding.reference.startsWith(\"env://\")) return { ok: false, code: \"RUNTIME_FILE_BINDING_INVALID\", detail: bindingRef }; const variable = binding.reference.slice(6).trim(); if (!variable) return { ok: false, code: \"RUNTIME_FILE_BINDING_INVALID\", detail: bindingRef }; const value = process.env[variable]; if (typeof value !== \"string\" || value.length === 0) return { ok: false, code: \"RUNTIME_FILE_BINDING_UNRESOLVED\", detail: bindingRef }; return { ok: true, value }; }",
    "function runtimeFileRoute(url) { const pathname = String(url || \"\").split(\"?\", 1)[0]; const match = pathname.match(/^\\/files\\/([^/]+)\\/(.+)$/); if (!match) return undefined; try { return { fileId: decodeURIComponent(match[1]), key: decodeURIComponent(match[2]) }; } catch { return undefined; } }",
    "function runtimeReadRawBody(request) { return new Promise((resolve, reject) => { let body = \"\"; request.setEncoding(\"utf8\"); request.on(\"data\", (chunk) => { body += chunk; if (body.length > 1048576) reject(new Error(\"RUNTIME_REQUEST_BODY_TOO_LARGE\")); }); request.on(\"end\", () => resolve(body)); request.on(\"error\", reject); }); }",
    "async function runtimeHandleFileRequest(request, response, model, environment) { const route = runtimeFileRoute(request.url); if (!route) return false; const descriptor = Array.isArray(model.files) ? model.files.find((candidate) => candidate.id === route.fileId) : undefined; if (!descriptor) { runtimeWriteJson(response, 404, { kind: \"RuntimeDiagnostic\", code: \"RUNTIME_FILE_UNKNOWN\", detail: route.fileId }); return true; } const operation = request.method === \"PUT\" ? \"put\" : request.method === \"GET\" ? \"get\" : request.method === \"DELETE\" ? \"delete\" : undefined; if (!operation) { runtimeWriteJson(response, 405, { kind: \"RuntimeDiagnostic\", code: \"RUNTIME_FILE_METHOD_NOT_ALLOWED\", detail: String(request.method || \"\") }); return true; } if (!descriptor.operations.includes(operation)) { runtimeWriteJson(response, 405, { kind: \"RuntimeDiagnostic\", code: \"RUNTIME_FILE_OPERATION_NOT_DECLARED\", detail: descriptor.id + \":\" + operation }); return true; } const resolved = runtimeResolveFileBinding(environment, descriptor.bindingRef); if (!resolved.ok) { runtimeWriteJson(response, 503, { kind: \"RuntimeDiagnostic\", code: resolved.code, detail: resolved.detail }); return true; } try { const path = await import(\"node:path\"); const fs = await import(\"node:fs/promises\"); const root = path.resolve(resolved.value); const target = path.resolve(root, route.key); const relative = path.relative(root, target); if (!relative || path.isAbsolute(relative) || relative === \"..\" || relative.startsWith(\"../\") || relative.startsWith(\"..\\\\\")) { runtimeWriteJson(response, 400, { kind: \"RuntimeDiagnostic\", code: \"RUNTIME_FILE_PATH_INVALID\", detail: descriptor.id + \":\" + route.key }); return true; } if (operation === \"put\") { const body = await runtimeReadRawBody(request); await fs.mkdir(path.dirname(target), { recursive: true }); await fs.writeFile(target, body, \"utf8\"); runtimeWriteJson(response, 200, { kind: \"RuntimeFile\", fileId: descriptor.id, key: route.key, operation }); return true; } if (operation === \"get\") { const content = await fs.readFile(target, \"utf8\"); runtimeWriteJson(response, 200, { kind: \"RuntimeFile\", fileId: descriptor.id, key: route.key, operation, content }); return true; } await fs.rm(target, { force: true }); runtimeWriteJson(response, 200, { kind: \"RuntimeFile\", fileId: descriptor.id, key: route.key, operation }); return true; } catch (error) { const code = error && typeof error === \"object\" && \"code\" in error && error.code === \"ENOENT\" ? \"RUNTIME_FILE_NOT_FOUND\" : \"RUNTIME_FILE_STORAGE_FAILED\"; runtimeWriteJson(response, code === \"RUNTIME_FILE_NOT_FOUND\" ? 404 : 503, { kind: \"RuntimeDiagnostic\", code, detail: descriptor.id + \":\" + route.key }); return true; } }",
  ].join("\n");
}

export const runtimeFileExecutionRoute = "              if (typeof runtimeModel !== \"undefined\" && runtimeModel && await runtimeHandleFileRequest(request, response, runtimeModel, environment)) return;";
