export function renderRuntimeIntegrationExecutionSupport(): string {
  return [
    "function runtimeResolveIntegrationBinding(environment, bindingRef) { const binding = Array.isArray(environment && environment.bindings) ? environment.bindings.find((candidate) => candidate && candidate.name === bindingRef) : undefined; if (!binding || binding.kind !== \"config\" || binding.requirementKind !== \"external-service\" || typeof binding.reference !== \"string\" || !binding.reference.startsWith(\"env://\")) return { ok: false, code: \"RUNTIME_INTEGRATION_BINDING_INVALID\", detail: bindingRef }; const variable = binding.reference.slice(6).trim(); if (!variable) return { ok: false, code: \"RUNTIME_INTEGRATION_BINDING_INVALID\", detail: bindingRef }; const value = process.env[variable]; if (typeof value !== \"string\" || value.length === 0) return { ok: false, code: \"RUNTIME_INTEGRATION_BINDING_UNRESOLVED\", detail: bindingRef }; return { ok: true, value }; }",
    "function runtimeIntegrationRoute(url) { const pathname = String(url || \"\").split(\"?\", 1)[0]; const match = pathname.match(/^\\/integrations\\/([^/]+)$/); if (!match) return undefined; try { return { integrationId: decodeURIComponent(match[1]) }; } catch { return undefined; } }",
    "async function runtimeHandleIntegrationRequest(request, response, model, environment) { const route = runtimeIntegrationRoute(request.url); if (!route) return false; if (request.method !== \"POST\") { runtimeWriteJson(response, 405, { kind: \"RuntimeDiagnostic\", code: \"RUNTIME_INTEGRATION_METHOD_NOT_ALLOWED\", detail: String(request.method || \"\") }); return true; } const descriptor = Array.isArray(model.integrations) ? model.integrations.find((candidate) => candidate.id === route.integrationId) : undefined; if (!descriptor || !descriptor.invocation || descriptor.invocation.kind !== \"http\") { runtimeWriteJson(response, 404, { kind: \"RuntimeDiagnostic\", code: \"RUNTIME_INTEGRATION_UNKNOWN\", detail: route.integrationId }); return true; } const resolved = runtimeResolveIntegrationBinding(environment, descriptor.invocation.bindingRef); if (!resolved.ok) { runtimeWriteJson(response, 503, { kind: \"RuntimeDiagnostic\", code: resolved.code, detail: resolved.detail }); return true; } try { let base; try { base = new URL(resolved.value); } catch { runtimeWriteJson(response, 503, { kind: \"RuntimeDiagnostic\", code: \"RUNTIME_INTEGRATION_BINDING_INVALID\", detail: descriptor.invocation.bindingRef }); return true; } if (base.protocol !== \"http:\" && base.protocol !== \"https:\") { runtimeWriteJson(response, 503, { kind: \"RuntimeDiagnostic\", code: \"RUNTIME_INTEGRATION_BINDING_INVALID\", detail: descriptor.invocation.bindingRef }); return true; } const target = new URL(descriptor.invocation.path, base); const body = await runtimeReadJsonBody(request); const method = descriptor.invocation.method; const init = { method, headers: { \"content-type\": \"application/json\" } }; if (method !== \"GET\" && method !== \"DELETE\") init.body = JSON.stringify(body); const upstream = await fetch(target, init); const text = await upstream.text(); let payload = text; try { payload = text.length === 0 ? null : JSON.parse(text); } catch {} runtimeWriteJson(response, upstream.ok ? 200 : 502, { kind: \"RuntimeIntegration\", integrationId: descriptor.id, status: upstream.status, response: payload }); return true; } catch { runtimeWriteJson(response, 503, { kind: \"RuntimeDiagnostic\", code: \"RUNTIME_INTEGRATION_INVOCATION_FAILED\", detail: descriptor.id }); return true; } }",
  ].join("\n");
}

export const runtimeIntegrationExecutionRoute = "              if (typeof runtimeModel !== \"undefined\" && runtimeModel && await runtimeHandleIntegrationRequest(request, response, runtimeModel, environment)) return;";
