export type RuntimePostgresStateExecutionRequirement = Readonly<{
  capability: string;
  storeKind: "sql";
  connectionBinding: Readonly<{ name: string; kind: "secret-reference" }>;
}>;

export function renderPostgresRuntimeStateSupport(
  requirements: readonly RuntimePostgresStateExecutionRequirement[],
): string {
  if (requirements.length === 0) return "";

  return [
    'import { createConnection as createPostgresConnection } from "node:net";',
    "function postgresStateConfig(connectionString) {",
    "  let url;",
    "  try { url = new URL(connectionString); } catch { throw new Error(\"POSTGRES_URL_INVALID\"); }",
    "  if (url.protocol !== \"postgres:\" && url.protocol !== \"postgresql:\") throw new Error(\"POSTGRES_URL_INVALID\");",
    "  const user = decodeURIComponent(url.username || \"\");",
    "  const pathname = url.pathname.startsWith(\"/\") ? url.pathname.slice(1) : url.pathname;",
    "  const database = decodeURIComponent(pathname);",
    "  if (!url.hostname || !user || !database) throw new Error(\"POSTGRES_URL_INVALID\");",
    "  const port = url.port ? Number(url.port) : 5432;",
    "  if (!Number.isInteger(port) || port <= 0 || port > 65535) throw new Error(\"POSTGRES_URL_INVALID\");",
    "  return { host: url.hostname, port, user, database };",
    "}",
    "function postgresCString(value) { return Buffer.from(String(value) + \"\\0\", \"utf8\"); }",
    "function postgresStartup(config) {",
    "  const fields = Buffer.concat([postgresCString(\"user\"), postgresCString(config.user), postgresCString(\"database\"), postgresCString(config.database), postgresCString(\"client_encoding\"), postgresCString(\"UTF8\"), Buffer.from([0])]);",
    "  const message = Buffer.allocUnsafe(8 + fields.length);",
    "  message.writeInt32BE(message.length, 0);",
    "  message.writeInt32BE(196608, 4);",
    "  fields.copy(message, 8);",
    "  return message;",
    "}",
    "function postgresQueryMessage(sql) {",
    "  const text = Buffer.from(sql + \"\\0\", \"utf8\");",
    "  const message = Buffer.allocUnsafe(5 + text.length);",
    "  message[0] = 81;",
    "  message.writeInt32BE(4 + text.length, 1);",
    "  text.copy(message, 5);",
    "  return message;",
    "}",
    "function postgresErrorCode(payload) {",
    "  let offset = 0;",
    "  while (offset < payload.length && payload[offset] !== 0) {",
    "    const field = String.fromCharCode(payload[offset]);",
    "    offset += 1;",
    "    const end = payload.indexOf(0, offset);",
    "    if (end < 0) break;",
    "    const value = payload.toString(\"utf8\", offset, end);",
    "    if (field === \"C\") return value;",
    "    offset = end + 1;",
    "  }",
    "  return \"UNKNOWN\";",
    "}",
    "function postgresDataRow(payload) {",
    "  const count = payload.readInt16BE(0);",
    "  let offset = 2;",
    "  const row = [];",
    "  for (let index = 0; index < count; index += 1) {",
    "    const length = payload.readInt32BE(offset);",
    "    offset += 4;",
    "    if (length === -1) { row.push(null); continue; }",
    "    row.push(payload.toString(\"utf8\", offset, offset + length));",
    "    offset += length;",
    "  }",
    "  return row;",
    "}",
    "function postgresSimpleQuery(connectionString, sql) {",
    "  const config = postgresStateConfig(connectionString);",
    "  return new Promise((resolve, reject) => {",
    "    let settled = false;",
    "    let querySent = false;",
    "    let buffer = Buffer.alloc(0);",
    "    const rows = [];",
    "    const socket = createPostgresConnection({ host: config.host, port: config.port });",
    "    const timer = setTimeout(() => finish(new Error(\"POSTGRES_TIMEOUT\")), 5000);",
    "    function finish(error) {",
    "      if (settled) return;",
    "      settled = true;",
    "      clearTimeout(timer);",
    "      socket.destroy();",
    "      if (error) reject(error); else resolve(rows);",
    "    }",
    "    socket.once(\"connect\", () => socket.write(postgresStartup(config)));",
    "    socket.once(\"error\", () => finish(new Error(\"POSTGRES_SOCKET_FAILED\")));",
    "    socket.on(\"data\", (chunk) => {",
    "      buffer = Buffer.concat([buffer, chunk]);",
    "      while (buffer.length >= 5) {",
    "        const type = String.fromCharCode(buffer[0]);",
    "        const length = buffer.readInt32BE(1);",
    "        const total = 1 + length;",
    "        if (length < 4 || buffer.length < total) return;",
    "        const payload = buffer.subarray(5, total);",
    "        buffer = buffer.subarray(total);",
    "        if (type === \"R\") {",
    "          const auth = payload.readInt32BE(0);",
    "          if (auth !== 0) { finish(new Error(`POSTGRES_AUTH_UNSUPPORTED:${auth}`)); return; }",
    "        } else if (type === \"E\") {",
    "          finish(new Error(`POSTGRES_QUERY_FAILED:${postgresErrorCode(payload)}`));",
    "          return;",
    "        } else if (type === \"D\") {",
    "          rows.push(postgresDataRow(payload));",
    "        } else if (type === \"Z\") {",
    "          if (!querySent) {",
    "            querySent = true;",
    "            socket.write(postgresQueryMessage(sql));",
    "          } else {",
    "            finish();",
    "            return;",
    "          }",
    "        }",
    "      }",
    "    });",
    "  });",
    "}",
    "async function incrementPostgresCounter(connectionString) {",
    "  const rows = await postgresSimpleQuery(connectionString, \"INSERT INTO runtime_counter (id, value) VALUES (1, 1) ON CONFLICT (id) DO UPDATE SET value = runtime_counter.value + 1 RETURNING value\");",
    "  const value = Number(rows.at(-1)?.[0]);",
    "  if (!Number.isInteger(value) || value < 1) throw new Error(\"POSTGRES_STATE_RESULT_INVALID\");",
    "  return value;",
    "}",
  ].join("\n");
}
