export type RuntimePostgresStateExecutionRequirement = Readonly<{
  capability: string;
  storeKind: "sql";
  connectionBinding: Readonly<{ name: string; kind: "secret-reference" }>;
}>;

export function renderPostgresRuntimeStateSupport(
  requirements: readonly RuntimePostgresStateExecutionRequirement[],
): string {
  if (requirements.length === 0) return "";

  return [
    'import { createConnection as createPostgresConnection } from "node:net";',
    'import { createHash as createPostgresHash, createHmac as createPostgresHmac, pbkdf2Sync as createPostgresPbkdf2, randomBytes as createPostgresRandom } from "node:crypto";',
    'import { readFileSync as createPostgresReadFile } from "node:fs";',
    'import { connect as createPostgresTls } from "node:tls";',
    "function postgresStateConfig(connectionString) {",
    "  let url;",
    "  try { url = new URL(connectionString); } catch { throw new Error(\"POSTGRES_URL_INVALID\"); }",
    "  if (url.protocol !== \"postgres:\" && url.protocol !== \"postgresql:\") throw new Error(\"POSTGRES_URL_INVALID\");",
    "  const user = decodeURIComponent(url.username || \"\");",
    "  const password = decodeURIComponent(url.password || \"\");",
    "  const pathname = url.pathname.startsWith(\"/\") ? url.pathname.slice(1) : url.pathname;",
    "  const database = decodeURIComponent(pathname);",
    "  if (!url.hostname || !user || !database) throw new Error(\"POSTGRES_URL_INVALID\");",
    "  const port = url.port ? Number(url.port) : 5432;",
    "  if (!Number.isInteger(port) || port <= 0 || port > 65535) throw new Error(\"POSTGRES_URL_INVALID\");",
    "  const sslModeValue = url.searchParams.get(\"sslmode\") || \"disable\";",
    "  if (sslModeValue !== \"disable\" && sslModeValue !== \"prefer\" && sslModeValue !== \"require\" && sslModeValue !== \"verify-ca\" && sslModeValue !== \"verify-full\") throw new Error(\"POSTGRES_SSLMODE_INVALID\");",
    "  if (sslModeValue === \"verify-ca\" || sslModeValue === \"verify-full\") {",
    "    const ca = url.searchParams.get(\"sslrootcert\") || \"\";",
    "    if (!ca) throw new Error(\"POSTGRES_SSLMODE_CA_REQUIRED\");",
    "    return { host: url.hostname, port, user, password, database, sslMode: sslModeValue, ca };",
    "  }",
    "  return { host: url.hostname, port, user, password, database, sslMode: sslModeValue };",
    "}",
    "function postgresCString(value) { return Buffer.from(String(value) + \"\\0\", \"utf8\"); }",
    "function postgresStartup(config) {",
    "  const fields = Buffer.concat([postgresCString(\"user\"), postgresCString(config.user), postgresCString(\"database\"), postgresCString(config.database), postgresCString(\"client_encoding\"), postgresCString(\"UTF8\"), Buffer.from([0])]);",
    "  const message = Buffer.allocUnsafe(8 + fields.length);",
    "  message.writeInt32BE(message.length, 0);",
    "  message.writeInt32BE(196608, 4);",
    "  fields.copy(message, 8);",
    "  return message;",
    "}",
    "function postgresSslRequest() { const message = Buffer.allocUnsafe(8); message.writeInt32BE(8, 0); message.writeInt32BE(80877103, 4); return message; }",
    "function postgresQueryMessage(sql) {",
    "  const text = Buffer.from(sql + \"\\0\", \"utf8\");",
    "  const message = Buffer.allocUnsafe(5 + text.length);",
    "  message[0] = 81;",
    "  message.writeInt32BE(4 + text.length, 1);",
    "  text.copy(message, 5);",
    "  return message;",
    "}",
    "function postgresPasswordMessage(password) {",
    "  const text = Buffer.from(password + \"\\0\", \"utf8\");",
    "  const message = Buffer.allocUnsafe(5 + text.length);",
    "  message[0] = 112;",
    "  message.writeInt32BE(4 + text.length, 1);",
    "  text.copy(message, 5);",
    "  return message;",
    "}",
    "function postgresSaslInitial(mechanism, response) {",
    "  const mechanismBytes = postgresCString(mechanism);",
    "  const responseBytes = Buffer.from(response, \"utf8\");",
    "  const message = Buffer.allocUnsafe(1 + 4 + mechanismBytes.length + 4 + responseBytes.length);",
    "  message[0] = 112;",
    "  message.writeInt32BE(message.length - 1, 1);",
    "  mechanismBytes.copy(message, 5);",
    "  message.writeInt32BE(responseBytes.length, 5 + mechanismBytes.length);",
    "  responseBytes.copy(message, 9 + mechanismBytes.length);",
    "  return message;",
    "}",
    "function postgresSaslResponse(response) {",
    "  const responseBytes = Buffer.from(response, \"utf8\");",
    "  const message = Buffer.allocUnsafe(5 + responseBytes.length);",
    "  message[0] = 112;",
    "  message.writeInt32BE(4 + responseBytes.length, 1);",
    "  responseBytes.copy(message, 5);",
    "  return message;",
    "}",
    "function postgresErrorCode(payload) {",
    "  let offset = 0;",
    "  while (offset < payload.length && payload[offset] !== 0) {",
    "    const field = String.fromCharCode(payload[offset]);",
    "    offset += 1;",
    "    const end = payload.indexOf(0, offset);",
    "    if (end < 0) break;",
    "    const value = payload.toString(\"utf8\", offset, end);",
    "    if (field === \"C\") return value;",
    "    offset = end + 1;",
    "  }",
    "  return \"UNKNOWN\";",
    "}",
    "function postgresDataRow(payload) {",
    "  const count = payload.readInt16BE(0);",
    "  let offset = 2;",
    "  const row = [];",
    "  for (let index = 0; index < count; index += 1) {",
    "    const length = payload.readInt32BE(offset);",
    "    offset += 4;",
    "    if (length === -1) { row.push(null); continue; }",
    "    row.push(payload.toString(\"utf8\", offset, offset + length));",
    "    offset += length;",
    "  }",
    "  return row;",
    "}",
    "function postgresMd5(password, user, salt) {",
    "  const inner = createPostgresHash(\"md5\").update(password + user, \"utf8\").digest(\"hex\");",
    "  return \"md5\" + createPostgresHash(\"md5\").update(Buffer.concat([Buffer.from(inner, \"utf8\"), salt])).digest(\"hex\");",
    "}",
    "function postgresScramName(value) { return value.replaceAll(\"=\", \"=3D\").replaceAll(\",\", \"=2C\"); }",
    "function postgresHmac(key, value) { return createPostgresHmac(\"sha256\", key).update(value, \"utf8\").digest(); }",
    "function postgresXor(left, right) { const result = Buffer.allocUnsafe(left.length); for (let index = 0; index < left.length; index += 1) result[index] = left[index] ^ right[index]; return result; }",
    "function postgresScramFields(message) {",
    "  const result = new Map();",
    "  for (const item of message.split(\",\")) { const separator = item.indexOf(\"=\"); if (separator > 0) result.set(item.slice(0, separator), item.slice(separator + 1)); }",
    "  return result;",
    "}",
    "function postgresConnect(config) {",
    "  return new Promise((resolve, reject) => {",
    "    let settled = false;",
    "    const socket = createPostgresConnection({ host: config.host, port: config.port });",
    "    const timer = setTimeout(() => finish(undefined, new Error(\"POSTGRES_TIMEOUT\")), 5000);",
    "    function finish(value, error) {",
    "      if (settled) return;",
    "      settled = true;",
    "      clearTimeout(timer);",
    "      if (error) { socket.destroy(); reject(error); } else if (value !== undefined) resolve(value);",
    "    }",
    "    socket.once(\"error\", () => finish(undefined, new Error(\"POSTGRES_SOCKET_FAILED\")));",
    "    socket.once(\"connect\", () => {",
    "      if (config.sslMode === \"disable\") { finish(socket); return; }",
    "      socket.write(postgresSslRequest());",
    "      socket.once(\"data\", (chunk) => {",
    "        const response = chunk[0];",
    "        if (response === 78) {",
    "          if (config.sslMode === \"require\" || config.sslMode === \"verify-ca\" || config.sslMode === \"verify-full\") finish(undefined, new Error(\"POSTGRES_TLS_REQUIRED\")); else finish(socket);",
    "          return;",
    "        }",
    "        if (response !== 83) { finish(undefined, new Error(\"POSTGRES_TLS_NEGOTIATION_FAILED\")); return; }",
    "        if (config.sslMode === \"verify-ca\" || config.sslMode === \"verify-full\") {",
    "          let ca;",
    "          try { ca = createPostgresReadFile(config.ca, \"utf8\"); } catch { finish(undefined, new Error(\"POSTGRES_TLS_CA_UNAVAILABLE\")); return; }",
    "          const secure = createPostgresTls({ socket, servername: config.host, rejectUnauthorized: true, ca, ...(config.sslMode === \"verify-ca\" ? { checkServerIdentity: () => undefined } : {}) });",
    "          secure.once(\"secureConnect\", () => finish(secure));",
    "          secure.once(\"error\", (error) => finish(undefined, new Error(error && error.code === \"ERR_TLS_CERT_ALTNAME_INVALID\" ? \"POSTGRES_TLS_HOSTNAME_MISMATCH\" : \"POSTGRES_TLS_CERT_UNTRUSTED\")));",
    "        } else {",
    "          const secure = createPostgresTls({ socket, servername: config.host, rejectUnauthorized: false });",
    "          secure.once(\"secureConnect\", () => finish(secure));",
    "          secure.once(\"error\", () => finish(undefined, new Error(\"POSTGRES_TLS_FAILED\")));",
    "        }",
    "      });",
    "    });",
    "  });",
    "}",
    "function postgresSimpleQuery(connectionString, sql) {",
    "  const config = postgresStateConfig(connectionString);",
    "  return postgresConnect(config).then((socket) => new Promise((resolve, reject) => {",
    "    let settled = false;",
    "    let querySent = false;",
    "    let buffer = Buffer.alloc(0);",
    "    const rows = [];",
    "    let scram;",
    "    const timer = setTimeout(() => finish(new Error(\"POSTGRES_TIMEOUT\")), 5000);",
    "    function finish(error) {",
    "      if (settled) return;",
    "      settled = true;",
    "      clearTimeout(timer);",
    "      socket.destroy();",
    "      if (error) reject(error); else resolve(rows);",
    "    }",
    "    socket.once(\"error\", () => finish(new Error(\"POSTGRES_SOCKET_FAILED\")));",
    "    socket.write(postgresStartup(config));",
    "    socket.on(\"data\", (chunk) => {",
    "      buffer = Buffer.concat([buffer, chunk]);",
    "      while (buffer.length >= 5) {",
    "        const type = String.fromCharCode(buffer[0]);",
    "        const length = buffer.readInt32BE(1);",
    "        const total = 1 + length;",
    "        if (length < 4 || buffer.length < total) return;",
    "        const payload = buffer.subarray(5, total);",
    "        buffer = buffer.subarray(total);",
    "        if (type === \"R\") {",
    "          if (payload.length < 4) { finish(new Error(\"POSTGRES_AUTH_FAILED:PROTOCOL\")); return; }",
    "          const auth = payload.readInt32BE(0);",
    "          if (auth === 0) continue;",
    "          if (auth === 3) { if (!config.password) { finish(new Error(\"POSTGRES_PASSWORD_REQUIRED\")); return; } socket.write(postgresPasswordMessage(config.password)); continue; }",
    "          if (auth === 5) { if (!config.password || payload.length < 8) { finish(new Error(\"POSTGRES_PASSWORD_REQUIRED\")); return; } socket.write(postgresPasswordMessage(postgresMd5(config.password, config.user, payload.subarray(4, 8)))); continue; }",
    "          if (auth === 10) {",
    "            if (!config.password) { finish(new Error(\"POSTGRES_PASSWORD_REQUIRED\")); return; }",
    "            const mechanisms = payload.subarray(4).toString(\"utf8\").split(\"\\0\").filter(Boolean);",
    "            if (!mechanisms.includes(\"SCRAM-SHA-256\")) { finish(new Error(\"POSTGRES_AUTH_UNSUPPORTED:10\")); return; }",
    "            const clientNonce = createPostgresRandom(18).toString(\"base64\");",
    "            const clientFirstBare = \"n=\" + postgresScramName(config.user) + \",r=\" + clientNonce;",
    "            scram = { clientFirstBare, clientNonce };",
    "            socket.write(postgresSaslInitial(\"SCRAM-SHA-256\", \"n,,\" + clientFirstBare));",
    "            continue;",
    "          }",
    "          if (auth === 11) {",
    "            if (!scram) { finish(new Error(\"POSTGRES_AUTH_FAILED:SCRAM_STATE\")); return; }",
    "            const serverFirst = payload.subarray(4).toString(\"utf8\");",
    "            const fields = postgresScramFields(serverFirst);",
    "            const nonce = fields.get(\"r\");",
    "            const salt = fields.get(\"s\");",
    "            const iterationsText = fields.get(\"i\");",
    "            const iterations = iterationsText === undefined ? Number.NaN : Number(iterationsText);",
    "            if (!nonce || !nonce.startsWith(scram.clientNonce) || !salt || !Number.isInteger(iterations) || iterations <= 0) { finish(new Error(\"POSTGRES_AUTH_FAILED:SCRAM_CHALLENGE\")); return; }",
    "            const clientFinalWithoutProof = \"c=biws,r=\" + nonce;",
    "            const authMessage = scram.clientFirstBare + \",\" + serverFirst + \",\" + clientFinalWithoutProof;",
    "            const saltedPassword = createPostgresPbkdf2(config.password, Buffer.from(salt, \"base64\"), iterations, 32, \"sha256\");",
    "            const clientKey = postgresHmac(saltedPassword, \"Client Key\");",
    "            const storedKey = createPostgresHash(\"sha256\").update(clientKey).digest();",
    "            const proof = postgresXor(clientKey, postgresHmac(storedKey, authMessage)).toString(\"base64\");",
    "            scram.serverSignature = postgresHmac(postgresHmac(saltedPassword, \"Server Key\"), authMessage).toString(\"base64\");",
    "            socket.write(postgresSaslResponse(clientFinalWithoutProof + \",p=\" + proof));",
    "            continue;",
    "          }",
    "          if (auth === 12) {",
    "            if (!scram || !scram.serverSignature) { finish(new Error(\"POSTGRES_AUTH_FAILED:SCRAM_STATE\")); return; }",
    "            if (postgresScramFields(payload.subarray(4).toString(\"utf8\")).get(\"v\") !== scram.serverSignature) { finish(new Error(\"POSTGRES_AUTH_FAILED:SCRAM_SIGNATURE\")); return; }",
    "            continue;",
    "          }",
    "          finish(new Error(\"POSTGRES_AUTH_UNSUPPORTED:\" + auth)); return;",
    "        } else if (type === \"E\") {",
    "          finish(new Error((querySent ? \"POSTGRES_QUERY_FAILED\" : \"POSTGRES_AUTH_FAILED\") + \":\" + postgresErrorCode(payload)));",
    "          return;",
    "        } else if (type === \"D\") {",
    "          rows.push(postgresDataRow(payload));",
    "        } else if (type === \"Z\") {",
    "          if (!querySent) {",
    "            querySent = true;",
    "            socket.write(postgresQueryMessage(sql));",
    "          } else {",
    "            finish();",
    "            return;",
    "          }",
    "        }",
    "      }",
    "    });",
    "  }));",
    "}",
    "async function incrementPostgresCounter(connectionString) {",
    "  const rows = await postgresSimpleQuery(connectionString, \"INSERT INTO runtime_counter (id, value) VALUES (1, 1) ON CONFLICT (id) DO UPDATE SET value = runtime_counter.value + 1 RETURNING value\");",
    "  const value = Number(rows.at(-1)?.[0]);",
    "  if (!Number.isInteger(value) || value < 1) throw new Error(\"POSTGRES_STATE_RESULT_INVALID\");",
    "  return value;",
    "}",
  ].join("\n");
}
