import { normalizeCurrentnessQualification, normalizeDefinitionRevisionRef, type CurrentnessQualification, type DefinitionRevisionRef } from "../semantic-substrate/index.js";
import { normalizeLocalityQualification, type LocalityQualification } from "../semantic-substrate/federation.js";

export const IDENTITY_AUTHORIZATION_CONTRACT_VERSION = "1.0.0" as const;
export type AuthenticationState = "AUTHENTICATED" | "REJECTED" | "UNKNOWN";
export type IdentityReference = Readonly<{ contractVersion: typeof IDENTITY_AUTHORIZATION_CONTRACT_VERSION; identity: DefinitionRevisionRef }>;
export type AuthenticationEvidenceReference = Readonly<{ contractVersion: typeof IDENTITY_AUTHORIZATION_CONTRACT_VERSION; subjectIdentity: DefinitionRevisionRef; evidence: DefinitionRevisionRef; currentness: CurrentnessQualification; locality: LocalityQualification; state: AuthenticationState }>;
export type ActorContext = Readonly<{ contractVersion: typeof IDENTITY_AUTHORIZATION_CONTRACT_VERSION; identity: IdentityReference; authentication: AuthenticationEvidenceReference }>;
type UnknownRecord = Record<string, unknown>;
function asRecord(value: unknown, label: string): UnknownRecord { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error(`${label} must be an object`); return value as UnknownRecord; }
function assertExactFields(record: UnknownRecord, fields: readonly string[], label: string): void { for (const key of Object.keys(record)) if (!fields.includes(key)) throw new Error(`${label} has unexpected field ${key}`); for (const key of fields) if (!(key in record)) throw new Error(`${label} is missing field ${key}`); }
function version(value: unknown): typeof IDENTITY_AUTHORIZATION_CONTRACT_VERSION { if (value !== IDENTITY_AUTHORIZATION_CONTRACT_VERSION) throw new Error(`unsupported identity/authorization contract version: ${String(value)}`); return IDENTITY_AUTHORIZATION_CONTRACT_VERSION; }
function revisionKey(value: DefinitionRevisionRef): string { return [value.semanticOwner, value.semanticKind, value.canonicalRef, value.definitionRef, value.revisionOwner, value.revisionDimension, value.revisionRef].join("\u0000"); }
export function normalizeIdentityReference(input: unknown): IdentityReference { const record = asRecord(input, "identity reference"); assertExactFields(record, ["contractVersion", "identity"], "identity reference"); return Object.freeze({ contractVersion: version(record.contractVersion), identity: normalizeDefinitionRevisionRef(record.identity) }); }
export function normalizeAuthenticationEvidenceReference(input: unknown): AuthenticationEvidenceReference { const record = asRecord(input, "authentication evidence reference"); assertExactFields(record, ["contractVersion", "subjectIdentity", "evidence", "currentness", "locality", "state"], "authentication evidence reference"); const subjectIdentity = normalizeDefinitionRevisionRef(record.subjectIdentity); const evidence = normalizeDefinitionRevisionRef(record.evidence); const currentness = normalizeCurrentnessQualification(record.currentness); if (revisionKey(currentness.subject) !== revisionKey(evidence)) throw new Error("authentication currentness must qualify the exact evidence revision"); const locality = normalizeLocalityQualification(record.locality); if (currentness.localityScope !== locality.localityRef) throw new Error("authentication currentness locality must exactly match evidence locality"); if (record.state !== "AUTHENTICATED" && record.state !== "REJECTED" && record.state !== "UNKNOWN") throw new Error("authentication state must be AUTHENTICATED, REJECTED or UNKNOWN"); if (record.state === "AUTHENTICATED" && currentness.state !== "CURRENT") throw new Error("authenticated evidence must be CURRENT; stale or unknown evidence cannot authenticate"); return Object.freeze({ contractVersion: version(record.contractVersion), subjectIdentity, evidence, currentness, locality, state: record.state }); }
export function normalizeActorContext(input: unknown): ActorContext { const record = asRecord(input, "actor context"); assertExactFields(record, ["contractVersion", "identity", "authentication"], "actor context"); const identity = normalizeIdentityReference(record.identity); const authentication = normalizeAuthenticationEvidenceReference(record.authentication); if (revisionKey(identity.identity) !== revisionKey(authentication.subjectIdentity)) throw new Error("authentication evidence must bind the exact actor identity revision"); return Object.freeze({ contractVersion: version(record.contractVersion), identity, authentication }); }
