import { normalizeCurrentnessQualification, normalizeDefinitionRevisionRef, type CurrentnessQualification, type DefinitionRevisionRef } from "../semantic-substrate/index.js";
import { normalizeLocalityQualification, type LocalityQualification } from "../semantic-substrate/federation.js";

export const IDENTITY_AUTHORIZATION_CONTRACT_VERSION = "1.0.0" as const;
export type AuthenticationState = "AUTHENTICATED" | "REJECTED" | "UNKNOWN";
export type IdentityReference = Readonly<{ contractVersion: typeof IDENTITY_AUTHORIZATION_CONTRACT_VERSION; identity: DefinitionRevisionRef }>;
export type AuthenticationEvidenceReference = Readonly<{ contractVersion: typeof IDENTITY_AUTHORIZATION_CONTRACT_VERSION; subjectIdentity: DefinitionRevisionRef; evidence: DefinitionRevisionRef; currentness: CurrentnessQualification; locality: LocalityQualification; state: AuthenticationState }>;
export type ActorContext = Readonly<{ contractVersion: typeof IDENTITY_AUTHORIZATION_CONTRACT_VERSION; identity: IdentityReference; authentication: AuthenticationEvidenceReference }>;
export type AuthorizationDisposition = "ALLOW" | "DENY" | "UNKNOWN";
export type AuthorizationEvidenceState = "SUFFICIENT" | "INSUFFICIENT" | "UNKNOWN";
export type AuthorizationEvidenceReference = Readonly<{ contractVersion: typeof IDENTITY_AUTHORIZATION_CONTRACT_VERSION; evidence: DefinitionRevisionRef; currentness: CurrentnessQualification; locality: LocalityQualification; state: AuthorizationEvidenceState }>;
export type AuthorizationScope = Readonly<{ action: string; resource: string; scope: string; locality: LocalityQualification }>;
export type AuthorizationRequest = Readonly<{ contractVersion: typeof IDENTITY_AUTHORIZATION_CONTRACT_VERSION; actor: ActorContext; authorityPolicy: DefinitionRevisionRef; policyCurrentness: CurrentnessQualification; authorizationEvidence: AuthorizationEvidenceReference; requested: AuthorizationScope }>;
export type AuthorizationDecision = Readonly<{ contractVersion: typeof IDENTITY_AUTHORIZATION_CONTRACT_VERSION; request: AuthorizationRequest; disposition: AuthorizationDisposition }>;
type UnknownRecord = Record<string, unknown>;
function asRecord(value: unknown, label: string): UnknownRecord { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error(`${label} must be an object`); return value as UnknownRecord; }
function assertExactFields(record: UnknownRecord, fields: readonly string[], label: string): void { for (const key of Object.keys(record)) if (!fields.includes(key)) throw new Error(`${label} has unexpected field ${key}`); for (const key of fields) if (!(key in record)) throw new Error(`${label} is missing field ${key}`); }
function version(value: unknown): typeof IDENTITY_AUTHORIZATION_CONTRACT_VERSION { if (value !== IDENTITY_AUTHORIZATION_CONTRACT_VERSION) throw new Error(`unsupported identity/authorization contract version: ${String(value)}`); return IDENTITY_AUTHORIZATION_CONTRACT_VERSION; }
function nonEmptyString(value: unknown, label: string): string { if (typeof value !== "string" || value.length === 0) throw new Error(`${label} must be a non-empty string`); return value; }
function revisionKey(value: DefinitionRevisionRef): string { return [value.semanticOwner, value.semanticKind, value.canonicalRef, value.definitionRef, value.revisionOwner, value.revisionDimension, value.revisionRef].join("\u0000"); }
function localityKey(value: LocalityQualification): string { return `${value.scopeKind}\u0000${value.localityRef}`; }
export function normalizeIdentityReference(input: unknown): IdentityReference { const record = asRecord(input, "identity reference"); assertExactFields(record, ["contractVersion", "identity"], "identity reference"); return Object.freeze({ contractVersion: version(record.contractVersion), identity: normalizeDefinitionRevisionRef(record.identity) }); }
export function normalizeAuthenticationEvidenceReference(input: unknown): AuthenticationEvidenceReference { const record = asRecord(input, "authentication evidence reference"); assertExactFields(record, ["contractVersion", "subjectIdentity", "evidence", "currentness", "locality", "state"], "authentication evidence reference"); const subjectIdentity = normalizeDefinitionRevisionRef(record.subjectIdentity); const evidence = normalizeDefinitionRevisionRef(record.evidence); const currentness = normalizeCurrentnessQualification(record.currentness); if (revisionKey(currentness.subject) !== revisionKey(evidence)) throw new Error("authentication currentness must qualify the exact evidence revision"); const locality = normalizeLocalityQualification(record.locality); if (currentness.localityScope !== locality.localityRef) throw new Error("authentication currentness locality must exactly match evidence locality"); if (record.state !== "AUTHENTICATED" && record.state !== "REJECTED" && record.state !== "UNKNOWN") throw new Error("authentication state must be AUTHENTICATED, REJECTED or UNKNOWN"); if (record.state === "AUTHENTICATED" && currentness.state !== "CURRENT") throw new Error("authenticated evidence must be CURRENT; stale or unknown evidence cannot authenticate"); return Object.freeze({ contractVersion: version(record.contractVersion), subjectIdentity, evidence, currentness, locality, state: record.state }); }
export function normalizeActorContext(input: unknown): ActorContext { const record = asRecord(input, "actor context"); assertExactFields(record, ["contractVersion", "identity", "authentication"], "actor context"); const identity = normalizeIdentityReference(record.identity); const authentication = normalizeAuthenticationEvidenceReference(record.authentication); if (revisionKey(identity.identity) !== revisionKey(authentication.subjectIdentity)) throw new Error("authentication evidence must bind the exact actor identity revision"); return Object.freeze({ contractVersion: version(record.contractVersion), identity, authentication }); }
export function normalizeAuthorizationEvidenceReference(input: unknown): AuthorizationEvidenceReference { const record = asRecord(input, "authorization evidence reference"); assertExactFields(record, ["contractVersion", "evidence", "currentness", "locality", "state"], "authorization evidence reference"); const evidence = normalizeDefinitionRevisionRef(record.evidence); const currentness = normalizeCurrentnessQualification(record.currentness); if (revisionKey(currentness.subject) !== revisionKey(evidence)) throw new Error("authorization currentness must qualify the exact evidence revision"); const locality = normalizeLocalityQualification(record.locality); if (currentness.localityScope !== locality.localityRef) throw new Error("authorization evidence currentness locality must exactly match evidence locality"); if (record.state !== "SUFFICIENT" && record.state !== "INSUFFICIENT" && record.state !== "UNKNOWN") throw new Error("authorization evidence state must be SUFFICIENT, INSUFFICIENT or UNKNOWN"); return Object.freeze({ contractVersion: version(record.contractVersion), evidence, currentness, locality, state: record.state }); }
export function normalizeAuthorizationScope(input: unknown): AuthorizationScope { const record = asRecord(input, "authorization scope"); assertExactFields(record, ["action", "resource", "scope", "locality"], "authorization scope"); return Object.freeze({ action: nonEmptyString(record.action, "authorization action"), resource: nonEmptyString(record.resource, "authorization resource"), scope: nonEmptyString(record.scope, "authorization scope"), locality: normalizeLocalityQualification(record.locality) }); }
export function normalizeAuthorizationRequest(input: unknown): AuthorizationRequest { const record = asRecord(input, "authorization request"); assertExactFields(record, ["contractVersion", "actor", "authorityPolicy", "policyCurrentness", "authorizationEvidence", "requested"], "authorization request"); const actor = normalizeActorContext(record.actor); const authorityPolicy = normalizeDefinitionRevisionRef(record.authorityPolicy); const policyCurrentness = normalizeCurrentnessQualification(record.policyCurrentness); if (revisionKey(policyCurrentness.subject) !== revisionKey(authorityPolicy)) throw new Error("policy currentness must qualify the exact authority policy revision"); const authorizationEvidence = normalizeAuthorizationEvidenceReference(record.authorizationEvidence); const requested = normalizeAuthorizationScope(record.requested); if (policyCurrentness.localityScope !== requested.locality.localityRef) throw new Error("policy currentness locality must exactly match requested locality"); if (localityKey(authorizationEvidence.locality) !== localityKey(requested.locality)) throw new Error("authorization evidence locality must exactly match requested locality"); if (localityKey(actor.authentication.locality) !== localityKey(requested.locality)) throw new Error("authentication locality cannot be strengthened or substituted for authorization"); return Object.freeze({ contractVersion: version(record.contractVersion), actor, authorityPolicy, policyCurrentness, authorizationEvidence, requested }); }
export function normalizeAuthorizationDecision(input: unknown, expectedRequest?: AuthorizationRequest): AuthorizationDecision { const record = asRecord(input, "authorization decision"); assertExactFields(record, ["contractVersion", "request", "disposition"], "authorization decision"); const request = normalizeAuthorizationRequest(record.request); if (expectedRequest !== undefined && JSON.stringify(request) !== JSON.stringify(normalizeAuthorizationRequest(expectedRequest))) throw new Error("authorization decision request does not match the exact expected actor/policy/scope envelope"); if (record.disposition !== "ALLOW" && record.disposition !== "DENY" && record.disposition !== "UNKNOWN") throw new Error("authorization disposition must be ALLOW, DENY or UNKNOWN"); if (record.disposition === "ALLOW") { if (request.actor.authentication.state !== "AUTHENTICATED") throw new Error("authentication does not imply authorization; ALLOW requires authenticated evidence"); if (request.policyCurrentness.state !== "CURRENT") throw new Error("stale or unknown policy cannot produce ALLOW"); if (request.authorizationEvidence.currentness.state !== "CURRENT" || request.authorizationEvidence.state !== "SUFFICIENT") throw new Error("stale, unknown or insufficient authorization evidence cannot produce ALLOW"); } return Object.freeze({ contractVersion: version(record.contractVersion), request, disposition: record.disposition }); }
