import { normalizeCurrentnessQualification, normalizeDefinitionRevisionRef, type CurrentnessQualification, type DefinitionRevisionRef } from "../semantic-substrate/index.js";
import { normalizeLocalityQualification, type LocalityQualification } from "../semantic-substrate/federation.js";

export const RECOVERY_CONTRACT_VERSION = "1.0.0" as const;
export type RecoveryVerificationState = "PARTIAL" | "VERIFIED" | "UNKNOWN";
export type EffectKnowledge = "KNOWN" | "UNKNOWN";
export type DuplicateSafety = "PROVEN" | "UNKNOWN";
export type RetryDisposition = "SAFE_RETRY" | "RECONCILE_BEFORE_RETRY";
export type QuiescenceState = "CONFIRMED" | "UNKNOWN";
export type ResidualRecoveryDisposition = "ACTIVE" | "FENCED" | "DRAINED" | "UNKNOWN";

type UnknownRecord = Record<string, unknown>;
const asRecord=(value:unknown,label:string):UnknownRecord=>{if(typeof value!=="object"||value===null||Array.isArray(value)) throw new Error(`${label} must be an object`);return value as UnknownRecord;};
const exact=(record:UnknownRecord,fields:readonly string[],label:string)=>{for(const key of Object.keys(record)) if(!fields.includes(key)) throw new Error(`${label} has unexpected field ${key}`);for(const key of fields) if(!(key in record)) throw new Error(`${label} is missing field ${key}`);};
const nonEmpty=(value:unknown,label:string):string=>{if(typeof value!=="string"||value.trim()==="") throw new Error(`${label} must be non-empty`);return value.trim();};
const version=(value:unknown)=>{if(value!==RECOVERY_CONTRACT_VERSION) throw new Error("unsupported recovery contract version");return RECOVERY_CONTRACT_VERSION;};
const revisionKey=(value:DefinitionRevisionRef)=>[value.semanticOwner,value.semanticKind,value.canonicalRef,value.definitionRef,value.revisionOwner,value.revisionDimension,value.revisionRef].join("\0");
const localityKey=(value:LocalityQualification)=>`${value.scopeKind}\0${value.localityRef}`;
const assertEvidence=(evidence:DefinitionRevisionRef,currentness:CurrentnessQualification,locality:LocalityQualification,label:string)=>{if(revisionKey(currentness.subject)!==revisionKey(evidence)) throw new Error(`${label} currentness must qualify exact evidence revision`);if(currentness.localityScope!==locality.localityRef) throw new Error(`${label} currentness locality must match evidence locality`);};

export type DegradedAuthorityCeiling = Readonly<{contractVersion:typeof RECOVERY_CONTRACT_VERSION;authorityPolicy:DefinitionRevisionRef;policyCurrentness:CurrentnessQualification;allowedScopes:readonly string[];prohibitedScopes:readonly string[];locality:LocalityQualification;validUntil:string;reviewCondition:string}>;
export type RecoveryCut = Readonly<{contractVersion:typeof RECOVERY_CONTRACT_VERSION;sourceRevision:DefinitionRevisionRef;cutEvidence:DefinitionRevisionRef;currentness:CurrentnessQualification;locality:LocalityQualification}>;
export type FencingObservation = Readonly<{contractVersion:typeof RECOVERY_CONTRACT_VERSION;actor:DefinitionRevisionRef;epoch:DefinitionRevisionRef;supersedesEpoch:DefinitionRevisionRef|null;oldActorQuiescence:QuiescenceState;evidence:DefinitionRevisionRef;currentness:CurrentnessQualification;locality:LocalityQualification}>;
export type RecoveryEffect = Readonly<{contractVersion:typeof RECOVERY_CONTRACT_VERSION;effectRef:string;knowledge:EffectKnowledge;duplicateSafety:DuplicateSafety;retryDisposition:RetryDisposition;evidence:DefinitionRevisionRef;currentness:CurrentnessQualification;locality:LocalityQualification}>;
export type ResidualRecoveryCohort = Readonly<{contractVersion:typeof RECOVERY_CONTRACT_VERSION;cohortRef:string;generation:DefinitionRevisionRef;disposition:ResidualRecoveryDisposition;evidence:DefinitionRevisionRef;currentness:CurrentnessQualification;locality:LocalityQualification}>;
export type RecoveryRequalification = Readonly<{contractVersion:typeof RECOVERY_CONTRACT_VERSION;ceiling:DegradedAuthorityCeiling;cut:RecoveryCut;fencing:FencingObservation;restoredAuthority:DefinitionRevisionRef;currentAuthority:DefinitionRevisionRef;restoredTrust:DefinitionRevisionRef;currentTrust:DefinitionRevisionRef;restoredConfig:DefinitionRevisionRef;currentConfig:DefinitionRevisionRef;postCutRevocations:readonly DefinitionRevisionRef[];postCutRotations:readonly DefinitionRevisionRef[];postCutConfigRevisions:readonly DefinitionRevisionRef[];effects:readonly RecoveryEffect[];residualCohorts:readonly ResidualRecoveryCohort[];evidence:DefinitionRevisionRef;currentness:CurrentnessQualification;locality:LocalityQualification;state:RecoveryVerificationState}>;

export function normalizeDegradedAuthorityCeiling(input:unknown):DegradedAuthorityCeiling{
  const r=asRecord(input,"degraded authority ceiling");exact(r,["contractVersion","authorityPolicy","policyCurrentness","allowedScopes","prohibitedScopes","locality","validUntil","reviewCondition"],"degraded authority ceiling");
  const authorityPolicy=normalizeDefinitionRevisionRef(r.authorityPolicy);const policyCurrentness=normalizeCurrentnessQualification(r.policyCurrentness);const locality=normalizeLocalityQualification(r.locality);
  if(revisionKey(policyCurrentness.subject)!==revisionKey(authorityPolicy)) throw new Error("degraded authority policy currentness must qualify the exact authority revision");if(policyCurrentness.localityScope!==locality.localityRef) throw new Error("degraded authority locality must exactly match policy currentness locality");
  if(!Array.isArray(r.allowedScopes)||!Array.isArray(r.prohibitedScopes)) throw new Error("degraded authority scopes must be arrays");const allowedScopes=Object.freeze(r.allowedScopes.map(v=>nonEmpty(v,"allowed scope")));const prohibitedScopes=Object.freeze(r.prohibitedScopes.map(v=>nonEmpty(v,"prohibited scope")));if(new Set(allowedScopes).size!==allowedScopes.length||new Set(prohibitedScopes).size!==prohibitedScopes.length) throw new Error("degraded authority scopes must be unique");if(allowedScopes.some(v=>prohibitedScopes.includes(v))) throw new Error("a degraded scope cannot be both allowed and prohibited");
  return Object.freeze({contractVersion:version(r.contractVersion),authorityPolicy,policyCurrentness,allowedScopes,prohibitedScopes,locality,validUntil:nonEmpty(r.validUntil,"valid until"),reviewCondition:nonEmpty(r.reviewCondition,"review condition")});
}
export function normalizeRecoveryCut(input:unknown):RecoveryCut{
  const r=asRecord(input,"recovery cut");exact(r,["contractVersion","sourceRevision","cutEvidence","currentness","locality"],"recovery cut");const sourceRevision=normalizeDefinitionRevisionRef(r.sourceRevision);const cutEvidence=normalizeDefinitionRevisionRef(r.cutEvidence);const currentness=normalizeCurrentnessQualification(r.currentness);const locality=normalizeLocalityQualification(r.locality);assertEvidence(cutEvidence,currentness,locality,"recovery cut");return Object.freeze({contractVersion:version(r.contractVersion),sourceRevision,cutEvidence,currentness,locality});
}
export function normalizeFencingObservation(input:unknown,expectedEpoch?:DefinitionRevisionRef):FencingObservation{
  const r=asRecord(input,"fencing observation");exact(r,["contractVersion","actor","epoch","supersedesEpoch","oldActorQuiescence","evidence","currentness","locality"],"fencing observation");const actor=normalizeDefinitionRevisionRef(r.actor);const epoch=normalizeDefinitionRevisionRef(r.epoch);const supersedesEpoch=r.supersedesEpoch===null?null:normalizeDefinitionRevisionRef(r.supersedesEpoch);const evidence=normalizeDefinitionRevisionRef(r.evidence);const currentness=normalizeCurrentnessQualification(r.currentness);const locality=normalizeLocalityQualification(r.locality);assertEvidence(evidence,currentness,locality,"fencing observation");if(r.oldActorQuiescence!=="CONFIRMED"&&r.oldActorQuiescence!=="UNKNOWN") throw new Error("old actor quiescence must be CONFIRMED or UNKNOWN");if(supersedesEpoch!==null&&revisionKey(supersedesEpoch)===revisionKey(epoch)) throw new Error("fencing epoch cannot supersede itself");if(expectedEpoch!==undefined&&revisionKey(epoch)!==revisionKey(normalizeDefinitionRevisionRef(expectedEpoch))) throw new Error("superseded fencing epoch reuse is not allowed");return Object.freeze({contractVersion:version(r.contractVersion),actor,epoch,supersedesEpoch,oldActorQuiescence:r.oldActorQuiescence,evidence,currentness,locality});
}
export function normalizeRecoveryEffect(input:unknown):RecoveryEffect{
  const r=asRecord(input,"recovery effect");exact(r,["contractVersion","effectRef","knowledge","duplicateSafety","retryDisposition","evidence","currentness","locality"],"recovery effect");const evidence=normalizeDefinitionRevisionRef(r.evidence);const currentness=normalizeCurrentnessQualification(r.currentness);const locality=normalizeLocalityQualification(r.locality);assertEvidence(evidence,currentness,locality,"recovery effect");if(r.knowledge!=="KNOWN"&&r.knowledge!=="UNKNOWN") throw new Error("effect knowledge must be KNOWN or UNKNOWN");if(r.duplicateSafety!=="PROVEN"&&r.duplicateSafety!=="UNKNOWN") throw new Error("duplicate safety must be PROVEN or UNKNOWN");if(r.retryDisposition!=="SAFE_RETRY"&&r.retryDisposition!=="RECONCILE_BEFORE_RETRY") throw new Error("invalid retry disposition");if(r.knowledge==="UNKNOWN"&&r.duplicateSafety!=="PROVEN"&&r.retryDisposition!=="RECONCILE_BEFORE_RETRY") throw new Error("UNKNOWN effect must reconcile before retry unless duplicate safety is independently proven");if(r.retryDisposition==="SAFE_RETRY"&&r.duplicateSafety!=="PROVEN") throw new Error("SAFE_RETRY requires independently proven duplicate safety");return Object.freeze({contractVersion:version(r.contractVersion),effectRef:nonEmpty(r.effectRef,"effect ref"),knowledge:r.knowledge,duplicateSafety:r.duplicateSafety,retryDisposition:r.retryDisposition,evidence,currentness,locality});
}
export function normalizeResidualRecoveryCohort(input:unknown):ResidualRecoveryCohort{
  const r=asRecord(input,"residual recovery cohort");exact(r,["contractVersion","cohortRef","generation","disposition","evidence","currentness","locality"],"residual recovery cohort");const generation=normalizeDefinitionRevisionRef(r.generation);const evidence=normalizeDefinitionRevisionRef(r.evidence);const currentness=normalizeCurrentnessQualification(r.currentness);const locality=normalizeLocalityQualification(r.locality);assertEvidence(evidence,currentness,locality,"residual recovery cohort");if(!["ACTIVE","FENCED","DRAINED","UNKNOWN"].includes(String(r.disposition))) throw new Error("invalid residual recovery disposition");if(r.disposition==="DRAINED"&&currentness.state!=="CURRENT") throw new Error("DRAINED recovery cohort requires current evidence");return Object.freeze({contractVersion:version(r.contractVersion),cohortRef:nonEmpty(r.cohortRef,"cohort ref"),generation,disposition:r.disposition as ResidualRecoveryDisposition,evidence,currentness,locality});
}
export function normalizeRecoveryRequalification(input:unknown):RecoveryRequalification{
  const r=asRecord(input,"recovery requalification");exact(r,["contractVersion","ceiling","cut","fencing","restoredAuthority","currentAuthority","restoredTrust","currentTrust","restoredConfig","currentConfig","postCutRevocations","postCutRotations","postCutConfigRevisions","effects","residualCohorts","evidence","currentness","locality","state"],"recovery requalification");
  const ceiling=normalizeDegradedAuthorityCeiling(r.ceiling);const cut=normalizeRecoveryCut(r.cut);const fencing=normalizeFencingObservation(r.fencing);const restoredAuthority=normalizeDefinitionRevisionRef(r.restoredAuthority);const currentAuthority=normalizeDefinitionRevisionRef(r.currentAuthority);const restoredTrust=normalizeDefinitionRevisionRef(r.restoredTrust);const currentTrust=normalizeDefinitionRevisionRef(r.currentTrust);const restoredConfig=normalizeDefinitionRevisionRef(r.restoredConfig);const currentConfig=normalizeDefinitionRevisionRef(r.currentConfig);const evidence=normalizeDefinitionRevisionRef(r.evidence);const currentness=normalizeCurrentnessQualification(r.currentness);const locality=normalizeLocalityQualification(r.locality);assertEvidence(evidence,currentness,locality,"recovery requalification");
  if(localityKey(locality)!==localityKey(ceiling.locality)||localityKey(locality)!==localityKey(cut.locality)||localityKey(locality)!==localityKey(fencing.locality)) throw new Error("recovery locality cannot strengthen or substitute the admitted degraded locality");if(!Array.isArray(r.postCutRevocations)||!Array.isArray(r.postCutRotations)||!Array.isArray(r.postCutConfigRevisions)||!Array.isArray(r.effects)||!Array.isArray(r.residualCohorts)) throw new Error("recovery comparison collections must be arrays");
  const postCutRevocations=Object.freeze(r.postCutRevocations.map(normalizeDefinitionRevisionRef));const postCutRotations=Object.freeze(r.postCutRotations.map(normalizeDefinitionRevisionRef));const postCutConfigRevisions=Object.freeze(r.postCutConfigRevisions.map(normalizeDefinitionRevisionRef));const effects=Object.freeze(r.effects.map(normalizeRecoveryEffect));const residualCohorts=Object.freeze(r.residualCohorts.map(normalizeResidualRecoveryCohort));
  if(r.state!=="PARTIAL"&&r.state!=="VERIFIED"&&r.state!=="UNKNOWN") throw new Error("recovery verification state must be PARTIAL, VERIFIED or UNKNOWN");
  if(r.state==="VERIFIED"){
    if(currentness.state!=="CURRENT"||ceiling.policyCurrentness.state!=="CURRENT"||cut.currentness.state!=="CURRENT"||fencing.currentness.state!=="CURRENT") throw new Error("VERIFIED recovery requires current policy, cut, fencing and verification evidence");
    if(revisionKey(restoredAuthority)!==revisionKey(currentAuthority)||revisionKey(restoredTrust)!==revisionKey(currentTrust)||revisionKey(restoredConfig)!==revisionKey(currentConfig)) throw new Error("restore completion does not imply current authority, trust or config; stale restored state must not be resurrected");
    if(postCutRevocations.length!==0||postCutRotations.length!==0||postCutConfigRevisions.length!==0) throw new Error("VERIFIED recovery requires explicit reconciliation of every post-cut revocation, rotation and config revision");
    if(effects.some(effect=>effect.knowledge==="UNKNOWN"&&effect.duplicateSafety!=="PROVEN")) throw new Error("VERIFIED recovery cannot hide ambiguous external effects");
    if(residualCohorts.some(cohort=>cohort.disposition!=="DRAINED"||cohort.currentness.state!=="CURRENT")) throw new Error("VERIFIED recovery requires all residual old-path/security cohorts to be explicitly drained");
  }
  return Object.freeze({contractVersion:version(r.contractVersion),ceiling,cut,fencing,restoredAuthority,currentAuthority,restoredTrust,currentTrust,restoredConfig,currentConfig,postCutRevocations,postCutRotations,postCutConfigRevisions,effects,residualCohorts,evidence,currentness,locality,state:r.state});
}
