import { normalizeAuthorizationDecision, type AuthorizationDecision } from "./index.js";
import { normalizeCurrentnessQualification, normalizeDefinitionRevisionRef, type CurrentnessQualification, type DefinitionRevisionRef } from "../semantic-substrate/index.js";
import { normalizeLocalityQualification, type LocalityQualification } from "../semantic-substrate/federation.js";

export const RECOVERY_CONTRACT_VERSION = "1.0.0" as const;
export type RestoreState = "RESTORED" | "PARTIAL" | "UNKNOWN";
export type RecoveryVerificationState = "VERIFIED" | "PARTIAL" | "UNKNOWN";
export type OldActorState = "QUIESCED" | "ACTIVE" | "UNKNOWN";
export type ExternalEffectOutcome = "APPLIED" | "NOT_APPLIED" | "UNKNOWN";
export type RetryDisposition = "SAFE_TO_RETRY" | "RECONCILE_BEFORE_RETRY" | "DO_NOT_RETRY";
export type ResidualRecoveryKind = "OLD_ACTOR" | "TRUST" | "CONFIG" | "CACHE" | "OFFLINE" | "RECOVERY_PATH";
export type ResidualRecoveryDisposition = "ACTIVE" | "FENCED" | "DRAINED" | "UNKNOWN";
export type PopulationKnowledge = "KNOWN" | "UNKNOWN";
const REQUIRED_RESIDUAL_KINDS: readonly ResidualRecoveryKind[] = ["OLD_ACTOR","TRUST","CONFIG","CACHE","OFFLINE","RECOVERY_PATH"];

type UnknownRecord = Record<string, unknown>;
const asRecord=(value:unknown,label:string):UnknownRecord=>{if(typeof value!=="object"||value===null||Array.isArray(value)) throw new Error(`${label} must be an object`);return value as UnknownRecord;};
const exact=(record:UnknownRecord,fields:readonly string[],label:string)=>{for(const key of Object.keys(record)) if(!fields.includes(key)) throw new Error(`${label} has unexpected field ${key}`);for(const key of fields) if(!(key in record)) throw new Error(`${label} is missing field ${key}`);};
const nonEmpty=(value:unknown,label:string):string=>{if(typeof value!=="string"||value.trim()==="") throw new Error(`${label} must be non-empty`);return value.trim();};
const version=(value:unknown)=>{if(value!==RECOVERY_CONTRACT_VERSION) throw new Error("unsupported recovery contract version");return RECOVERY_CONTRACT_VERSION;};
const revisionKey=(value:DefinitionRevisionRef)=>[value.semanticOwner,value.semanticKind,value.canonicalRef,value.definitionRef,value.revisionOwner,value.revisionDimension,value.revisionRef].join("\0");
const definitionKey=(value:DefinitionRevisionRef)=>[value.semanticOwner,value.semanticKind,value.canonicalRef,value.definitionRef].join("\0");
const localityKey=(value:LocalityQualification)=>`${value.scopeKind}\0${value.localityRef}`;
const assertEvidence=(evidence:DefinitionRevisionRef,currentness:CurrentnessQualification,locality:LocalityQualification,label:string)=>{if(revisionKey(currentness.subject)!==revisionKey(evidence)) throw new Error(`${label} currentness must qualify exact evidence revision`);if(currentness.localityScope!==locality.localityRef) throw new Error(`${label} currentness locality must match evidence locality`);};

export type DegradedAuthorityCeiling = Readonly<{contractVersion:typeof RECOVERY_CONTRACT_VERSION;sourceDecision:AuthorizationDecision;allowedScope:string;prohibitedScopes:readonly string[];locality:LocalityQualification;horizonEvidence:DefinitionRevisionRef;currentness:CurrentnessQualification;expiresAt:string;reviewCondition:string}>;
export type RecoveryCut = Readonly<{contractVersion:typeof RECOVERY_CONTRACT_VERSION;sourceCut:DefinitionRevisionRef;restoredAuthority:DefinitionRevisionRef;currentAuthority:DefinitionRevisionRef;restoredTrust:DefinitionRevisionRef;currentTrust:DefinitionRevisionRef;restoredConfig:DefinitionRevisionRef;currentConfig:DefinitionRevisionRef;postCutRevocations:readonly DefinitionRevisionRef[];postCutRotations:readonly DefinitionRevisionRef[];postCutConfigRevisions:readonly DefinitionRevisionRef[];restoreState:RestoreState;locality:LocalityQualification}>;
export type FencingObservation = Readonly<{contractVersion:typeof RECOVERY_CONTRACT_VERSION;actor:DefinitionRevisionRef;epoch:DefinitionRevisionRef;supersededEpoch:DefinitionRevisionRef|null;oldActorState:OldActorState;evidence:DefinitionRevisionRef;currentness:CurrentnessQualification;locality:LocalityQualification}>;
export type ExternalEffectAssessment = Readonly<{contractVersion:typeof RECOVERY_CONTRACT_VERSION;effectRef:string;outcome:ExternalEffectOutcome;retryDisposition:RetryDisposition;duplicateSafetyEvidence:DefinitionRevisionRef|null;currentness:CurrentnessQualification|null;locality:LocalityQualification}>;
export type ResidualRecoveryCohort = Readonly<{contractVersion:typeof RECOVERY_CONTRACT_VERSION;cohortRef:string;kind:ResidualRecoveryKind;generation:DefinitionRevisionRef;populationKnowledge:PopulationKnowledge;population:number|null;disposition:ResidualRecoveryDisposition;evidence:DefinitionRevisionRef;currentness:CurrentnessQualification;locality:LocalityQualification}>;
export type RecoveryVerification = Readonly<{contractVersion:typeof RECOVERY_CONTRACT_VERSION;ceiling:DegradedAuthorityCeiling;cut:RecoveryCut;fencing:FencingObservation;effect:ExternalEffectAssessment;residualCohorts:readonly ResidualRecoveryCohort[];reprotectionEvidence:DefinitionRevisionRef;currentness:CurrentnessQualification;locality:LocalityQualification;state:RecoveryVerificationState}>;

export function normalizeDegradedAuthorityCeiling(input:unknown):DegradedAuthorityCeiling{
  const r=asRecord(input,"degraded authority ceiling");exact(r,["contractVersion","sourceDecision","allowedScope","prohibitedScopes","locality","horizonEvidence","currentness","expiresAt","reviewCondition"],"degraded authority ceiling");
  const sourceDecision=normalizeAuthorizationDecision(r.sourceDecision);if(sourceDecision.disposition!=="ALLOW") throw new Error("degraded authority ceiling requires an existing ALLOW source decision; failure cannot mint authority");
  const locality=normalizeLocalityQualification(r.locality);if(localityKey(locality)!==localityKey(sourceDecision.request.requested.locality)) throw new Error("degraded locality cannot strengthen or substitute source authority locality");
  const allowedScope=nonEmpty(r.allowedScope,"allowed scope");if(allowedScope!==sourceDecision.request.requested.scope) throw new Error("degraded allowed scope cannot expand or substitute source authority scope");
  if(!Array.isArray(r.prohibitedScopes)||r.prohibitedScopes.length===0||r.prohibitedScopes.some(v=>typeof v!=="string"||v.trim()==="")) throw new Error("degraded mode must declare explicit prohibited scopes");
  const horizonEvidence=normalizeDefinitionRevisionRef(r.horizonEvidence);const currentness=normalizeCurrentnessQualification(r.currentness);assertEvidence(horizonEvidence,currentness,locality,"degraded horizon");if(currentness.state!=="CURRENT") throw new Error("degraded authority ceiling requires CURRENT horizon evidence");
  const expiresAt=nonEmpty(r.expiresAt,"expiry");const expiryMs=Date.parse(expiresAt);const horizonUntilMs=Date.parse(currentness.currentnessHorizon.validUntil);if(!Number.isFinite(expiryMs)||!Number.isFinite(horizonUntilMs)||expiryMs>horizonUntilMs) throw new Error("degraded authority expiry must be a valid timestamp within the proven currentness horizon");
  return Object.freeze({contractVersion:version(r.contractVersion),sourceDecision,allowedScope,prohibitedScopes:Object.freeze(r.prohibitedScopes.map(v=>(v as string).trim())),locality,horizonEvidence,currentness,expiresAt,reviewCondition:nonEmpty(r.reviewCondition,"review condition")});
}

const revisions=(value:unknown,label:string):readonly DefinitionRevisionRef[]=>{if(!Array.isArray(value)) throw new Error(`${label} must be an array`);return Object.freeze(value.map(normalizeDefinitionRevisionRef));};
export function normalizeRecoveryCut(input:unknown):RecoveryCut{
  const r=asRecord(input,"recovery cut");exact(r,["contractVersion","sourceCut","restoredAuthority","currentAuthority","restoredTrust","currentTrust","restoredConfig","currentConfig","postCutRevocations","postCutRotations","postCutConfigRevisions","restoreState","locality"],"recovery cut");
  const sourceCut=normalizeDefinitionRevisionRef(r.sourceCut),restoredAuthority=normalizeDefinitionRevisionRef(r.restoredAuthority),currentAuthority=normalizeDefinitionRevisionRef(r.currentAuthority),restoredTrust=normalizeDefinitionRevisionRef(r.restoredTrust),currentTrust=normalizeDefinitionRevisionRef(r.currentTrust),restoredConfig=normalizeDefinitionRevisionRef(r.restoredConfig),currentConfig=normalizeDefinitionRevisionRef(r.currentConfig),locality=normalizeLocalityQualification(r.locality);
  if(r.restoreState!=="RESTORED"&&r.restoreState!=="PARTIAL"&&r.restoreState!=="UNKNOWN") throw new Error("invalid restore state");for(const [a,b,label] of [[restoredAuthority,currentAuthority,"authority"],[restoredTrust,currentTrust,"trust"],[restoredConfig,currentConfig,"config"]] as const) if(definitionKey(a)!==definitionKey(b)) throw new Error(`restored and current ${label} must remain on the same definition lineage`);
  return Object.freeze({contractVersion:version(r.contractVersion),sourceCut,restoredAuthority,currentAuthority,restoredTrust,currentTrust,restoredConfig,currentConfig,postCutRevocations:revisions(r.postCutRevocations,"post-cut revocations"),postCutRotations:revisions(r.postCutRotations,"post-cut rotations"),postCutConfigRevisions:revisions(r.postCutConfigRevisions,"post-cut config revisions"),restoreState:r.restoreState,locality});
}

export function normalizeFencingObservation(input:unknown):FencingObservation{
  const r=asRecord(input,"fencing observation");exact(r,["contractVersion","actor","epoch","supersededEpoch","oldActorState","evidence","currentness","locality"],"fencing observation");const actor=normalizeDefinitionRevisionRef(r.actor),epoch=normalizeDefinitionRevisionRef(r.epoch),supersededEpoch=r.supersededEpoch===null?null:normalizeDefinitionRevisionRef(r.supersededEpoch),evidence=normalizeDefinitionRevisionRef(r.evidence),currentness=normalizeCurrentnessQualification(r.currentness),locality=normalizeLocalityQualification(r.locality);assertEvidence(evidence,currentness,locality,"fencing");
  if(r.oldActorState!=="QUIESCED"&&r.oldActorState!=="ACTIVE"&&r.oldActorState!=="UNKNOWN") throw new Error("invalid old actor state");if(supersededEpoch!==null&&revisionKey(supersededEpoch)===revisionKey(epoch)) throw new Error("superseded fencing epoch cannot be reused as admitted epoch");return Object.freeze({contractVersion:version(r.contractVersion),actor,epoch,supersededEpoch,oldActorState:r.oldActorState,evidence,currentness,locality});
}

export function normalizeExternalEffectAssessment(input:unknown):ExternalEffectAssessment{
  const r=asRecord(input,"external effect assessment");exact(r,["contractVersion","effectRef","outcome","retryDisposition","duplicateSafetyEvidence","currentness","locality"],"external effect assessment");const locality=normalizeLocalityQualification(r.locality);if(r.outcome!=="APPLIED"&&r.outcome!=="NOT_APPLIED"&&r.outcome!=="UNKNOWN") throw new Error("invalid external effect outcome");if(r.retryDisposition!=="SAFE_TO_RETRY"&&r.retryDisposition!=="RECONCILE_BEFORE_RETRY"&&r.retryDisposition!=="DO_NOT_RETRY") throw new Error("invalid retry disposition");
  let duplicateSafetyEvidence:DefinitionRevisionRef|null=null,currentness:CurrentnessQualification|null=null;if(r.duplicateSafetyEvidence!==null){duplicateSafetyEvidence=normalizeDefinitionRevisionRef(r.duplicateSafetyEvidence);if(r.currentness===null) throw new Error("duplicate-safety evidence requires currentness");currentness=normalizeCurrentnessQualification(r.currentness);assertEvidence(duplicateSafetyEvidence,currentness,locality,"duplicate safety");}else if(r.currentness!==null) throw new Error("currentness without duplicate-safety evidence is invalid");if(r.outcome==="UNKNOWN"&&r.retryDisposition==="SAFE_TO_RETRY"&&(duplicateSafetyEvidence===null||currentness?.state!=="CURRENT")) throw new Error("UNKNOWN effect must reconcile-before-retry unless duplicate safety is independently proven current");return Object.freeze({contractVersion:version(r.contractVersion),effectRef:nonEmpty(r.effectRef,"effect ref"),outcome:r.outcome,retryDisposition:r.retryDisposition,duplicateSafetyEvidence,currentness,locality});
}

function normalizePopulation(knowledge:unknown,population:unknown):{knowledge:PopulationKnowledge;population:number|null}{if(knowledge!=="KNOWN"&&knowledge!=="UNKNOWN") throw new Error("residual population knowledge must be KNOWN or UNKNOWN");if(knowledge==="UNKNOWN"){if(population!==null) throw new Error("UNKNOWN residual population must remain null, never zero-defaulted");return {knowledge,population:null};}if(typeof population!=="number"||!Number.isInteger(population)||population<0) throw new Error("KNOWN residual population must be a non-negative integer");return {knowledge,population};}
export function normalizeResidualRecoveryCohort(input:unknown):ResidualRecoveryCohort{
  const r=asRecord(input,"residual recovery cohort");exact(r,["contractVersion","cohortRef","kind","generation","populationKnowledge","population","disposition","evidence","currentness","locality"],"residual recovery cohort");const generation=normalizeDefinitionRevisionRef(r.generation),evidence=normalizeDefinitionRevisionRef(r.evidence),currentness=normalizeCurrentnessQualification(r.currentness),locality=normalizeLocalityQualification(r.locality);assertEvidence(evidence,currentness,locality,"residual recovery cohort");if(!REQUIRED_RESIDUAL_KINDS.includes(r.kind as ResidualRecoveryKind)) throw new Error("invalid residual recovery kind");if(!["ACTIVE","FENCED","DRAINED","UNKNOWN"].includes(String(r.disposition))) throw new Error("invalid residual recovery disposition");const p=normalizePopulation(r.populationKnowledge,r.population);if(r.disposition==="DRAINED"&&(currentness.state!=="CURRENT"||p.knowledge!=="KNOWN"||p.population!==0)) throw new Error("DRAINED residual recovery cohort requires CURRENT known zero population evidence");return Object.freeze({contractVersion:version(r.contractVersion),cohortRef:nonEmpty(r.cohortRef,"cohort ref"),kind:r.kind as ResidualRecoveryKind,generation,populationKnowledge:p.knowledge,population:p.population,disposition:r.disposition as ResidualRecoveryDisposition,evidence,currentness,locality});
}

export function normalizeRecoveryVerification(input:unknown):RecoveryVerification{
  const r=asRecord(input,"recovery verification");exact(r,["contractVersion","ceiling","cut","fencing","effect","residualCohorts","reprotectionEvidence","currentness","locality","state"],"recovery verification");const ceiling=normalizeDegradedAuthorityCeiling(r.ceiling),cut=normalizeRecoveryCut(r.cut),fencing=normalizeFencingObservation(r.fencing),effect=normalizeExternalEffectAssessment(r.effect),reprotectionEvidence=normalizeDefinitionRevisionRef(r.reprotectionEvidence),currentness=normalizeCurrentnessQualification(r.currentness),locality=normalizeLocalityQualification(r.locality);assertEvidence(reprotectionEvidence,currentness,locality,"recovery verification");if(!Array.isArray(r.residualCohorts)) throw new Error("residual recovery cohorts must be an array");const residualCohorts=Object.freeze(r.residualCohorts.map(normalizeResidualRecoveryCohort));
  if(!["VERIFIED","PARTIAL","UNKNOWN"].includes(String(r.state))) throw new Error("invalid recovery verification state");if(localityKey(locality)!==localityKey(ceiling.locality)||localityKey(locality)!==localityKey(cut.locality)||localityKey(locality)!==localityKey(fencing.locality)||localityKey(locality)!==localityKey(effect.locality)||residualCohorts.some(c=>localityKey(c.locality)!==localityKey(locality))) throw new Error("recovery locality cannot strengthen or substitute source locality");
  if(r.state==="VERIFIED"){if(cut.restoreState!=="RESTORED"||currentness.state!=="CURRENT"||fencing.currentness.state!=="CURRENT"||fencing.oldActorState!=="QUIESCED") throw new Error("VERIFIED recovery requires restored state, current evidence and independently observed old-actor quiescence");if(revisionKey(cut.restoredAuthority)!==revisionKey(cut.currentAuthority)||revisionKey(cut.restoredTrust)!==revisionKey(cut.currentTrust)||revisionKey(cut.restoredConfig)!==revisionKey(cut.currentConfig)) throw new Error("restore completion cannot promote stale authority, trust or config to current");if(cut.postCutRevocations.length+cut.postCutRotations.length+cut.postCutConfigRevisions.length===0) throw new Error("VERIFIED recovery requires explicit post-cut comparison evidence");if(effect.outcome==="UNKNOWN"&&effect.retryDisposition!=="RECONCILE_BEFORE_RETRY"&&effect.duplicateSafetyEvidence===null) throw new Error("verified recovery cannot strengthen UNKNOWN external effects");const kinds=new Set(residualCohorts.map(c=>c.kind));if(kinds.size!==REQUIRED_RESIDUAL_KINDS.length||REQUIRED_RESIDUAL_KINDS.some(kind=>!kinds.has(kind))) throw new Error("VERIFIED recovery requires explicit evidence for every residual old-path/security cohort kind; omitted cohorts remain hidden residuals");if(residualCohorts.some(c=>c.disposition!=="DRAINED"||c.populationKnowledge!=="KNOWN"||c.population!==0||c.currentness.state!=="CURRENT")) throw new Error("VERIFIED recovery requires every residual old-path/security cohort to be explicitly drained");}
  return Object.freeze({contractVersion:version(r.contractVersion),ceiling,cut,fencing,effect,residualCohorts,reprotectionEvidence,currentness,locality,state:r.state as RecoveryVerificationState});
}
