import { normalizeCurrentnessQualification, normalizeDefinitionRevisionRef, type CurrentnessQualification, type DefinitionRevisionRef } from "../semantic-substrate/index.js";
import { normalizeLocalityQualification, type LocalityQualification } from "../semantic-substrate/federation.js";
import { IDENTITY_AUTHORIZATION_CONTRACT_VERSION, normalizeIdentityReference, type IdentityReference } from "./index.js";

export const REVOCATION_CONVERGENCE_CONTRACT_VERSION = "1.0.0" as const;
export type RevocationIntentKind = "REVOKED" | "DEPROVISIONED";
export type ObservedAuthorityState = "ACTIVE" | "REVOKED" | "DEPROVISIONED" | "UNKNOWN";
export type ConvergenceStatus = "PENDING" | "PARTIAL" | "CONVERGED" | "UNKNOWN";
export type ResidualAuthorityCohortKind = "SESSION" | "TOKEN" | "CACHE" | "OFFLINE";
export type ResidualPopulationCount = number | "UNKNOWN";
export type ResidualAuthorityCohort = Readonly<{ kind: ResidualAuthorityCohortKind; populationCount: ResidualPopulationCount; evidence: DefinitionRevisionRef; currentness: CurrentnessQualification; locality: LocalityQualification }>;
export type RevocationIntent = Readonly<{ contractVersion: typeof REVOCATION_CONVERGENCE_CONTRACT_VERSION; identity: IdentityReference; authorityRevision: DefinitionRevisionRef; desiredState: RevocationIntentKind; evidence: DefinitionRevisionRef; currentness: CurrentnessQualification; locality: LocalityQualification }>;
export type RevocationConvergence = Readonly<{ contractVersion: typeof REVOCATION_CONVERGENCE_CONTRACT_VERSION; intent: RevocationIntent; observedAuthorityRevision: DefinitionRevisionRef; observedState: ObservedAuthorityState; acknowledged: boolean; status: ConvergenceStatus; convergenceEvidence: DefinitionRevisionRef; convergenceCurrentness: CurrentnessQualification; residualCohorts: readonly ResidualAuthorityCohort[] }>;

type UnknownRecord = Record<string, unknown>;
function asRecord(value: unknown, label: string): UnknownRecord { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error(`${label} must be an object`); return value as UnknownRecord; }
function exact(record: UnknownRecord, fields: readonly string[], label: string): void { for (const key of Object.keys(record)) if (!fields.includes(key)) throw new Error(`${label} has unexpected field ${key}`); for (const key of fields) if (!(key in record)) throw new Error(`${label} is missing field ${key}`); }
function revisionKey(value: DefinitionRevisionRef): string { return [value.semanticOwner, value.semanticKind, value.canonicalRef, value.definitionRef, value.revisionOwner, value.revisionDimension, value.revisionRef].join("\u0000"); }
function localityKey(value: LocalityQualification): string { return `${value.scopeKind}\u0000${value.localityRef}`; }
function normalizeResidualCohort(input: unknown, intentLocality: LocalityQualification): ResidualAuthorityCohort { const record = asRecord(input, "residual authority cohort"); exact(record, ["kind", "populationCount", "evidence", "currentness", "locality"], "residual authority cohort"); if (record.kind !== "SESSION" && record.kind !== "TOKEN" && record.kind !== "CACHE" && record.kind !== "OFFLINE") throw new Error("residual cohort kind must be SESSION, TOKEN, CACHE or OFFLINE"); if (record.populationCount !== "UNKNOWN" && (!Number.isInteger(record.populationCount) || Number(record.populationCount) <= 0)) throw new Error("residual cohort populationCount must be a positive integer or UNKNOWN; zero-default is forbidden"); const evidence = normalizeDefinitionRevisionRef(record.evidence); const currentness = normalizeCurrentnessQualification(record.currentness); if (revisionKey(currentness.subject) !== revisionKey(evidence)) throw new Error("residual cohort currentness must qualify the exact evidence revision"); const locality = normalizeLocalityQualification(record.locality); if (localityKey(locality) !== localityKey(intentLocality) || currentness.localityScope !== locality.localityRef) throw new Error("residual cohort locality cannot be strengthened or substituted"); return Object.freeze({ kind: record.kind, populationCount: record.populationCount as ResidualPopulationCount, evidence, currentness, locality }); }
export function normalizeRevocationIntent(input: unknown): RevocationIntent { const record = asRecord(input, "revocation intent"); exact(record, ["contractVersion", "identity", "authorityRevision", "desiredState", "evidence", "currentness", "locality"], "revocation intent"); if (record.contractVersion !== REVOCATION_CONVERGENCE_CONTRACT_VERSION) throw new Error(`unsupported revocation convergence contract version: ${String(record.contractVersion)}`); if (record.desiredState !== "REVOKED" && record.desiredState !== "DEPROVISIONED") throw new Error("desired revocation state must be REVOKED or DEPROVISIONED"); const identity = normalizeIdentityReference(record.identity); if (identity.contractVersion !== IDENTITY_AUTHORIZATION_CONTRACT_VERSION) throw new Error("identity contract version mismatch"); const authorityRevision = normalizeDefinitionRevisionRef(record.authorityRevision); const evidence = normalizeDefinitionRevisionRef(record.evidence); const currentness = normalizeCurrentnessQualification(record.currentness); if (revisionKey(currentness.subject) !== revisionKey(evidence)) throw new Error("revocation currentness must qualify the exact evidence revision"); const locality = normalizeLocalityQualification(record.locality); if (currentness.localityScope !== locality.localityRef) throw new Error("revocation currentness locality must exactly match intent locality"); return Object.freeze({ contractVersion: REVOCATION_CONVERGENCE_CONTRACT_VERSION, identity, authorityRevision, desiredState: record.desiredState, evidence, currentness, locality }); }
export function normalizeRevocationConvergence(input: unknown, expectedAuthorityRevision?: DefinitionRevisionRef): RevocationConvergence { const record = asRecord(input, "revocation convergence"); exact(record, ["contractVersion", "intent", "observedAuthorityRevision", "observedState", "acknowledged", "status", "convergenceEvidence", "convergenceCurrentness", "residualCohorts"], "revocation convergence"); if (record.contractVersion !== REVOCATION_CONVERGENCE_CONTRACT_VERSION) throw new Error(`unsupported revocation convergence contract version: ${String(record.contractVersion)}`); const intent = normalizeRevocationIntent(record.intent); if (expectedAuthorityRevision !== undefined && revisionKey(intent.authorityRevision) !== revisionKey(normalizeDefinitionRevisionRef(expectedAuthorityRevision))) throw new Error("revocation intent authority revision does not match the exact expected revision"); const observedAuthorityRevision = normalizeDefinitionRevisionRef(record.observedAuthorityRevision); if (revisionKey(observedAuthorityRevision) !== revisionKey(intent.authorityRevision)) throw new Error("observed authority revision cannot substitute or resurrect another revision"); if (record.observedState !== "ACTIVE" && record.observedState !== "REVOKED" && record.observedState !== "DEPROVISIONED" && record.observedState !== "UNKNOWN") throw new Error("observed authority state is invalid"); if (typeof record.acknowledged !== "boolean") throw new Error("acknowledged must be boolean"); if (record.status !== "PENDING" && record.status !== "PARTIAL" && record.status !== "CONVERGED" && record.status !== "UNKNOWN") throw new Error("convergence status is invalid"); const convergenceEvidence = normalizeDefinitionRevisionRef(record.convergenceEvidence); const convergenceCurrentness = normalizeCurrentnessQualification(record.convergenceCurrentness); if (revisionKey(convergenceCurrentness.subject) !== revisionKey(convergenceEvidence)) throw new Error("convergence currentness must qualify the exact convergence evidence revision"); if (convergenceCurrentness.localityScope !== intent.locality.localityRef) throw new Error("convergence evidence locality cannot be strengthened or substituted"); if (!Array.isArray(record.residualCohorts)) throw new Error("residualCohorts must be an explicit array"); const residualCohorts = Object.freeze(record.residualCohorts.map((value) => normalizeResidualCohort(value, intent.locality))); const seen = new Set<string>(); for (const cohort of residualCohorts) { if (seen.has(cohort.kind)) throw new Error(`duplicate residual cohort kind ${cohort.kind}`); seen.add(cohort.kind); }
 if (record.status === "CONVERGED") { if (record.observedState !== intent.desiredState) throw new Error("convergence requires observed authority state to equal desired revoked/deprovisioned state"); if (residualCohorts.length !== 0) throw new Error("residual cohorts must be drained before convergence"); if (intent.currentness.state !== "CURRENT" || convergenceCurrentness.state !== "CURRENT") throw new Error("UNKNOWN/PARTIAL or stale revocation/reconciliation evidence cannot become fully converged"); } else if (record.observedState === intent.desiredState && residualCohorts.length === 0 && intent.currentness.state === "CURRENT" && record.acknowledged === true) { /* acknowledgement may coexist with a non-converged status; it never promotes status itself */ }
 return Object.freeze({ contractVersion: REVOCATION_CONVERGENCE_CONTRACT_VERSION, intent, observedAuthorityRevision, observedState: record.observedState, acknowledged: record.acknowledged, status: record.status, convergenceEvidence, convergenceCurrentness, residualCohorts }); }
