import { normalizeCurrentnessQualification, normalizeDefinitionRevisionRef, type CurrentnessQualification, type DefinitionRevisionRef } from "../semantic-substrate/index.js";
import { normalizeLocalityQualification, type LocalityQualification } from "../semantic-substrate/federation.js";

export const ROTATION_DRAINAGE_CONTRACT_VERSION = "1.0.0" as const;
export type RotationDomain = "TRUST" | "SECRET_CONFIG";
export type PopulationKnowledge = "KNOWN" | "UNKNOWN";
export type AdoptionDisposition = "ADOPTED" | "PARTIAL" | "STALE" | "UNKNOWN";
export type ResidualDisposition = "AUTHORITATIVE" | "FENCED" | "DRAINED" | "UNKNOWN";
export type ConvergenceState = "PARTIAL" | "CONVERGED" | "UNKNOWN";
export type ResidualCohortKind = "VERIFIER" | "CONSUMER" | "CACHE" | "OFFLINE" | "RECOVERY";
const REQUIRED_RESIDUAL_COHORT_KINDS: readonly ResidualCohortKind[] = ["VERIFIER", "CONSUMER", "CACHE", "OFFLINE", "RECOVERY"];

type UnknownRecord = Record<string, unknown>;
const asRecord=(value:unknown,label:string):UnknownRecord=>{if(typeof value!=="object"||value===null||Array.isArray(value)) throw new Error(`${label} must be an object`);return value as UnknownRecord;};
const exact=(record:UnknownRecord,required:readonly string[],label:string)=>{for(const key of Object.keys(record)) if(!required.includes(key)) throw new Error(`${label} has unexpected field ${key}`);for(const key of required) if(!(key in record)) throw new Error(`${label} is missing field ${key}`);};
const nonEmpty=(value:unknown,label:string):string=>{if(typeof value!=="string"||value.trim()==="") throw new Error(`${label} must be non-empty`);return value.trim();};
const version=(value:unknown)=>{if(value!==ROTATION_DRAINAGE_CONTRACT_VERSION) throw new Error("unsupported rotation/drainage contract version");return ROTATION_DRAINAGE_CONTRACT_VERSION;};
const revisionKey=(value:DefinitionRevisionRef)=>[value.semanticOwner,value.semanticKind,value.canonicalRef,value.definitionRef,value.revisionOwner,value.revisionDimension,value.revisionRef].join("\0");
const definitionKey=(value:DefinitionRevisionRef)=>[value.semanticOwner,value.semanticKind,value.canonicalRef,value.definitionRef].join("\0");
const localityKey=(value:LocalityQualification)=>`${value.scopeKind}\0${value.localityRef}`;

export type RotationIntent = Readonly<{contractVersion:typeof ROTATION_DRAINAGE_CONTRACT_VERSION;domain:RotationDomain;oldGeneration:DefinitionRevisionRef;newGeneration:DefinitionRevisionRef;providerVersionRef:string;populationRef:string;populationKnowledge:PopulationKnowledge;eligiblePopulation:number|null;locality:LocalityQualification}>;
export type RotationAcknowledgement = Readonly<{contractVersion:typeof ROTATION_DRAINAGE_CONTRACT_VERSION;intent:RotationIntent;providerVersionRef:string;evidence:DefinitionRevisionRef;currentness:CurrentnessQualification;locality:LocalityQualification}>;
export type AdoptionObservation = Readonly<{contractVersion:typeof ROTATION_DRAINAGE_CONTRACT_VERSION;intent:RotationIntent;populationRef:string;generation:DefinitionRevisionRef;populationKnowledge:PopulationKnowledge;observedPopulation:number|null;adoptedPopulation:number|null;disposition:AdoptionDisposition;evidence:DefinitionRevisionRef;currentness:CurrentnessQualification;locality:LocalityQualification}>;
export type ResidualCohort = Readonly<{contractVersion:typeof ROTATION_DRAINAGE_CONTRACT_VERSION;intent:RotationIntent;cohortId:string;kind:ResidualCohortKind;generation:DefinitionRevisionRef;populationKnowledge:PopulationKnowledge;population:number|null;disposition:ResidualDisposition;evidence:DefinitionRevisionRef;currentness:CurrentnessQualification;locality:LocalityQualification}>;
export type RotationConvergence = Readonly<{contractVersion:typeof ROTATION_DRAINAGE_CONTRACT_VERSION;intent:RotationIntent;acknowledgement:RotationAcknowledgement;adoption:AdoptionObservation;residualCohorts:readonly ResidualCohort[];evidence:DefinitionRevisionRef;currentness:CurrentnessQualification;locality:LocalityQualification;state:ConvergenceState}>;

function normalizePopulation(knowledge:unknown,population:unknown,label:string):{knowledge:PopulationKnowledge;population:number|null}{
  if(knowledge!=="KNOWN"&&knowledge!=="UNKNOWN") throw new Error(`${label} population knowledge must be KNOWN or UNKNOWN`);
  if(knowledge==="UNKNOWN"){if(population!==null) throw new Error(`${label} UNKNOWN population must remain null, never zero-defaulted`);return {knowledge,population:null};}
  if(typeof population!=="number"||!Number.isInteger(population)||population<0) throw new Error(`${label} KNOWN population must be a non-negative integer`);
  return {knowledge,population};
}
function assertEvidence(evidence:DefinitionRevisionRef,currentness:CurrentnessQualification,locality:LocalityQualification,label:string){if(revisionKey(currentness.subject)!==revisionKey(evidence)) throw new Error(`${label} currentness must qualify exact evidence revision`);if(currentness.localityScope!==locality.localityRef) throw new Error(`${label} currentness locality must match evidence locality`);}

export function normalizeRotationIntent(input:unknown):RotationIntent{
  const r=asRecord(input,"rotation intent");exact(r,["contractVersion","domain","oldGeneration","newGeneration","providerVersionRef","populationRef","populationKnowledge","eligiblePopulation","locality"],"rotation intent");
  const oldGeneration=normalizeDefinitionRevisionRef(r.oldGeneration);const newGeneration=normalizeDefinitionRevisionRef(r.newGeneration);const locality=normalizeLocalityQualification(r.locality);
  if(r.domain!=="TRUST"&&r.domain!=="SECRET_CONFIG") throw new Error("rotation domain must be TRUST or SECRET_CONFIG");
  if(definitionKey(oldGeneration)!==definitionKey(newGeneration)) throw new Error("old and new generations must remain on the same definition lineage");
  if(revisionKey(oldGeneration)===revisionKey(newGeneration)) throw new Error("rotation requires distinct old and new generations");
  const providerVersionRef=nonEmpty(r.providerVersionRef,"provider version ref");if(providerVersionRef===oldGeneration.canonicalRef||providerVersionRef===newGeneration.canonicalRef) throw new Error("provider version cannot substitute canonical generation identity");
  const p=normalizePopulation(r.populationKnowledge,r.eligiblePopulation,"eligible");
  return Object.freeze({contractVersion:version(r.contractVersion),domain:r.domain,oldGeneration,newGeneration,providerVersionRef,populationRef:nonEmpty(r.populationRef,"population ref"),populationKnowledge:p.knowledge,eligiblePopulation:p.population,locality});
}
export function normalizeRotationAcknowledgement(input:unknown):RotationAcknowledgement{
  const r=asRecord(input,"rotation acknowledgement");exact(r,["contractVersion","intent","providerVersionRef","evidence","currentness","locality"],"rotation acknowledgement");const intent=normalizeRotationIntent(r.intent);const evidence=normalizeDefinitionRevisionRef(r.evidence);const currentness=normalizeCurrentnessQualification(r.currentness);const locality=normalizeLocalityQualification(r.locality);const providerVersionRef=nonEmpty(r.providerVersionRef,"provider version ref");
  if(providerVersionRef!==intent.providerVersionRef) throw new Error("provider version substitution is not allowed");if(localityKey(locality)!==localityKey(intent.locality)) throw new Error("acknowledgement locality cannot strengthen or substitute intent locality");assertEvidence(evidence,currentness,locality,"acknowledgement");
  return Object.freeze({contractVersion:version(r.contractVersion),intent,providerVersionRef,evidence,currentness,locality});
}
export function normalizeAdoptionObservation(input:unknown):AdoptionObservation{
  const r=asRecord(input,"adoption observation");exact(r,["contractVersion","intent","populationRef","generation","populationKnowledge","observedPopulation","adoptedPopulation","disposition","evidence","currentness","locality"],"adoption observation");const intent=normalizeRotationIntent(r.intent);const generation=normalizeDefinitionRevisionRef(r.generation);const evidence=normalizeDefinitionRevisionRef(r.evidence);const currentness=normalizeCurrentnessQualification(r.currentness);const locality=normalizeLocalityQualification(r.locality);
  if(nonEmpty(r.populationRef,"population ref")!==intent.populationRef) throw new Error("adoption population cannot substitute intent population");if(revisionKey(generation)!==revisionKey(intent.newGeneration)) throw new Error("adoption must target the exact new generation");if(localityKey(locality)!==localityKey(intent.locality)) throw new Error("adoption locality cannot strengthen or substitute intent locality");assertEvidence(evidence,currentness,locality,"adoption");
  const observed=normalizePopulation(r.populationKnowledge,r.observedPopulation,"observed");const adopted=normalizePopulation(r.populationKnowledge,r.adoptedPopulation,"adopted");if(!["ADOPTED","PARTIAL","STALE","UNKNOWN"].includes(String(r.disposition))) throw new Error("invalid adoption disposition");
  if(r.disposition==="ADOPTED"){if(currentness.state!=="CURRENT"||observed.knowledge!=="KNOWN"||adopted.knowledge!=="KNOWN"||observed.population!==adopted.population||intent.populationKnowledge!=="KNOWN"||observed.population!==intent.eligiblePopulation) throw new Error("ADOPTED requires current evidence for the complete known eligible population");}
  return Object.freeze({contractVersion:version(r.contractVersion),intent,populationRef:intent.populationRef,generation,populationKnowledge:observed.knowledge,observedPopulation:observed.population,adoptedPopulation:adopted.population,disposition:r.disposition as AdoptionDisposition,evidence,currentness,locality});
}
export function normalizeResidualCohort(input:unknown):ResidualCohort{
  const r=asRecord(input,"residual cohort");exact(r,["contractVersion","intent","cohortId","kind","generation","populationKnowledge","population","disposition","evidence","currentness","locality"],"residual cohort");const intent=normalizeRotationIntent(r.intent);const generation=normalizeDefinitionRevisionRef(r.generation);const evidence=normalizeDefinitionRevisionRef(r.evidence);const currentness=normalizeCurrentnessQualification(r.currentness);const locality=normalizeLocalityQualification(r.locality);
  if(!["VERIFIER","CONSUMER","CACHE","OFFLINE","RECOVERY"].includes(String(r.kind))) throw new Error("invalid residual cohort kind");if(revisionKey(generation)!==revisionKey(intent.oldGeneration)) throw new Error("residual cohort must remain pinned to the old generation");if(localityKey(locality)!==localityKey(intent.locality)) throw new Error("residual locality cannot strengthen or substitute intent locality");assertEvidence(evidence,currentness,locality,"residual cohort");const p=normalizePopulation(r.populationKnowledge,r.population,"residual");if(!["AUTHORITATIVE","FENCED","DRAINED","UNKNOWN"].includes(String(r.disposition))) throw new Error("invalid residual disposition");if(r.disposition==="DRAINED"&&(currentness.state!=="CURRENT"||p.knowledge!=="KNOWN"||p.population!==0)) throw new Error("DRAINED requires current evidence of known zero residual population");
  return Object.freeze({contractVersion:version(r.contractVersion),intent,cohortId:nonEmpty(r.cohortId,"cohort id"),kind:r.kind as ResidualCohortKind,generation,populationKnowledge:p.knowledge,population:p.population,disposition:r.disposition as ResidualDisposition,evidence,currentness,locality});
}
export function normalizeRotationConvergence(input:unknown):RotationConvergence{
  const r=asRecord(input,"rotation convergence");exact(r,["contractVersion","intent","acknowledgement","adoption","residualCohorts","evidence","currentness","locality","state"],"rotation convergence");const intent=normalizeRotationIntent(r.intent);const acknowledgement=normalizeRotationAcknowledgement(r.acknowledgement);const adoption=normalizeAdoptionObservation(r.adoption);if(!Array.isArray(r.residualCohorts)) throw new Error("residual cohorts must be an array");const residualCohorts=Object.freeze(r.residualCohorts.map(normalizeResidualCohort));const evidence=normalizeDefinitionRevisionRef(r.evidence);const currentness=normalizeCurrentnessQualification(r.currentness);const locality=normalizeLocalityQualification(r.locality);assertEvidence(evidence,currentness,locality,"convergence");if(localityKey(locality)!==localityKey(intent.locality)) throw new Error("convergence locality cannot strengthen intent locality");
  if(!["PARTIAL","CONVERGED","UNKNOWN"].includes(String(r.state))) throw new Error("invalid convergence state");if(r.state==="CONVERGED"){if(currentness.state!=="CURRENT"||adoption.disposition!=="ADOPTED") throw new Error("CONVERGED requires current complete new-generation adoption");if(intent.populationKnowledge!=="KNOWN") throw new Error("UNKNOWN eligible population cannot manufacture convergence");const kinds=new Set(residualCohorts.map(c=>c.kind));if(kinds.size!==REQUIRED_RESIDUAL_COHORT_KINDS.length||REQUIRED_RESIDUAL_COHORT_KINDS.some(kind=>!kinds.has(kind))) throw new Error("CONVERGED requires explicit drainage evidence for every residual cohort kind; omitted cohorts remain hidden residuals");if(residualCohorts.some(c=>c.disposition!=="DRAINED"||c.populationKnowledge!=="KNOWN"||c.population!==0||c.currentness.state!=="CURRENT")) throw new Error("all authoritative residual cohorts must be explicitly drained before convergence");}
  return Object.freeze({contractVersion:version(r.contractVersion),intent,acknowledgement,adoption,residualCohorts,evidence,currentness,locality,state:r.state as ConvergenceState});
}
