import { normalizeCurrentnessQualification, normalizeDefinitionRevisionRef, type CurrentnessQualification, type DefinitionRevisionRef } from "../semantic-substrate/index.js";
import { normalizeLocalityQualification, type LocalityQualification } from "../semantic-substrate/federation.js";

export const TRUST_QUALIFICATION_CONTRACT_VERSION = "1.0.0" as const;
export type TrustStatus = "VALID" | "REVOKED" | "UNKNOWN";
export type CryptographicValidity = "VALID" | "INVALID" | "UNKNOWN";
export type TrustDisposition = "TRUSTED" | "REJECTED" | "UNKNOWN";
export type TrustGenerationReference = Readonly<{ contractVersion: typeof TRUST_QUALIFICATION_CONTRACT_VERSION; trustDomain: DefinitionRevisionRef; generation: DefinitionRevisionRef; providerRealizationRef: string }>;
export type CredentialStatusEvidence = Readonly<{ contractVersion: typeof TRUST_QUALIFICATION_CONTRACT_VERSION; credential: DefinitionRevisionRef; evidence: DefinitionRevisionRef; currentness: CurrentnessQualification; locality: LocalityQualification; status: TrustStatus; cryptographicValidity: CryptographicValidity }>;
export type TrustQualification = Readonly<{ contractVersion: typeof TRUST_QUALIFICATION_CONTRACT_VERSION; admittedGeneration: TrustGenerationReference; verifierEffectiveGeneration: TrustGenerationReference; credentialStatus: CredentialStatusEvidence; purpose: string; scope: string; locality: LocalityQualification; disposition: TrustDisposition }>;
export type ExpectedTrustQualificationBinding = Readonly<{ purpose: string; scope: string }>;
type UnknownRecord = Record<string, unknown>;
function asRecord(value: unknown,label:string):UnknownRecord { if(typeof value!=="object"||value===null||Array.isArray(value)) throw new Error(`${label} must be an object`); return value as UnknownRecord; }
function exact(record:UnknownRecord,fields:readonly string[],label:string):void { for(const key of Object.keys(record)) if(!fields.includes(key)) throw new Error(`${label} has unexpected field ${key}`); for(const key of fields) if(!(key in record)) throw new Error(`${label} is missing field ${key}`); }
function version(value:unknown):typeof TRUST_QUALIFICATION_CONTRACT_VERSION { if(value!==TRUST_QUALIFICATION_CONTRACT_VERSION) throw new Error(`unsupported trust qualification contract version: ${String(value)}`); return TRUST_QUALIFICATION_CONTRACT_VERSION; }
function nonEmpty(value:unknown,label:string):string { if(typeof value!=="string"||value.trim().length===0) throw new Error(`${label} must be a non-empty string`); return value.trim(); }
function revisionKey(value:DefinitionRevisionRef):string { return [value.semanticOwner,value.semanticKind,value.canonicalRef,value.definitionRef,value.revisionOwner,value.revisionDimension,value.revisionRef].join("\u0000"); }
function localityKey(value:LocalityQualification):string { return `${value.scopeKind}\u0000${value.localityRef}`; }
export function normalizeTrustGenerationReference(input:unknown):TrustGenerationReference { const record=asRecord(input,"trust generation reference"); exact(record,["contractVersion","trustDomain","generation","providerRealizationRef"],"trust generation reference"); const trustDomain=normalizeDefinitionRevisionRef(record.trustDomain); const generation=normalizeDefinitionRevisionRef(record.generation); const providerRealizationRef=nonEmpty(record.providerRealizationRef,"provider realization ref"); if(providerRealizationRef===trustDomain.canonicalRef||providerRealizationRef===generation.canonicalRef) throw new Error("provider realization id cannot substitute canonical trust identity or generation"); return Object.freeze({contractVersion:version(record.contractVersion),trustDomain,generation,providerRealizationRef}); }
export function normalizeCredentialStatusEvidence(input:unknown):CredentialStatusEvidence { const record=asRecord(input,"credential status evidence"); exact(record,["contractVersion","credential","evidence","currentness","locality","status","cryptographicValidity"],"credential status evidence"); const credential=normalizeDefinitionRevisionRef(record.credential); const evidence=normalizeDefinitionRevisionRef(record.evidence); const currentness=normalizeCurrentnessQualification(record.currentness); const locality=normalizeLocalityQualification(record.locality); if(revisionKey(currentness.subject)!==revisionKey(evidence)) throw new Error("credential status currentness must qualify the exact evidence revision"); if(currentness.localityScope!==locality.localityRef) throw new Error("credential status currentness locality must exactly match evidence locality"); if(record.status!=="VALID"&&record.status!=="REVOKED"&&record.status!=="UNKNOWN") throw new Error("credential trust status must be VALID, REVOKED or UNKNOWN"); if(record.cryptographicValidity!=="VALID"&&record.cryptographicValidity!=="INVALID"&&record.cryptographicValidity!=="UNKNOWN") throw new Error("cryptographic validity must be VALID, INVALID or UNKNOWN"); if(record.status==="VALID"&&currentness.state!=="CURRENT") throw new Error("stale or unknown status evidence cannot be promoted to VALID"); return Object.freeze({contractVersion:version(record.contractVersion),credential,evidence,currentness,locality,status:record.status,cryptographicValidity:record.cryptographicValidity}); }
export function normalizeTrustQualification(input:unknown,expected?:ExpectedTrustQualificationBinding):TrustQualification { const record=asRecord(input,"trust qualification"); exact(record,["contractVersion","admittedGeneration","verifierEffectiveGeneration","credentialStatus","purpose","scope","locality","disposition"],"trust qualification"); const admittedGeneration=normalizeTrustGenerationReference(record.admittedGeneration); const verifierEffectiveGeneration=normalizeTrustGenerationReference(record.verifierEffectiveGeneration); const credentialStatus=normalizeCredentialStatusEvidence(record.credentialStatus); const locality=normalizeLocalityQualification(record.locality); const purpose=nonEmpty(record.purpose,"trust purpose"); const scope=nonEmpty(record.scope,"trust scope"); if(expected){ const expectedPurpose=nonEmpty(expected.purpose,"expected trust purpose"); const expectedScope=nonEmpty(expected.scope,"expected trust scope"); if(purpose!==expectedPurpose) throw new Error("trust purpose cannot widen or substitute the expected purpose"); if(scope!==expectedScope) throw new Error("trust scope cannot widen or substitute the expected scope"); } if(revisionKey(admittedGeneration.trustDomain)!==revisionKey(verifierEffectiveGeneration.trustDomain)) throw new Error("verifier trust domain cannot substitute the admitted trust domain revision"); if(localityKey(credentialStatus.locality)!==localityKey(locality)) throw new Error("trust locality cannot strengthen or substitute credential evidence locality"); if(record.disposition!=="TRUSTED"&&record.disposition!=="REJECTED"&&record.disposition!=="UNKNOWN") throw new Error("trust disposition must be TRUSTED, REJECTED or UNKNOWN"); if(record.disposition==="TRUSTED") { if(revisionKey(admittedGeneration.generation)!==revisionKey(verifierEffectiveGeneration.generation)) throw new Error("desired/admitted trust generation is not verifier-effective yet"); if(credentialStatus.status!=="VALID"||credentialStatus.currentness.state!=="CURRENT"||credentialStatus.cryptographicValidity!=="VALID") throw new Error("TRUSTED requires current valid status and cryptographic validity; UNKNOWN or stale evidence cannot be strengthened"); } return Object.freeze({contractVersion:version(record.contractVersion),admittedGeneration,verifierEffectiveGeneration,credentialStatus,purpose,scope,locality,disposition:record.disposition}); }
